### ISSUE TITLE
gRPC 服务会报错UNAVAILABLE status

### ISSUE THREAD

**Issue by pigLoveRabbit520** [midwayjs/midway#1086]
错误日志：
```
Error: 14 UNAVAILABLE: Stream refused by server
    at Object.callErrorFromStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

* **Node Version**: v14.16.1
* **Egg Version**:  ^2.29.4

**Comment by czy88840616** [comment]
这个是服务端不支持流式调用吧

**Comment by mmdapl** [comment]
和proto文件比对下，看response 是否定义为stream类型了

**Comment by salamander-mh** [comment]
@czy88840616  @mmdapl  好奇怪，就没地方用到了`stream`了，很奇怪这个错。。

**Comment by mmdapl** [comment]
> @czy88840616  @mmdapl  好奇怪，就没地方用到了`stream`了，很奇怪这个错。。

得把最小的错误场景还原出来，一起调试看看..

**Comment by salamander-mh** [comment]
@mmdapl  就是线上偶现的错误（线上请求量大），我本地都很难复现，别人也碰到过类型的问题[793](https://github.com/googleapis/nodejs-firestore/issues/793)

**Comment by czy88840616** [comment]
这样看起来猜测是 grpc 底层模块的问题了。

**Comment by salamander-mh** [comment]
@czy88840616  我估计也是呢，大佬有啥好办法临时解决一下吗？

**Comment by czy88840616** [comment]
服务端是 midway 起的么？

**Comment by salamander-mh** [comment]
@czy88840616  
```
    "firebase-admin": "^8.7.0",
    "googleapis": "^42.0.0",
```
没看懂咋搞，这俩库没用过呀

**Comment by czy88840616** [comment]
这个issue里是说出现的原因是 server.start() 在 bindAsync 的回调外面。

```
//server.js
server.bindAsync(`${config.address}:${config.port}`, grpc.ServerCredentials.createInsecure(),  (err, port) => {
  if (err) {
    logger.log(err);
    process.exit(1);
  } else {
    server.start(); //here
    logger.info(`Address: ${config.address}`);
    logger.info(`Port: ${port}`);
  }
});
```

**Comment by salamander-mh** [comment]
@czy88840616  这个改了也没啥用。

**Comment by czy88840616** [comment]
如果必现的话可以给我们示例，如果运行时报错的话就比较困难了，就算是提给 grpc 那边也是需要能复现的例子的。

**Comment by lwmxiaobei** [comment]
我也遇到了，请求量大的时候会出现几个

**Comment by czy88840616** [comment]
大量是多少？感觉可以用压测来复现。
