### ISSUE TITLE
jest test failed (`yarn test`) for both web app and component

### ISSUE THREAD

**Issue by DevanXU** [midwayjs/midway#1147]
* **Node Version**: 12.16.1
* **Egg Version**: 2.29.4
* **Midway Version**: 2.11.4
* **Mini Showcase Repository**: https://github.com/DevanXU/midway-2.x-jest-failed

jest test failed when run `yarn test` for both `web app` and `comp`, reproduce steps as below:
- Create lerna project, say `demo`
- Create `demo-web` and `demo-comp` under `demo/packages`
- Install packages under `demo` thru `yarn install`
- Goto `demo-web`
- Run `yarn dev` works fine
- Run `yarn test`, it failed with below error information:
```
$ midway-bin test --ts
Testing all *.test.ts...
TypeError: Jest: a transform must export something.
    at /Users/devan/src/tmp/midway2.x/demo/node_modules/@jest/transform/build/ScriptTransformer.js:386:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at ScriptTransformer.loadTransformers (/Users/devan/src/tmp/midway2.x/demo/node_modules/@jest/transform/build/ScriptTransformer.js:378:5)
    at createScriptTransformer (/Users/devan/src/tmp/midway2.x/demo/node_modules/@jest/transform/build/ScriptTransformer.js:1106:3)
    at /Users/devan/src/tmp/midway2.x/demo/node_modules/jest-cli/node_modules/@jest/core/build/TestScheduler.js:269:31
    at async Promise.all (index 0)
    at TestScheduler.scheduleTests (/Users/devan/src/tmp/midway2.x/demo/node_modules/jest-cli/node_modules/@jest/core/build/TestScheduler.js:262:5)
    at runJest (/Users/devan/src/tmp/midway2.x/demo/node_modules/jest-cli/node_modules/@jest/core/build/runJest.js:387:19)
    at _run10000 (/Users/devan/src/tmp/midway2.x/demo/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:408:7)
```

**Comment by waitingsong** [comment]
如果 jest 版本是 27，尝试降级到 26 试试。

**Comment by DevanXU** [comment]
lerna结构的jest包要放在根目录的package.json里，在packages/xxx里的yarn test命令链接到root下的jest包，jest@27是可以工作的。

**Comment by czy88840616** [comment]
所以也可以 ../../node_modules/.bin/jest 这种相对路径吧。

**Comment by DevanXU** [comment]
> 所以也可以 ../../node_modules/.bin/jest 这种相对路径吧。

是的。在packages/xxx里的yarn test命令链接到root下的jest包用的就是 ../../node_modules/.bin/jest的相对路径。
