### ISSUE TITLE
单元测试使用jest --coverage报错

### ISSUE THREAD

**Issue by lide14** [midwayjs/midway#1180]
使用前后端一体化的koa-hooks-react的demo工程，验证单元测试可用性的时候，发现单纯使用jest指令可以正常测试成功，但加上输出--coverage会报错，错误信息如下：

 FAIL   SERVER  src/apis/lambda/index.test.ts
  ● Test suite failed to run

    TypeError: D:\Nodejs\koa-hooks-react2\src\apis\lambda\index.ts: Property typeName of TSTypeReference expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"

      at Object.validate (node_modules/@babel/types/lib/definitions/utils.js:130:11)
      at validateField (node_modules/@babel/types/lib/validators/validate.js:24:9)
      at Object.validate (node_modules/@babel/types/lib/validators/validate.js:17:3)
      at NodePath._replaceWith (node_modules/@babel/traverse/lib/path/replacement.js:179:7)
      at NodePath.replaceWith (node_modules/@babel/traverse/lib/path/replacement.js:161:8)
      at Object.ReferencedIdentifier (node_modules/@babel/helper-module-transforms/lib/rewrite-live-references.js:186:14)
      at Object.newFn (node_modules/@babel/traverse/lib/visitors.js:216:17)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:92:31)

麻烦帮忙看看是程序问题还是指令的问题，十分感谢。

**Comment by lide14** [comment]
@Lxxyx hi，请问这个问题有计划什么时候看看吗

**Comment by Lxxyx** [comment]
> @Lxxyx hi，请问这个问题有计划什么时候看看吗

尝试重新装一下依赖，使用 2.3.0 版本

**Comment by lide14** [comment]
2.3.0貌似可以了，多谢
