### ISSUE TITLE
Task模块在@midwayjs/core ^2.12.1 无法使用或报错

### ISSUE THREAD

**Issue by yyfn** [midwayjs/midway#1203]
* **Node Version**:v14.17.1
* **Egg Version**:4.18.0
* **Plugin Name**:@midwayjs/task
* **Plugin Version**:2.12.1
* **Platform**:mac 11.5（apple silicon）
* **Mini Showcase Repository**:https://github.com/yyfn/midway_task_error

新初始化midway + egg项目，根据[任务调度Task](https://www.yuque.com/midwayjs/midway_v2/task)的方法调用Task

@Task装饰器无效，但可以在redis可以看到相关任务key

@TaskLocal装饰器在到达执行任务时间会报错

错误代码：
```
ERROR 47765 TypeError: Cannot set property logger of #<Object> which has only a getter
    at AutoConfiguration.getContext (/Users/***/Desktop/midway_task_error/node_modules/@midwayjs/task/dist/configuration.js:67:20)
    at CronJob.<anonymous> (/Users/***/Desktop/midway_task_error/node_modules/@midwayjs/task/dist/configuration.js:119:38)
    at CronJob.fireOnTick (/Users/yyfn/Desktop/midway_task_error/node_modules/cron/lib/cron.js:600:23)
    at Timeout.callbackWrapper [as _onTimeout] (/Users/***/Desktop/midway_task_error/node_modules/cron/lib/cron.js:667:10)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by czy88840616** [comment]
task 模块已切回 2.11.6，可以重新安装一下

**Comment by yyfn** [comment]
2.11.6完美运行~
