### ISSUE TITLE
"xxxxx" is not valid in current context

### ISSUE THREAD

**Issue by yyshengfan** [midwayjs/midway#1217]
场景：midway/koa init的demo，使用pkg打包之后，删除掉dist文件夹，会报错
```
2021-08-10 20:29:20,810 ERROR 50387 NotFoundError [unhandledRejectionError]: remoteConfigKey is not valid in current context
    at MidwayContainer.getAsync (/snapshot/my_midway_app/node_modules/@midwayjs/core/dist/context/applicationContext.js:175:19)
    at MidwayContainer.getAsync (/snapshot/my_midway_app/node_modules/@midwayjs/core/dist/context/midwayContainer.js:475:33)
    at Object.beforeHandler (/snapshot/my_midway_app/bootstrap.js)
    at BootstrapStarter.init (/snapshot/my_midway_app/node_modules/@midwayjs/bootstrap/dist/bootstrap.js:51:54)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1805:13)
    at internal/main/run_main_module.js:17:47
    at async Function.run (/snapshot/my_midway_app/node_modules/@midwayjs/bootstrap/dist/bootstrap.js:205:9) {
  [Symbol(#NotFoundError)]: Symbol(#NotFoundError)
}
```
我是在bootstrap.js入口文件里有引用
`
Bootstrap.before(async container => {
  await container.getAsync('remoteConfigKey');
})
`
此处定义
```
import {
  App,
  Config,
  Init,
  Provide,
  Scope,
  ScopeEnum,
} from '@midwayjs/decorator';
import { IMidwayApplication } from '@midwayjs/core';

@Scope(ScopeEnum.Singleton)
@Provide()
export class RemoteConfigKey {
  @Config('nacosClient') private nacosConfig;
  @App() private app: IMidwayApplication;
  @Init() protected async init(): Promise<void> {
    console.log('nacosClient', this.nacosConfig);
    const { dataId, group } = this.nacosConfig;
    this.app.addConfigObject({ remoteConfig: this.nacosConfig });
    console.log(dataId, group);
  }
}
```
分析问题：应该是在执行时没有找到以来注入的目录，是否有办法改变contain的寻址目录

**Comment by czy88840616** [comment]
参考 #1193

**Comment by yyshengfan** [comment]
看过了，路由是有，同样也做了这个，但是接下来依赖注入的东西找不到

**Comment by czy88840616** [comment]
在入口处，也要 require('./dist/RemoteConfigKey')

**Comment by yyshengfan** [comment]
意思我用这个方法，也要手动引入一下吗？container.getAsync('remoteConfigKey');

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/128871958-4bea456f-3175-4ff2-9438-a04ece83de7c.png)
主要是这里。

**Comment by yyshengfan** [comment]
好的，谢谢，我试试
