### ISSUE TITLE
ConnectionNotFoundError: Connection "default" was not found.

### ISSUE THREAD

**Issue by mdsb100** [midwayjs/midway#1220]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

2021-08-11 11:58:18,110 ERROR 16651 ConnectionNotFoundError: Connection "default" was not found.
    at ConnectionNotFoundError.TypeORMError [as constructor] (/Users/caojun79/project/pubfree/pubfree-server/server/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new ConnectionNotFoundError (/Users/caojun79/project/pubfree/pubfree-server/server/node_modules/typeorm/error/ConnectionNotFoundError.js:12:23)
    at ConnectionManager.get (/Users/caojun79/project/pubfree/pubfree-server/server/node_modules/typeorm/connection/ConnectionManager.js:48:19)
    at Object.getCustomRepository (/Users/caojun79/project/pubfree/pubfree-server/server/node_modules/typeorm/globals.js:160:35)
    at new BambooService (/Users/caojun79/project/pubfree/pubfree-server/server/dist/service/bamboo-service.js:23:43)
    at ObjectCreator.doConstructAsync (/Users/caojun79/project/pubfree/pubfree-server/server/node_modules/@midwayjs/core/dist/definitions/objectCreator.js:75:28)
    at ManagedResolverFactory.createAsync (/Users/caojun79/project/pubfree/pubfree-server/server/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:423:41)
    at MidwayContainer.getAsync (/Users/caojun79/project/pubfree/pubfree-server/server/node_modules/@midwayjs/core/dist/context/applicationContext.js:177:49)
    at MidwayContainer.getAsync (/Users/caojun79/project/pubfree/pubfree-server/server/node_modules/@midwayjs/core/dist/context/midwayContainer.js:475:33)
    at RefResolver.resolveAsync (/Users/caojun79/project/pubfree/pubfree-server/server/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:105:38)

**Comment by czy88840616** [comment]
一般是配置没写对啥的吧，具体查还要提供更详细的场景
