### ISSUE TITLE
使用pm2启动项目时boostrap调用了src目录

### ISSUE THREAD

**Issue by zerogu** [midwayjs/midway#1235]
entrance.config.js
```
const path = require('path')
const projectName = path.basename(__dirname)

const serverConf = {
  name: projectName,
  script: 'bootstrap.js',
  env: {
    APP_MODE: 'server',
  },
  instances: 1,
  exec_mode: 'fork',
  error_file: '/dev/null',
  out_file: '/dev/null',
  cwd: __dirname,
}

module.exports = serverConf

```

bootstrap.js
```
Bootstrap.load(web)
    .before(async (container) => {
      await container.getAsync(RemoteConfig)
    })
    .run()
```

```
Error: Cannot find module './src/remoteConfig'
Require stack:
- /data/app/mlive-node-base/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Module.Hook._require.Module.require (/usr/local/node/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/app/mlive-node-base/bootstrap.js:2:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
    at Module._compile (internal/modules/cjs/loader.js:955:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/data/app/mlive-node-base/bootstrap.js' ]
}
```

求救,如何让他走dist目录呢

**Comment by czy88840616** [comment]
你 RemoteConfig 引的是 src 吧。。

**Comment by zerogu** [comment]
> 你 RemoteConfig 引的是 src 吧。。

啊这.....
大佬秒回,感谢!

**Comment by czy88840616** [comment]
用 https://www.yuque.com/midwayjs/midway_v2/env_config#YvBRV 这个吧，更简单点。

**Comment by zerogu** [comment]
> 用 https://www.yuque.com/midwayjs/midway_v2/env_config#YvBRV 这个吧，更简单点。

求问,这个生命周期是在db启动前还是启动后呢?

**Comment by czy88840616** [comment]
在midway的组件onReady前，orm也是在onReady的时候才去创建连接

**Comment by zerogu** [comment]
> 在midway的组件onReady前，orm也是在onReady的时候才去创建连接

收到!多谢大佬!

**Comment by zerogu** [comment]
> 在midway的组件onReady前，orm也是在onReady的时候才去创建连接

收到!多谢大佬!
