### ISSUE TITLE
读取私钥失败

### ISSUE THREAD

**Issue by CWaiLeung** [midwayjs/midway#1332]
* **Node Version**: v14.16.0
* **Egg Version**: 2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: ubutun20.0
* **Mini Showcase Repository**:

 在src下建一新目录key，里面放privatekey.pem，在util下的文件用fs读取时报错。请问该如何读取？

2021-10-15 16:42:58,312 ERROR 12139 Error [unhandledRejectionError]: ENOENT: no such file or directory, open '../key/privatekey.pem'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at exports.default (/home/lcwai/Public/git/XXX/src/config/config.default.ts:40:20)
    at EggAppWorkerLoader.loadFile (/home/lcwai/Public/git/XXX/node_modules/egg-core/lib/loader/egg_loader.js:304:13)
    at EggAppWorkerLoader._loadConfig (/home/lcwai/Public/git/XXX/node_modules/egg-core/lib/loader/mixin/config.js:83:25)
    at EggAppWorkerLoader._preloadAppConfig (/home/lcwai/Public/git/XXX/node_modules/egg-core/lib/loader/mixin/config.js:68:27)
    at EggAppWorkerLoader.loadConfig (/home/lcwai/Public/git/XXX/node_modules/egg-core/lib/loader/mixin/config.js:26:28)
    at EggAppWorkerLoader.loadConfig (/home/lcwai/Public/git/XXX/node_modules/egg/lib/loader/agent_worker_loader.js:16:11)
    at new EggApplication (/home/lcwai/Public/git/XXX/node_modules/egg/lib/egg.js:54:17)
    at new Agent (/home/lcwai/Public/git/XXX/node_modules/egg/lib/agent.js:22:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '../key/privatekey.pem'
}

**Comment by CWaiLeung** [comment]
谢谢，已解决
