### ISSUE TITLE
模板渲染@midwayjs/view-nunjucks包导入后不能build

### ISSUE THREAD

**Issue by cc4dogman** [midwayjs/midway#1344]
* **Node Version**:v14.15.1
* **Egg Version**:2.31.0

1.使用npm init midway 选择A egg-layer boilerplate for Midway v2 application migration模板
2.按照教程https://www.yuque.com/midwayjs/midway_v2/render增加了Nunjucks
3.添加1个最简单的html做模板，已在 plugint.ts 中关闭 view 和其相关插件
3.vscode调试启动没问题，但执行npm run build时，ts检测报错

```
[Verbose] 849 +1.59s Core Lifecycle after:build:compile 0 
[Verbose] 849 +0.00s Core Lifecycle before:build:emit 0 
[Verbose] 849 +0.00s Core Lifecycle build:emit 1
node_modules/egg-multipart/index.d.ts:61:13 - error TS2320: Interface 'Context<ResponseBodyT>' cannot simultaneously extend types 'ViewBase' and 'Context'.
  Named property 'render' of types 'ViewBase' and 'Context' are not identical.

61   interface Context {
               ~~~~~~~

node_modules/egg-multipart/index.d.ts:61:13 - error TS2320: Interface 'Context<ResponseBodyT>' cannot simultaneously extend types 'ViewBase' and 'Context'.
  Named property 'renderString' of types 'ViewBase' and 'Context' are not identical.

61   interface Context {
               ~~~~~~~

node_modules/egg-multipart/index.d.ts:61:13 - error TS2320: Interface 'Context<ResponseBodyT>' cannot simultaneously extend types 'ViewBase' and 'Context'.
  Named property 'renderView' of types 'ViewBase' and 'Context' are not identical.

61   interface Context {
               ~~~~~~~

[Verbose] 849 +2.56s Core Lifecycle Hook Error Error: TS Error: [object Object](node_modules\egg-multipart\index.d.ts)
    at BuildPlugin.emit (D:\workspace\test\midway-project\node_modules\@midwayjs\cli-plugin-build\src\index.ts:193:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CommandCore.execLiftcycle (D:\workspace\test\midway-project\node_modules\@midwayjs\command-core\src\core.ts:204:11)
    at CommandCore.invoke (D:\workspace\test\midway-project\node_modules\@midwayjs\command-core\src\core.ts:181:5)
    at CLI.start (D:\workspace\test\midway-project\node_modules\@midwayjs\command-core\src\cli.ts:190:5)
```

**Comment by czy88840616** [comment]
应该是egg插件的定义和 midway组件的定义冲突了，由于 egg 内置插件无法去掉，只能关闭 build 检查了。
