### ISSUE TITLE
请问如何拦截bodyParser的报错

### ISSUE THREAD

**Issue by CWaiLeung** [midwayjs/midway#1348]
* **Node Version**: 14.16.0
* **Egg Version**:  2.28.0
* **Plugin Name**: / 
* **Plugin Version**: /
* **Platform**: ubuntu 20.04.3 LTS
* **Mini Showcase Repository**: /

我的config里是这样配置的
  // 覆盖egg自带的配置 使支持接收xml参数
  config.bodyParser = {
    enable: true,
    encoding: "utf8",
    formLimit: "100kb",
    jsonLimit: "100kb",
    strict: false,
    // @see https://github.com/hapijs/qs/blob/master/lib/parse.js#L8 for more options
    queryString: {
      arrayLimit: 100,
      depth: 5,
      parameterLimit: 1000,
    },
    enableTypes: ["json", "form", "text"],
    extendTypes: {
      text: ["text/xml", "application/xml"],
    },
  };

今天要测试入参时不写多了一个字符，报以下错

[ Midway ] 
  SyntaxError: Unexpected token } in JSON at position 218, check bodyParser config
      at JSON.parse (<anonymous>)
      at parse (/home/lcwai/Public/git/configurationCenter/node_modules/co-body/lib/json.js:50:36)
      at AsyncFunction.module.exports [as json] (/home/lcwai/Public/git/configurationCenter/node_modules/co-body/lib/json.js:41:20)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at parseBody (/home/lcwai/Public/git/configurationCenter/node_modules/koa-bodyparser/index.js:100:14)
      at bodyParser (/home/lcwai/Public/git/configurationCenter/node_modules/koa-bodyparser/index.js:85:19)
      at notfound (/home/lcwai/Public/git/configurationCenter/node_modules/egg/app/middleware/notfound.js:5:5)
      at meta (/home/lcwai/Public/git/configurationCenter/node_modules/egg/app/middleware/meta.js:17:5)

2021-10-29 16:23:35,573 WARN 35749 [47ms POST] SyntaxError: Unexpected token } in JSON at position 218, check bodyParser config
    at JSON.parse (<anonymous>)
    at parse (/home/lcwai/Public/git/configurationCenter/node_modules/co-body/lib/json.js:50:36)
    at AsyncFunction.module.exports [as json] (/home/lcwai/Public/git/configurationCenter/node_modules/co-body/lib/json.js:41:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at parseBody (/home/lcwai/Public/git/configurationCenter/node_modules/koa-bodyparser/index.js:100:14)
    at bodyParser (/home/lcwai/Public/git/configurationCenter/node_modules/koa-bodyparser/index.js:85:19)
    at notfound (/home/lcwai/Public/git/configurationCenter/node_modules/egg/app/middleware/notfound.js:5:5)
    at meta (/home/lcwai/Public/git/configurationCenter/node_modules/egg/app/middleware/meta.js:17:5) {
  status: 400,

想拦截到此报错，打断点发现aspect和middleware均无法拦截，请问如何解决？

**Comment by CWaiLeung** [comment]
谢谢，已解决
