### ISSUE TITLE
项目部署到docker，访问swagger ui出现问题

### ISSUE THREAD

**Issue by CWaiLeung** [midwayjs/midway#1407]
* **Node Version**: 14.16.0
* **Egg Version**:  2.28.0
* **Plugin Name**: / 
* **Plugin Version**: /
* **Platform**: ubuntu 20.04.3 LTS
* **Mini Showcase Repository**: /
项目在虚拟机中运行，访问xxx/swagger-ui/index.html能正常显示。

当部署到虚拟机中的docker后，再通过映射的端口访问swagger-ui/index.html时，页面报以下错
`
Cannot destructure property 'getAbsoluteFSPath' of '(0 , core_1.safeRequire)(...)' as it is undefined.
`

日志如下：
`
2021-12-07 12:24:45,064 ERROR 18 [undefined GET 129ms] TypeError: Cannot destructure property 'getAbsoluteFSPath' of '(0 , core_1.safeRequire)(...)' as it is undefined.
    at new SwaggerController (/app/node_modules/@midwayjs/swagger/dist/controller/swagger.js:23:17)
    at ObjectCreator.doConstructAsync (/app/node_modules/@midwayjs/core/dist/definitions/objectCreator.js:75:28)
    at ManagedResolverFactory.createAsync (/app/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:423:41)
    at MidwayRequestContainer.getAsync (/app/node_modules/@midwayjs/core/dist/context/requestContainer.js:83:68)
    at Object.<anonymous> (/app/node_modules/@midwayjs/koa/dist/framework.js:33:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async xframe (/app/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/app/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/app/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)

`

**Comment by czy88840616** [comment]
```


constructor() {
--
23 | const { getAbsoluteFSPath } = (0, core_1.safeRequire)('swagger-ui-dist');
24 | if (getAbsoluteFSPath) {
25 | this.swaggerUiAssetPath = getAbsoluteFSPath();
26 | }
27 | }



```


看上去像是 swagger-ui-dist 这个包没有的样子。

**Comment by CWaiLeung** [comment]
对的，卸载，用npm install swagger-ui-dist --save就ok
