### ISSUE TITLE
[QUESTION]如何启动是执行特定Task

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1412]
背景
```
import { Provide, Task } from '@midwayjs/decorator';


@Provide()
export class FansService {
  @Task({
    repeat: { cron: '0 0/30 * * * *' },
  })
  async syncFans() {
    console.log('10');
  }
}

```
- 我想程序启动的时候就执行一次
```
  async onReady(container: IMidwayContainer) {
    const result = await container.getAsync(QueueService);
    const job = await result.getQueueTask('FansService', 'syncFans');
    console.log(job);
    job.add({}, { delay: 0 });
  }
```
- 但是显示
```
2021-12-08 19:27:41,217 ERROR 7726 Error [unhandledRejectionError]: Invalid characters, got value: undefinedundefinedundefined
    at Function._parseField (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/cron-parser@2.18.0/node_modules/cron-parser/lib/expression.js:187:11)
    at parse (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/cron-parser@2.18.0/node_modules/cron-parser/lib/expression.js:796:36)
    at Function.parse (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/cron-parser@2.18.0/node_modules/cron-parser/lib/expression.js:875:10)
    at Function.parseExpression (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/cron-parser@2.18.0/node_modules/cron-parser/lib/parser.js:41:25)
    at getNextMillis (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/bull@3.29.3/node_modules/bull/lib/repeatable.js:214:29)
    at Queue.nextRepeatableJob (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/bull@3.29.3/node_modules/bull/lib/repeatable.js:38:24)
    at /Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/bull@3.29.3/node_modules/bull/lib/queue.js:702:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-12-08 19:27:41,218 ERROR 7726 Error [unhandledRejectionError]: Invalid characters, got value: undefinedundefinedundefined
    at Function._parseField (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/cron-parser@2.18.0/node_modules/cron-parser/lib/expression.js:187:11)
    at parse (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/cron-parser@2.18.0/node_modules/cron-parser/lib/expression.js:796:36)
    at Function.parse (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/cron-parser@2.18.0/node_modules/cron-parser/lib/expression.js:875:10)
    at Function.parseExpression (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/cron-parser@2.18.0/node_modules/cron-parser/lib/parser.js:41:25)
    at getNextMillis (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/bull@3.29.3/node_modules/bull/lib/repeatable.js:214:29)
    at Queue.nextRepeatableJob (/Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/bull@3.29.3/node_modules/bull/lib/repeatable.js:38:24)
    at /Users/chenshijian/code/act/act-20211123/app/official/service/node_modules/.pnpm/bull@3.29.3/node_modules/bull/lib/queue.js:702:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[ Midway ] Auto reload. [change] configuration.ts
2021-12-08 19:30:00,162 INFO 7726 [Task][repeat:5413f10f820d4ddf14bb8b64d13dbfaf:1638963000000]
```

**Comment by xmsz** [comment]
目前通过 repeat: undefined  可以实现
```
job.add({}, { delay: 0, repeat: undefined });
```

**Comment by czy88840616** [comment]
那直接拿到服务调用方法就好了吧。。不用走定时接口吧。

**Comment by xmsz** [comment]
> 那直接拿到服务调用方法就好了吧。。不用走定时接口吧。

configuration怎么拿服务 可以直接inject服务进来吗

**Comment by czy88840616** [comment]
可。

**Comment by xmsz** [comment]
> 可。

ok

**Comment by xmsz** [comment]
> 可。

有个额外的问题
- 我在onReady注册abc
- bService里用用到abc
- 然后我又想在onReady调用bService
```
 @Inject()
  bService: bService;

async onReady(container: IMidwayContainer) {
    container.registerObject('abc', {});
}
```
- 这是就会出现
```
NotFoundError: abc in class bService in class ContainerLifeCycle is not valid in current context

```

这种情况要怎么处理

**Comment by czy88840616** [comment]
嗯，getAsync出来就行，和inject一样的
