### ISSUE TITLE
[QUESTION]docker里出现'server got error: bind EADDRINUSE null:7001, code: EADDRINUSE'原因可能哪些

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1418]
背景
```
...

# 如果端口更换，这边可以更新一下
EXPOSE 7001

CMD ["npm", "run", "start"]
```
```
"scripts": {
    "start": "egg-scripts start --title=my-midway-project --framework=@midwayjs/web",
  },
```
但是在docker运行居然报了
```
2021-12-10 12:35:05,400 INFO 52 [egg:loader] Controller loaded: /app/dist/app/controller


2021-12-10 12:35:05,402 ERROR 52 [app_worker] server got error: bind EADDRINUSE null:7001, code: EADDRINUSE


2021-12-10 12:35:05,402 INFO 52 [egg:core:ready_stat] end ready task /app/node_modules/.pnpm/@midwayjs+web@2.13.4_@midwayjs+decorator@2.14.0/node_modules/@midwayjs/web/app.js:didLoad, remain []


2021-12-10 12:35:05,403 INFO 52 [egg-security] use csrf middleware

2021-12-10 12:35:05,403 INFO 52 [egg-security] use methodnoallow middleware


2021-12-10 12:35:05,404 INFO 52 [egg-security] use noopen middleware

2021-12-10 12:35:05,404 INFO 52 [egg-security] use nosniff middleware

2021-12-10 12:35:05,404 INFO 52 [egg-security] use xssProtection middleware

2021-12-10 12:35:05,404 INFO 52 [egg-security] use xframe middleware


2021-12-10 12:35:05,404 INFO 52 [egg-security] use dta middleware


2021-12-10 12:35:05,404 INFO 52 [egg-security] compose 7 middlewares into one security middleware


2021-12-10 12:35:05,406 INFO 52 [app_worker] receive signal SIGTERM, exiting with code:0


2021-12-10 12:35:05,408 INFO 52 [midway:bootstrap] receive signal SIGTERM, closing


2021-12-10 12:35:05,422 INFO 52 [app_worker] beforeExit success

2021-12-10 12:35:05,422 INFO 52 [app_worker] exit with code:0


2021-12-10 12:35:05,422 INFO 52 [midway:bootstrap] exit with code:0

[2021-12-10 12:35:05.434] [cfork:master:34] worker:52 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)

[2021-12-10 12:35:05.435] [cfork:master:34] don't fork, because worker:52 will be kill soon


2021-12-10 12:35:05,436 INFO 34 [master] app_worker#1:52 disconnect, suicide: false, state: disconnected, current workers: ["1"]


[2021-12-10 12:35:05.438] [cfork:master:34] worker:52 exit (code: 0, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)


2021-12-10 12:35:05,441 ERROR 34 nodejs.AppWorkerDiedError: [master] app_worker#1:52 died (code: 0, signal: null, suicide: false, state: dead), current workers: []

at Master.onAppExit (/app/node_modules/.pnpm/egg-cluster@1.27.1/node_modules/egg-cluster/lib/master.js:511:21)

at Master.emit (events.js:314:20)

at Messenger.sendToMaster (/app/node_modules/.pnpm/egg-cluster@1.27.1/node_modules/egg-cluster/lib/utils/messenger.js:137:17)

at Messenger.send (/app/node_modules/.pnpm/egg-cluster@1.27.1/node_modules/egg-cluster/lib/utils/messenger.js:102:12)

at EventEmitter.<anonymous> (/app/node_modules/.pnpm/egg-cluster@1.27.1/node_modules/egg-cluster/lib/master.js:354:22)

at EventEmitter.emit (events.js:326:22)

at ChildProcess.<anonymous> (internal/cluster/master.js:191:13)

at Object.onceWrapper (events.js:421:26)


at ChildProcess.emit (events.js:314:20)

at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)

name: "AppWorkerDiedError"

pid: 34

hostname: c353260abdf9



2021-12-10 12:35:05,442 ERROR 34 [master] app_worker#1:52 start fail, exiting with code:1


2021-12-10 12:35:05,444 ERROR 34 [master] exit with code:1


2021-12-10 12:35:05,455 ERROR 41 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110


2021-12-10 12:35:05,459 INFO 41 [agent_worker] beforeExit success

2021-12-10 12:35:05,460 ERROR 41 [agent_worker] exit with code:110


2021-12-10 12:35:05,460 INFO 41 [midway:bootstrap] exit with code:110


npm ERR! code ELIFECYCLE

npm ERR! errno 1


npm ERR! my-midway-project@1.0.0 start: `egg-scripts start --title=my-midway-project --framework=@midwayjs/web --workers=1`

npm ERR! Exit status 1


npm ERR!

npm ERR! Failed at the my-midway-project@1.0.0 start script.


npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:


npm ERR! /root/.npm/_logs/2021-12-10T04_35_05_485Z-debug.log


```

大家有没有遇到这种情况，是不是我哪个地方搞错了

**Comment by xmsz** [comment]
暂时找不到原因 不过应该是代码的问题导致 一直重启 先关闭了

**Comment by xmsz** [comment]
然后千万记得不要设置rootDir:"."
这样的话就一定会报上面的错误 但不会有提示
