### ISSUE TITLE
windows 机器部署 serverless aliyunFC 报错：Error: Cannot find module '@midwayjs/bootstrap'

### ISSUE THREAD

**Issue by zhanyeye** [midwayjs/midway#1435]
* **Node Version**: Node.js 12.x
* **Plugin Version**:
```
    "@midwayjs/core": "^2.3.0",
    "@midwayjs/decorator": "^2.3.0",
    "@midwayjs/faas": "^2.0.0",
```
+ **OS: windows**

```diff
! 回来补充：Linux 机器部署正常，windows 部署出了问题
```

### 报错信息
```
{
   "errorMessage":"Error: Cannot find module '@midwayjs/bootstrap'\nRequire stack:\n- /code/helloHttpService.js\n- /var/fc/runtime/nodejs12/prepare_code.js\n- /var/fc/runtime/nodejs12/invoke.js\n- /var/fc/runtime/nodejs12/bootstrap.js",
   "errorType":"FunctionUnhandledError: ImportModuleError",
   "stackTrace":[
      "ImportModuleError: Error: Cannot find module '@midwayjs/bootstrap'",
      "Require stack:",
      "- /code/helloHttpService.js",
      "- /var/fc/runtime/nodejs12/prepare_code.js",
      "- /var/fc/runtime/nodejs12/invoke.js",
      "- /var/fc/runtime/nodejs12/bootstrap.js",
      "    at exports (/var/fc/runtime/nodejs12/invoke.js:47:19)",
      "    at InvocationHandler.handleInvocation (/var/fc/runtime/nodejs12/bootstrap.js:128:22)"
   ]
}
```

### 阿里云测试函数日志：
```
FC Initialize Start RequestId: 9e90ebb5-96b4-4d08-aae9-cd986f3d9b5e
load code for handler:helloHttpService.initializer
2021-12-23T02:55:19.281Z 9e90ebb5-96b4-4d08-aae9-cd986f3d9b5e [verbose] load function throw: Error: Cannot find module '@midwayjs/bootstrap'
Require stack:
- /code/helloHttpService.js
- /var/fc/runtime/nodejs12/prepare_code.js
- /var/fc/runtime/nodejs12/invoke.js
- /var/fc/runtime/nodejs12/bootstrap.js
FC Initialize End RequestId: 9e90ebb5-96b4-4d08-aae9-cd986f3d9b5e, Error: Handled function error
2021-12-23T02:55:19.282Z 9e90ebb5-96b4-4d08-aae9-cd986f3d9b5e [error] {"errorMessage":"Error: Cannot find module '@midwayjs/bootstrap'\nRequire stack:\n- /code/helloHttpService.js\n- /var/fc/runtime/nodejs12/prepare_code.js\n- /var/fc/runtime/nodejs12/invoke.js\n- /var/fc/runtime/nodejs12/bootstrap.js","errorType":"FunctionUnhandledError: ImportModuleError","stackTrace":["ImportModuleError: Error: Cannot find module '@midwayjs/bootstrap'","Require stack:","- /code/helloHttpService.js","- /var/fc/runtime/nodejs12/prepare_code.js","- /var/fc/runtime/nodejs12/invoke.js","- /var/fc/runtime/nodejs12/bootstrap.js","    at exports (/var/fc/runtime/nodejs12/invoke.js:47:19)","    at InvocationHandler.handleInvocation (/var/fc/runtime/nodejs12/bootstrap.js:128:22)"]}
```

### 本地执行部署命令输出：
![image](https://user-images.githubusercontent.com/35565811/147182015-670795db-cd75-4026-82c6-3f77fa8b8eaf.png)

### pacakge.json 文件
```
{
  "name": "midway_faas_project",
  "private": true,
  "version": "1.0.0",
  "description": "Midway Serverless for the Serverless environment",
  "main": "index.js",
  "license": "MIT",
  "keywords": [
    "serverless",
    "midway"
  ],
  "scripts": {
    "dev": "cross-env NODE_ENV=local midway-bin dev --ts",
    "test": "cross-env midway-bin test --ts",
    "deploy": "cross-env UDEV_NODE_ENV=production midway-bin deploy",
    "lint": "mwts check",
    "lint:fix": "mwts fix"
  },
  "dependencies": {
    "@midwayjs/bootstrap": "^2.14.0",
    "@midwayjs/core": "^2.3.0",
    "@midwayjs/decorator": "^2.3.0",
    "@midwayjs/faas": "^2.0.0",
    "axios": "^0.21.1",
    "chartist-alpha": "^1.0.1",
    "dotenv": "^10.0.0"
  },
  "devDependencies": {
    "@midwayjs/cli": "^1.2.45",
    "@midwayjs/cli-plugin-faas": "^1.2.45",
    "@midwayjs/mock": "^2.8.7",
    "@midwayjs/serverless-app": "^2.8.7",
    "@midwayjs/serverless-fc-trigger": "^2.10.3",
    "@midwayjs/serverless-scf-trigger": "^2.10.3",
    "@types/jest": "^26.0.10",
    "@types/node": "14",
    "cross-env": "^6.0.0",
    "jest": "^26.4.0",
    "mwts": "^1.0.5",
    "ts-jest": "^26.2.0",
    "typescript": "^4.0.0"
  }
}

```

**Comment by zhanyeye** [comment]
尝试了一下，执行  `npm init midway` 生成的demo项目部署后，也会报这个错

**Comment by czy88840616** [comment]
感觉像是安装环境的问题

- 1、检查服务器上，node_modeuls 目录下该包是否存在，是否是软链
- 2、检查本地发布后 .serverless目录中是否存在该依赖

**Comment by zhanyeye** [comment]
1. 服务器上node_modeuls 目录下确实不存在该包，本地 .serverless目录中是有的
2. 服务器运行环境执行 npm install 后出现：
```diff
npm ERR! code ENOENT
npm ERR! syscall access
npm ERR! path /home/admin/workspace/functions/c52f65eb-b68e-4109-9662-e8928c5f9207/node_modules/@midwayjs/bootstrap
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, access '/home/admin/workspace/functions/c52f65eb-b68e-4109-9662-e8928c5f9207/node_modules/@midwayjs/bootstrap'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-23T05_17_13_542Z-debug.log
```

**Comment by czy88840616** [comment]
把 @midwayjs/bootstrap放到依赖里？（这个理论上是打包自动装的）

**Comment by zhanyeye** [comment]
有添加der~，是我少配置了什么嘛🤣
pacakge.json 中的 dependencies：
```
 "dependencies": {
    "@midwayjs/bootstrap": "^2.14.0",
    "@midwayjs/core": "^2.3.0",
    "@midwayjs/decorator": "^2.3.0",
    "@midwayjs/faas": "^2.0.0",
    "axios": "^0.21.1",
    "dotenv": "^10.0.0"
  },
```
**函数计算FC**环境上的node_modules目录
![image](https://user-images.githubusercontent.com/35565811/147194461-7d19fda1-7b00-4613-bc11-22b9c66d0c3d.png)

错误截图：
![image](https://user-images.githubusercontent.com/35565811/147194890-0dfa79ac-8c20-4be7-9a01-30b766894f40.png)

**Comment by zhanyeye** [comment]
发现在 Linux 机器上执行 npm run deploy 服务是正常的，在 windows 机器上就出现了问题。

**Comment by czy88840616** [comment]
我猜是因为软链文件的路径问题。你可以打开部署的node_modules里的软链看看。

**Comment by xmsz** [comment]
我也遇到差不多的
```
{
errorMessage: "Error: Cannot find module '@midwayjs/serverless-fc-starter' Require stack: - /code/index.js - /var/fc/runtime/nodejs12/prepare_code.js - /var/fc/runtime/nodejs12/invoke.js - /var/fc/runtime/nodejs12/bootstrap.js",
errorType: "FunctionUnhandledError: ImportModuleError",
stackTrace: [
"ImportModuleError: Error: Cannot find module '@midwayjs/serverless-fc-starter'",
"Require stack:",
"- /code/index.js",
"- /var/fc/runtime/nodejs12/prepare_code.js",
"- /var/fc/runtime/nodejs12/invoke.js",
"- /var/fc/runtime/nodejs12/bootstrap.js",
" at exports (/var/fc/runtime/nodejs12/invoke.js:47:19)",
" at InvocationHandler.handleInvocation (/var/fc/runtime/nodejs12/bootstrap.js:128:22)"
]
}
```
mac部署没什么问题 但是windows就出现这个...

**Comment by czy88840616** [comment]
在 midway-bin deploy 的时候加上 --npmClient=npm 试试？

**Comment by xmsz** [comment]
> 
就会出现
```
Install layers...
 - npm install err Command failed: npm i @midwayjs/egg-layer --production
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: ts-jest@27.1.2
npm ERR! Found: @types/jest@26.0.24
npm ERR! node_modules/@types/jest
npm ERR!   dev @types/jest@"^26.0.24" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @types/jest@"^27.0.0" from ts-jest@27.1.2
npm ERR! node_modules/ts-jest
npm ERR!   dev ts-jest@"^27.0.4" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @types/jest@27.0.3
npm ERR! node_modules/@types/jest
npm ERR!   peerOptional @types/jest@"^27.0.0" from ts-jest@27.1.2
npm ERR!   node_modules/ts-jest
npm ERR!     dev ts-jest@"^27.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2021-12-25T05_47_48_160Z-debug.log
```

**Comment by xmsz** [comment]
然后我尝试在阿里云上安装依赖`npm i --no-bin-links，依赖不报错了，但是报了另外的
```
FC Invoke Start RequestId: 784a0197-56b6-4d18-a215-823e8b863b23
2021-12-25T06:01:53.579Z 784a0197-56b6-4d18-a215-823e8b863b23 [error] Error: handler not found: index.handler, please check your f.yml
    at defaultInvokeHandler (/code/node_modules/@midwayjs/runtime-engine/dist/runtime.js:186:15)
    at (/code/node_modules/@midwayjs/serverless-fc-starter/dist/runtime.js:83:37)
    at invokeHandlerWrapper (/code/node_modules/@midwayjs/runtime-engine/dist/lightRuntime.js:19:34)
FC Invoke End RequestId: 784a0197-56b6-4d18-a215-823e8b863b23

```

```
service: ele-bonus-server

provider:
  name: aliyun
  timeout: 60
  initTimeout: 60
  environment:
    TZ: Asia/Shanghai

deployType: egg




```

**Comment by czy88840616** [comment]
lock文件删了么

**Comment by xmsz** [comment]
> lock文件删了么

没有lock文件

**Comment by czy88840616** [comment]
看着像是npm7的问题，你是npm7么
