### ISSUE TITLE
FaaS部署后发http请求报错please set config.keys first

### ISSUE THREAD

**Issue by liaozhonghui** [midwayjs/midway#1436]
### 问题描述：

本地跑没问题，使用npm run deploy部署到FC上，http请求报错please set config.keys first，请问哪地方还需要配置吗😃？
配置文件只有一个config.default.ts, 按照egg的配置文件格式写的.
> 看Egg.js的issue里面说这个问题需要tsc compile。 但是我看本地.serverless文件里面有编译完成的dist里是正常的

### 报错信息：

```console

2021-12-23 15:12:04,634 ERROR 6 [-/210.12.182.18/-/13ms POST /message/21100] nodejs.Error: Please set config.keys first
    at get keys (/code/node_modules/egg/lib/application.js:266:15)
    at get cookies (/code/node_modules/egg/app/extend/context.js:23:66)
    at get [egg-security#CSRF_SECRET] (/code/node_modules/egg-security/app/extend/context.js:91:35)
    at ensureCsrfSecret (/code/node_modules/egg-security/app/extend/context.js:104:13)
    at csrf (/code/node_modules/egg-security/lib/middlewares/csrf.js:15:11)
    at dispatch (/code/node_modules/koa-compose/index.js:42:32)
    at (/code/node_modules/koa-compose/index.js:34:12)
    at dispatch (/code/node_modules/koa-compose/index.js:42:32)
    at session (/code/node_modules/koa-session/index.js:41:13)
    at dispatch (/code/node_modules/koa-compose/index.js:42:32)
```

config.default.ts配置
![image](https://user-images.githubusercontent.com/20548333/147204288-920c00bf-bbb5-4b56-b7d7-724b6a504310.png)

package.json的脚本配置：
```js
 "scripts": {
    "dev": "cross-env NODE_ENV=local midway-bin dev --ts",
    "test": "cross-env midway-bin test --ts",
    "deploy": "cross-env UDEV_NODE_ENV=prod midway-bin deploy",
    "lint": "mwts check",
    "lint:fix": "mwts fix"
  },
  "dependencies": {
    "@koa/cors": "^3.1.0",
    "@midwayjs/core": "^2.3.0",
    "@midwayjs/decorator": "^2.3.0",
    "@midwayjs/faas": "^2.0.0",
    "@midwayjs/fcli-plugin-fc": "^1.2.92",
    "@midwayjs/jwt": "^2.14.0",
    "@midwayjs/orm": "^2.14.0",
    "egg": "^2.33.1",
    "joi": "^17.5.0",
    "lodash": "^4.17.21",
    "pg": "^8.7.1",
    "typeorm": "^0.2.41"
  },
```

**Comment by czy88840616** [comment]
应用上serverless 请参考 https://midwayjs.org/docs/migrate_egg

**Comment by liaozhonghui** [comment]
@czy88840616 是文档上这个部分吗？
但是这个tsc得scripts对应的是啥，没找到😭
![image](https://user-images.githubusercontent.com/20548333/147207528-0f42d7f9-73b9-4556-b05a-7a34eeb81114.png)

**Comment by czy88840616** [comment]
构建的脚本命令，比如 npm run build...

**Comment by liaozhonghui** [comment]
build脚本我也没找到，用`midway-bin build`这个可以吧

**Comment by echosoar** [comment]
上面的配置只有使用了 egg-ts 才需要配置，其他情况不需要配置

**Comment by czy88840616** [comment]
就是 package.json 的 scrips ...，build是 midway 默认写的。

**Comment by liaozhonghui** [comment]
我用的faas那个脚手架，`$ npm init midway --type=faas my_midway_app` 里面没有😢

**Comment by czy88840616** [comment]
faas 和应用迁移是两个不同的东西，如果要用应用上 serverless 环境，应该创建标准应用。

**Comment by liaozhonghui** [comment]
ok了，已解决，我把egg相关的都删除了再部署FaaS就好了，以后有机会再试试标准应用😃 0.0
