### ISSUE TITLE
项目无法编译通过，导致无法Docker部署

### ISSUE THREAD

**Issue by ddzyan** [midwayjs/midway#1458]
项目中使用了 `prisma`作为orm来使用，现在运行 `npm run build` ，无法编译通过，报错内容暂时也看不出是否因为 prisma 引起，希望帮忙看看

仓库地址：https://github.com/ddzyan/midway-prisma.git

错误信息：
```shell
> midway-prisma@1.0.0 build
> midway-bin build -c

   - Copy prisma/schema.prisma
   - Copy Complete
node_modules/@waiting/shared-types/dist/lib/template-literal.d.ts:5:111 - error TS2322: Type 'T[0]' is not assignable to type 'string | number | bigint | boolean'.
  Type 'unknown' is not assignable to type 'string | number | bigint | boolean'.
    Type 'unknown' is not assignable to type 'true'.
      Type 'T[0]' is not assignable to type 'bigint'.
        Type 'unknown' is not assignable to type 'bigint'.

5 export declare type TupleJoin<T extends V[], D extends string> = T extends [] ? '' : T extends [unknown] ? `${T[0]}` : T extends [unknown, ...infer U] ? `${T[0]}${D}${TupleJoin<U, D>}` : string;
                                                                                                                ~~~~

node_modules/@waiting/shared-types/dist/lib/template-literal.d.ts:5:178 - error TS2344: Type 'U' does not satisfy the constraint 'V[]'.
  Type 'unknown[]' is not assignable to type 'V[]'.
    Type 'unknown' is not assignable to type 'V'.
      Type 'unknown' is not assignable to type 'true'.

5 export declare type TupleJoin<T extends V[], D extends string> = T extends [] ? '' : T extends [unknown] ? `${T[0]}` : T extends [unknown, ...infer U] ? `${T[0]}${D}${TupleJoin<U, D>}` : string;
                                                                                                                                                                                   ~

node_modules/@waiting/shared-types/dist/lib/tuple.d.ts:17:21 - error TS2536: Type 'P' cannot be used to index type 'S'.

17     [P in keyof T]: S[P];
                       ~~~~





Error! You can try adding the -V parameter for more information output.




Error: TS Error: [object Object](node_modules/@waiting/shared-types/dist/lib/template-literal.d.ts)
    at BuildPlugin.emit (/Users/didi/Documents/work-space/temp/midway-prisma/node_modules/@midwayjs/cli-plugin-build/src/index.ts:209:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CommandCore.execLiftcycle (/Users/didi/Documents/work-space/temp/midway-prisma/node_modules/@midwayjs/command-core/src/core.ts:208:11)
    at CommandCore.invoke (/Users/didi/Documents/work-space/temp/midway-prisma/node_modules/@midwayjs/command-core/src/core.ts:181:5)
    at CLI.start (/Users/didi/Documents/work-space/temp/midway-prisma/node_modules/@midwayjs/command-core/src/cli.ts:192:5)
```

**Comment by czy88840616** [comment]
字符串模板，ts版本太低的缘故吧。

**Comment by ddzyan** [comment]
> 字符串模板，ts版本太低的缘故吧。

我本地的项目下安装和全局安装的ts模块，我看了下版本已经是4.5.4最新版本，还有啥其他可能的原因吗

**Comment by czy88840616** [comment]
还有个可能是。。这个依赖包的定义没写对。。skipLibCheck 呗。

**Comment by waitingsong** [comment]
编辑 tsconfig.json
```json
{
  "compilerOptions": {
    ...
   ...
    "skipLibCheck": true

  }
} 
```

**Comment by waitingsong** [comment]
> 还有个可能是。。这个依赖包的定义没写对。。skipLibCheck 呗。

那个类型是用于 交叉、联合类型的相互转换，在老版本 ts 下面工作正常，ts 4.3 以后更加严格就会过不了。
skipLibCheck 可解决
