### ISSUE TITLE
[QUESTION]一体化项目pnpm i无法运行

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1568]
背景
```
 pnpm i --shamefully-hoist
```
运行dev
```
[ Midway ] start error: Cannot read property 'namespace' of undefined
TypeError: Cannot read property 'namespace' of undefined
    at ContainerConfiguration.loadComponentObject (node_modules/.pnpm/@midwayjs+core@2.14.0/node_modules/@midwayjs/core/dist/context/configuration.js:174:41)
    at ContainerConfiguration.addImports (node_modules/.pnpm/@midwayjs+core@2.14.0/node_modules/@midwayjs/core/dist/context/configuration.js:42:43)
    at ContainerConfiguration.loadConfiguration (node_modules/.pnpm/@midwayjs+core@2.14.0/node_modules/@midwayjs/core/dist/context/configuration.js:229:26)
    at ContainerConfiguration.load (node_modules/.pnpm/@midwayjs+core@2.14.0/node_modules/@midwayjs/core/dist/context/configuration.js:157:14)
    at MidwayContainer.load (node_modules/.pnpm/@midwayjs+core@2.14.0/node_modules/@midwayjs/core/dist/context/midwayContainer.js:85:23)
    at ConfigFramework.containerDirectoryLoad (node_modules/.pnpm/@midwayjs+core@2.14.0/node_modules/@midwayjs/core/dist/baseFramework.js:137:33)
    at ConfigFramework.initialize (node_modules/.pnpm/@midwayjs+core@2.14.0/node_modules/@midwayjs/core/dist/baseFramework.js:53:20)
    at BootstrapStarter.init (node_modules/.pnpm/@midwayjs+bootstrap@2.14.0/node_modules/@midwayjs/bootstrap/dist/bootstrap.js:36:9)
    at create (node_modules/.pnpm/@midwayjs+mock@2.14.0/node_modules/@midwayjs/mock/dist/utils.js:161:5)
    at createApp (node_modules/.pnpm/@midwayjs+mock@2.14.0/node_modules/@midwayjs/mock/dist/utils.js:168:23)
```

**Comment by Lxxyx** [comment]
![image](https://user-images.githubusercontent.com/13161470/149446679-608c5d7c-88f9-4d7e-aedf-eea024198ad4.png)
初步判定是因为 pnpm 目录结构问题

**Comment by songjiachao** [comment]
也报这个错误了，估计是一个问题

![image](https://user-images.githubusercontent.com/70792885/149760223-fe03780d-223a-447e-8c2f-cf360a39035b.png)

**Comment by Lxxyx** [comment]
优先使用 yarn 吧，pnpm 目录结构我得先排查一会儿

**Comment by songjiachao** [comment]
怎么样了？

**Comment by Lxxyx** [comment]
@echosoar
