### ISSUE TITLE
自定义错误文本报错

### ISSUE THREAD

**Issue by Ttou** [midwayjs/midway#1627]
* **Node Version**:v16.13.1
* **Midway Version(Decorator/Core)**:3.0.2
* **Component Name/Version**:@midwayjs/validate@3.0.2
* **Platform**:windows11
* **Mini Showcase Repository**:

根据 3.0 文档的自定义错误文本的写法，启动应用就会报错。

```ts
import { Rule, RuleType } from '@midwayjs/validate';

export class SetUserDto {
  @Rule(RuleType.string().required().message('不能为空'))
  username: string;
}
```

```
[ Midway ] start error: Cannot apply rules to empty ruleset or the last rule added does not support rule properties

Error: Cannot apply rules to empty ruleset or the last rule added does not support rule properties
    at new module.exports (D:\projects\midway-template\node_modules\@hapi\hoek\lib\error.js:23:19)
    at module.exports (D:\projects\midway-template\node_modules\@hapi\hoek\lib\assert.js:20:11)
    at internals.Base.rule (D:\projects\midway-template\node_modules\joi\lib\base.js:479:9)
    at internals.Base.method [as message] (D:\projects\midway-template\node_modules\joi\lib\extend.js:145:29)
    at Object.<anonymous> (D:\projects\midway-template\src\dto\user.dto.ts:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (D:\projects\midway-template\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)     
    at Object.require.extensions.<computed> [as .ts] (D:\projects\midway-template\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

**Comment by czy88840616** [comment]
我研究了一下，好像是因为 required的关系

**Comment by czy88840616** [comment]
调整下吧，使用 `@Rule(RuleType.string().required().error(new Error('不能为空')))`

**Comment by Ttou** [comment]
这样写可以

**Comment by waitingsong** [comment]
> .error(new Error('不能为空'))

`.error(new Error('不能为空'))` 感觉有点繁琐，能不能扩展下 `.throwError('不能为空')` 就舒坦了～～

**Comment by czy88840616** [comment]
单纯的对单条指定报错概率不高吧，一般都是对特定的规则做文案，比如 string.max/string.min 啥的提示 xxx 过长/过短，单独对某个属性报错，前端也不知道是因为哪个规则，属于偷懒了。
