### ISSUE TITLE
delegateTargetPrototypeMethod的对象如果有init方法要怎么处理

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1697]
背景
```
class Book {
  init() {
    console.log('book init');
  }
}
delegateTargetPrototypeMethod(CloudbaseService, [Book]);
```
会报错
```
2022-02-13 12:53:41,369 ERROR 43928 [-/::ffff:127.0.0.1/-/13ms POST /api/manage/data] TypeError: Cannot read property 'init' of undefined
    at CloudbaseService.derivedCtor.<computed> (/node_modules/.pnpm/@midwayjs+core@3.0.4_@midwayjs+decorator@3.0.4/node_modules/@midwayjs/core/dist/util/index.js:122:41)
    at ObjectCreator.doInitAsync (/node_modules/.pnpm/@midwayjs+core@3.0.4_@midwayjs+decorator@3.0.4/node_modules/@midwayjs/core/dist/definitions/objectCreator.js:120:28)
    at ManagedResolverFactory.createAsync (/node_modules/.pnpm/@midwayjs+core@3.0.4_@midwayjs+decorator@3.0.4/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:228:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ManagedResolverFactory.createAsync (/node_modules/.pnpm/@midwayjs+core@3.0.4_@midwayjs+decorator@3.0.4/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:208:33)
    at ManagedResolverFactory.createAsync (/node_modules/.pnpm/@midwayjs+core@3.0.4_@midwayjs+decorator@3.0.4/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:208:33)
    at /node_modules/.pnpm/@midwayjs+core@3.0.4_@midwayjs+decorator@3.0.4/node_modules/@midwayjs/core/dist/common/webGenerator.js:25:32
    at /node_modules/.pnpm/@midwayjs+info@3.0.5/node_modules/@midwayjs/info/dist/middleware/info.middleware.js:35:24
    at /node_modules/.pnpm/@midwayjs+i18n@3.0.5/node_modules/@midwayjs/i18n/dist/middleware.js:128:17
    at bodyParser (/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)
```

**Comment by czy88840616** [comment]
给个具体的示例？

**Comment by xmsz** [comment]
> 给个具体的示例？

```
npm init midway
componentv3

```
```
// book.service.ts

import { Init, Provide } from '@midwayjs/decorator';
import { delegateTargetPrototypeMethod } from '@midwayjs/core';

class Book {
  init() {
    console.log('book init');
  }
}

@Provide()
export class BookService implements Book {
  @Init()
  async init() {
    console.log('bookService init');
  }

  async getBookById() {
    return 'hello world';
  }
}

delegateTargetPrototypeMethod(BookService, [Book]);


```
```
npm run test
```


这样就能复现了

**Comment by czy88840616** [comment]
可以把@init 装饰的方法换一个名字。。

```ts
@Provide()
export class BookService implements Book {
  @Init()
  async _init() {
    console.log('bookService init');
  }

  async getBookById() {
    return 'hello world';
  }
}
```

**Comment by xmsz** [comment]
> 可以把@init 装饰的方法换一个名字。。
> 
> ```ts
> @Provide()
> export class BookService implements Book {
>   @Init()
>   async _init() {
>     console.log('bookService init');
>   }
> 
>   async getBookById() {
>     return 'hello world';
>   }
> }
> ```

ok 可行
