### ISSUE TITLE
最新的midway3.0.10版本fass demo发布到阿里云fc报错

### ISSUE THREAD

**Issue by cc4dogman** [midwayjs/midway#1747]
* **Node Version**:
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

阿里云FC环境如下
Node Version:12
Midway:3.0.10

自带demo中目前遇到2个问题

1.运行依赖包
"@midwayjs/serverless-fc-starter": "^3.0.2",
这个依赖放到了开发包导致启动函数报
{
    "errorMessage": "Cannot find module '@midwayjs/serverless-fc-starter'\nRequire stack:\n- /code/cardHttpService.js\n- /var/fc/runtime/nodejs12/prepare_code.js\n- /var/fc/runtime/nodejs12/invoke.js\n- /var/fc/runtime/nodejs12/bootstrap.js",
    "errorType": "FunctionUnhandledError: ImportModuleError",
    "stackTrace": [
        "Error: Cannot find module '@midwayjs/serverless-fc-starter'",
        "Require stack:",
        "- /code/cardHttpService.js",
        "- /var/fc/runtime/nodejs12/prepare_code.js",
        "- /var/fc/runtime/nodejs12/invoke.js",
        "- /var/fc/runtime/nodejs12/bootstrap.js",
        "    at Module._resolveFilename (internal/modules/cjs/loader.js:815:15)",
        "    at Module._load (internal/modules/cjs/loader.js:667:27)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at (/code/cardHttpService.js:3:33)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)"
    ]
}

2.如果使用阿里云自带的https访问后日志报错
2022-02-25T02:54:17.400Z a9a5983b-318d-4786-8077-e231c0a42e6d [error] Error: Cannot send secure cookie over unencrypted connection
    at set (/code/node_modules/@midwayjs/cookies/dist/cookies.js:91:19)
    at (/code/node_modules/@midwayjs/i18n/dist/middleware.js:140:33)
    at (/code/node_modules/@midwayjs/core/dist/baseFramework.js:208:36)
    at (/code/node_modules/@midwayjs/faas/dist/framework.js:125:20)
    at invokeHandlerWrapper (/code/node_modules/@midwayjs/runtime-engine/dist/lightRuntime.js:19:28)
FC Invoke End RequestId: a9a5983b-318d-4786-8077-e231c0a42e6d

代码中只返回一个"ok" 字符串,换成http协议后就可以了

**Comment by echosoar** [comment]
我排查下

**Comment by bravehot** [comment]
同样遇到了 第一个 问题，最后发现是 `node` 版本的问题，`f.yml`指定的 `node` 版本是 12，本地 `node` 的版本是 14。
本地把 `node` 切到了 `v12.22.10`，删了` node_modules` 后再 `deploy` 发现可以了

**Comment by czy88840616** [comment]
这跟node版本还有关系么-。-

**Comment by bravehot** [comment]
啊，这。。。，发现我这边是这样的。
刚刚又试了下本地切到 `v14.15.3 (npm v8.5.0)`后，重新 `install` 再 `npm run deploy` 访问又报`Cannot find module '@midwayjs/serverless-fc-starter` 这个错误了。但本地用 `v12.22.10 (npm v6.14.16)` 发现没啥问题。f.yml runtime 指定的是 nodejs12

**Comment by czy88840616** [comment]
- 1、如果全局安装了 @midwayjs/cli，把全局的删掉，用项目里的
- 2、如果有 package-lock，务必删掉

**Comment by zdhxiong** [comment]
@czy88840616 我从 midway v2 升级到 v3，也遇到了第二个问题。阿里云函数计算 node14 环境，使用 http 正常，https 时会报错：
![image](https://user-images.githubusercontent.com/3030330/158030496-d3ad6b76-720a-44af-b4f7-8ffe2ff7b8d4.png)

**Comment by czy88840616** [comment]
基本查明，是判断协议的问题，由于函数的req是假的，req.socket无法判断真实的协议，导致 https 下，使用了 http 逻辑。
