### ISSUE TITLE
midway-bin 发布时会在package.json里自动加上"@midwayjs/bootstrap": "*"导致部署后出错

### ISSUE THREAD

**Issue by andantei** [midwayjs/midway#1771]
* **Node Version**: 14.15.1
* **Midway Version(Decorator/Core)**: 2.13.2
* **Component Name/Version**: midway-bin
* **Platform**: Mac/Linux
* **Mini Showcase Repository**: 

项目采用的是midwayjs 2.13.*,发布时发现midway-bin会自动在dist的package.json里面自动加入以下dependency：
```
    "@midwayjs/serverless-fc-starter": "*",
    "@midwayjs/bootstrap": "*",
    "path-to-regexp": "*",
```
这样部署之后会导致以上package被安装成3.*版本，与项目2.*版本代码不兼容，导致以下错误：
```
{
    "errorMessage": "boot.configure(...).load is not a function",
    "errorType": "TypeError",
    "stackTrace": [
        "at beforeFunctionStart (/code/all.js:36:12)",
        "at handlerInvokerWrapper (/code/node_modules/@midwayjs/runtime-engine/dist/runtime.js:169:31)",
        "at functionStart (/code/node_modules/@midwayjs/runtime-engine/dist/runtime.js:42:20)",
        "at ready (/code/node_modules/@midwayjs/runtime-engine/dist/engine.js:57:40)",
        "at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "at start (/code/node_modules/@midwayjs/runtime-engine/dist/bootstrap.js:22:9)",
        "at start (/code/node_modules/@midwayjs/serverless-fc-starter/dist/index.js:33:5)",
        "at initializeMethod (/code/all.js:43:13)",
        "at (/code/all.js:615:5)"
    ]
}
```

**Comment by czy88840616** [comment]
用项目中的midway-bin命令，全局的cli估计很久没更新了吧。
