### ISSUE TITLE
"[winston] Attempt to write logs with no transports" printed even when test is passed 

### ISSUE THREAD

**Issue by coderup2021** [midwayjs/midway#1862]
every time I exec test cmd, it will print the same error like follow picture even if the test is passed.

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/93026018/160263560-3ca22202-f1c4-4448-a64f-f7658305c5fe.png">

```
lj@linjiangdeMacBook-Pro firefly_api_server % npx midway-bin test -f test/service/excelService.test.ts
Testing test/service/excelService.test.ts
2022-03-27 10:02:30,681 INFO 45482 [egg:logger] init all loggers with options: {"clients":{"appLogger":{"fileLogName":"midway-web.log","aliasName":"logger"},"agentLogger":{"fileLogName":"midway-agent.log"},"coreLogger":{"fileLogName":"midway-core.log"}},"default":{"dir":"/var/log/fireflyAPIServer","maxSize":"100m","maxFiles":"30d","level":"info","consoleLevel":"info","auditFileDir":".audit"}}
2022-03-27 10:02:30,683 INFO 45482 [egg:core] dump config after load, 9ms
2022-03-27 10:02:30,778 INFO 45482 [egg:core] dump config after ready, 4ms
2022-03-27 10:02:30,793 INFO 45482 [egg:logger] init all loggers with options: {"clients":{"appLogger":{"fileLogName":"midway-web.log","aliasName":"logger"},"agentLogger":{"fileLogName":"midway-agent.log"},"coreLogger":{"fileLogName":"midway-core.log"}},"default":{"dir":"/var/log/fireflyAPIServer","maxSize":"100m","maxFiles":"30d","level":"info","consoleLevel":"info","auditFileDir":".audit"}}
2022-03-27 10:02:30,793 INFO 45482 [egg:core] dump config after load, 4ms
 PASS  test/service/excelService.test.ts
  test/service/excelService.test.ts
    ✓ should GET / (1239 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.028 s
Ran all test suites related to files matching /test\/service\/excelService.test.ts|test/i.
2022-03-27 10:02:31,050 INFO 45482 [egg-static] starting static serve /public/ -> /Users/lj/Work/firefly_api_server/src/app/public
2022-03-27 10:02:31,055 INFO 45482 [egg-security] use methodnoallow middleware
2022-03-27 10:02:31,056 INFO 45482 [egg-security] use noopen middleware
2022-03-27 10:02:31,058 INFO 45482 [egg-security] use nosniff middleware
2022-03-27 10:02:31,058 INFO 45482 [egg-security] use xssProtection middleware
2022-03-27 10:02:31,059 INFO 45482 [egg-security] use xframe middleware
2022-03-27 10:02:31,060 INFO 45482 [egg-security] use dta middleware
2022-03-27 10:02:31,060 INFO 45482 [egg-security] compose 6 middlewares into one security middleware
  console.error
    [winston] Attempt to write logs with no transports {"level":"info","message":"[egg:core] dump config after ready, 4ms"}

      at MidwayBaseLogger._transform (node_modules/winston/lib/winston/logger.js:302:15)
      at MidwayBaseLogger.Object.<anonymous>.Transform._read (node_modules/readable-stream/lib/_stream_transform.js:177:10)
      at MidwayBaseLogger.Object.<anonymous>.Transform._write (node_modules/readable-stream/lib/_stream_transform.js:164:83)
      at doWrite (node_modules/readable-stream/lib/_stream_writable.js:409:139)
      at writeOrBuffer (node_modules/readable-stream/lib/_stream_writable.js:398:5)
      at MidwayBaseLogger.Object.<anonymous>.Writable.write (node_modules/readable-stream/lib/_stream_writable.js:307:11)
      at MidwayBaseLogger.write (node_modules/@midwayjs/logger/dist/logger/logger.js:305:32)
```

My test code: 
//
```ts
import { createApp, close } from '@midwayjs/mock';
import { Framework } from '@midwayjs/web';
import { ExcelService } from '../../src/service/excel';
import * as _ from 'lodash';

describe('test/service/excelService.test.ts', () => {
  it('should GET /', async () => {
    // create app
    const app = await createApp<Framework>();

    // 根据依赖注入 class 获取实例（推荐）
    const excelService = await app
      .getApplicationContext()
      .getAsync<ExcelService>(ExcelService);
    //prettier-ignore
    expect(excelService.getChineseCharLength('测试代码')).toBe(12);
    // close app
    await close(app);
  });
});
```

excelService code
```ts
import { Provide, Inject } from '@midwayjs/decorator';
import { Context } from 'egg';
@Provide()
export class ExcelService {
  @Inject()
  ctx: Context;

  getChineseCharLength(value: string) {
    const res = value.match(/[\u4e00-\u9fa5]/g);
    if (res && Array.isArray(res)) return res.length;
    return 0;
  }
}
```
this doesn't effect any actual function, but it is indeed annoying.
Anyone can help?

**Comment by czy88840616** [comment]
egg still using logger when global logger close.

maybe i can modify this case when egg close（egg will be close it self delay 1s）
