### ISSUE TITLE
@midwayjs/redis interrupts the starting of midway

### ISSUE THREAD

**Issue by csjkevin** [midwayjs/midway#1900]
* **Node Version**: 14.17.5
* **Midway Version(Decorator/Core)**: 3.3.0
* **Component Name/Version**: redis/3.3.0
* **Platform**: macOS

Today when I tried to start my midway project, the console shows the following outputs:

```
TypeError: (0 , core_1.delegateTargetAllPrototypeMethod) is not a function
    at Object.<anonymous> (/project-path/node_modules/.pnpm/@midwayjs+redis@3.3.0/node_modules/@midwayjs/redis/dist/manager.js:106:45)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (project-path/node_modules/.pnpm/@midwayjs+redis@3.3.0/node_modules/@midwayjs/redis/dist/configuration.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
```

And the starting of midway was then interrupted.

I noticed that midway released version 3.3.0 on April 7. I guess if it is the update brought the problem, so I tried to set:

`"@midwayjs/redis": "~3.2",`

on my `package.json`. Then the problem was solved.

Hope this issue can help you notice the problem.

**Comment by czy88840616** [comment]
it is a new api at @midway/core v3.3.0，update it.

**Comment by csjkevin** [comment]
Sure. However, the version I set for `@midwayjs/core` is

`"@midwayjs/core": "^3.0.0"`

It should already takes the latest version. The problem is that the latest version of `@midwayjs/core` cannot work with `@midwayjs/redis`.

**Comment by czy88840616** [comment]
Midway publish by lerna and it will be update version by specific rules. You cannot update a @midwayjs/redis package alone.

You can follow [this guide](https://midwayjs.org/docs/how_to_update_midway) to update your dependence.

I guess your package-lock block the update（I just [disable package-lock.json](https://midwayjs.org/docs/faq/npm_problem#1%E4%B8%8D%E5%B8%8C%E6%9C%9B%E7%94%9F%E6%88%90-package-lockjson) file in local environment).

It is also possible your npm mirror not updated to the new version（very small probability）.

**Comment by csjkevin** [comment]
I think you are right. I figure out the cause of the problem.

I installed `midway` before. Because of the lock file, its version remains 3.2.0. When I installed `@midway/redis` yesterday, it got the latest version, which is 3.3.0. So the issue raised.

By manually updating the dependencies, the problem was solved.

Thank you for your hint.
