### ISSUE TITLE
如果设置了port，就无法用pm2启动

### ISSUE THREAD

**Issue by zhump** [midwayjs/midway#195]
1、package.json设置 
```
"midway-server-options": {
    "port": 17003
  },
```
2、config.default.js
```
  config.cluster = {
         listen: {
             port: 17003,
         },
    };
```
```
0|index  | [2019-04-15 21:49:41.973] [cfork:master:24626] don't fork, because worker:24636 will be kill soon
0|index  | 2019-04-15 21:49:41,973 INFO 24626 [master] app_worker#2:24636 disconnect, suicide: false, state: disconnected, current workers: ["1","2","3","4"]
0|index  | [2019-04-15 21:49:41.974] [cfork:master:24626] worker:24636 exit (code: 0, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
0|index  | 2019-04-15 21:49:41,975 ERROR 24626 nodejs.AppWorkerDiedError: [master] app_worker#2:24636 died (code: 0, signal: null, suicide: false, state: dead), current workers: ["1","3","4"]
0|index  |     at Master.onAppExit (/Volumes/web/server/node_modules/egg-cluster/lib/master.js:408:21)
0|index  |     at emitOne (events.js:116:13)
0|index  |     at Master.emit (events.js:211:7)
0|index  |     at Messenger.sendToMaster (/Volumes/web/server/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
0|index  |     at Messenger.send (/Volumes/web/server/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
0|index  |     at EventEmitter.cluster.on (/Volumes/web/server/node_modules/egg-cluster/lib/master.js:277:22)
0|index  |     at emitThree (events.js:141:20)
0|index  |     at EventEmitter.emit (events.js:217:7)
0|index  |     at ChildProcess.worker.process.once (internal/cluster/master.js:191:13)
0|index  |     at Object.onceWrapper (events.js:317:30)
0|index  | name: "AppWorkerDiedError"
0|index  | pid: 24626
0|index  | hostname: bogon
0|index  | 2019-04-15 21:49:41,975 ERROR 24626 [master] app_worker#2:24636 start fail, exiting with code:1
0|index  | 2019-04-15 21:49:41,975 ERROR 24626 [master] exit with code:1
0|index  | 2019-04-15 21:49:41,981 INFO 24638 [egg:core] dump config after load, 33ms
PM2      | App [index:0] exited with code [1] via signal [SIGINT]
0|index  | 2019-04-15 21:49:41,982 ERROR 24634 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
PM2      | App [index:0] starting in -fork mode-
PM2      | App [index:0] online
0|index  | 2019-04-15 21:49:41,984 ERROR 24634 [agent_worker] exit with code:110
0|index  | 2019-04-15 21:49:42,025 ERROR 24638 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
0|index  | 2019-04-15 21:49:42,539 INFO 24640 [master] =================== midway start =====================
0|index  | 2019-04-15 21:49:42,540 INFO 24640 [master] node version v8.13.0
0|index  | 2019-04-15 21:49:42,541 INFO 24640 [master] midway version 1.4.10
0|index  | 2019-04-15 21:49:42,541 INFO 24640 [master] start with options:
0|index  | {
0|index  |   "framework": "/Volumes/web/server/node_modules/midway",
0|index  |   "baseDir": "/Volumes/web/server",
0|index  |   "port": 17003,
0|index  |   "workers": 4,
0|index  |   "plugins": null,
0|index  |   "https": false,
0|index  |   "typescript": true
 0|index  | }
0|index  | 2019-04-15 21:49:42,541 INFO 24640 [master] start with env: isProduction: true, EGG_SERVER_ENV: prev, NODE_ENV: undefined
0|index  | 2019-04-15 21:49:42,544 INFO 24640 [master] egg version 2.20.1, egg-core version 4.16.1
0|index  | 2019-04-15 21:49:42,549 INFO 24640 [master] agent_worker#1:24645 start with clusterPort:58001
```

**Comment by Lellansin** [comment]
pm2 的启动详情可以贴一下吗
