### ISSUE TITLE
项目中使用到task组件 构建单文件运行会有错误信息: No .lua files found!

### ISSUE THREAD

**Issue by tuohuang** [midwayjs/midway#1958]
* **Node Version**:16.14.0
* **Midway Version(Decorator/Core)**:3.3.5
* **Component Name/Version**:@midwayjs/task  3.3.5
* **Platform**: Linux Ubuntu
* **Mini Showcase Repository**:

项目中使用到task组件且使用的是本地定时任务 构建单文件后 启动运行会有错误信息:
2022-05-05 18:42:12,000 ERROR 17918 Error [unhandledRejectionError]: No .lua files found!
    at loadScripts (/code/midway/build/index.js:57947:11)
    at async /code/midway/build/index.js:57931:15
但是可以正常启动。

如果把构建后的build代码移动到别的地方然后执行里面的index.js会报：ERROR 5889 TypeError: Cannot read properties of undefined (reading '_isAMomentObject')  且无法正常启动：
ERROR 7110 TypeError: Cannot read properties of undefined (reading '_isAMomentObject')
    at new CronTime (/code/test/build/index.js:70125:50)
    at new CronJob (/code/test/build/index.js:70648:19)
    at TaskFramework.loadLocalTask (/code/test/build/index.js:35233:29)
    at TaskConfiguration.onReady (/code/test/build/index.js:35098:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MidwayLifeCycleService.runContainerLifeCycle (/code/test/build/index.js:23414:36)
    at async MidwayLifeCycleService.init (/code/test/build/index.js:23382:9)
    at async ObjectCreator.doInitAsync (/code/test/build/index.js:21700:17)
    at async ManagedResolverFactory.createAsync (/code/test/build/index.js:21243:9)
    at async initializeGlobalApplicationContext (/code/test/build/index.js:24111:5)

以上问题如果不使用@midwayjs/task 3.3.5组件没有问题

**Comment by chenyuncai** [comment]
各个组件更新到最新后，也遇到了这个问题，3.7.4

**Comment by stone-jin** [comment]
不支持构建单文件模式，因为里面有个register lua的逻辑。

**Comment by czy88840616** [comment]
bull 看起来不支持单文件模式。

**Comment by stone-jin** [comment]
https://github.com/OptimalBits/bull/tree/develop/lib/commands ，他需要注册这些lua脚本，单文件的时候，就取不到这些了。你为啥要用单文件模式，单文件模式在生产环境到时排查各类问题也是个问题。我个人建议还是先不要用单文件模式。

**Comment by czy88840616** [comment]
有pkg啥的需求吧。

**Comment by chenyuncai** [comment]
我这边暂时没用单文件模式了。

用ncc原因是pnpm monorepo大项目打包的docker镜像3个G, ncc后一百多M的镜像轻量好发布快。

由于pnpm所有子项目的依赖都在跟目录node_modules里，用prod模式install 后好多影子依赖包丢失

所以现在先正常模式打包，后面再去把各种peerDependence处理好，还是再去试试prod install
