### ISSUE TITLE
打包成单文件 启动报Error: ENOENT: no such file or directory, open '/code/package.json'

### ISSUE THREAD

**Issue by tuohuang** [midwayjs/midway#1959]
* **Node Version**:16.14.0
* **Midway Version(Decorator/Core)**:3.3.5
* **Component Name/Version**:3.3.5
* **Platform**:Linux
* **Mini Showcase Repository**:
[midway-project.zip](https://github.com/midwayjs/midway/files/8638471/midway-project.zip)

项目中使用到阿里云短息的模块包时，将项目打包成单文件后 运行报：
Error: ENOENT: no such file or directory, open 'D:\package.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.exports.loadJSONSync (D:\midway-project\build\index.js:54254:20)
    at Object.97778 (D:\midway-project\build\index.js:1352:28)
    at __nccwpck_require__ (D:\midway-project\build\index.js:77538:43)
    at Object.52291 (D:\midway-project\build\index.js:1391:29)
    at __nccwpck_require__ (D:\midway-project\build\index.js:77538:43)
    at Object.58470 (D:\midway-project\build\index.js:1036:16)
    at __nccwpck_require__ (D:\midway-project\build\index.js:77538:43)
    at Object.50595 (D:\midway-project\build\index.js:511:51) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\package.json'
}

**Comment by czy88840616** [comment]
我们无法保证三方库 ncc 构建后的效果，请将此 issue 提到短信模块包处。
