### ISSUE TITLE
MidwayDefinitionNotFoundError: MidwayFaaSFramework is not valid in current context

### ISSUE THREAD

**Issue by imohuan** [midwayjs/midway#1964]
这里我配置 Serverless 聚合部署
link: https://midwayjs.org/docs/serverless/serverless_aggr
完成部署之后运行 `npm run deploy`之后报错
``` javascript 
 MidwayDefinitionNotFoundError: MidwayFaaSFramework is not valid in current context
      at MidwayContainer.getAsync (/var/user/node_modules/@midwayjs/core/dist/context/container.js:439:19)
      at SCFRuntime.beforeFunctionStart (/var/user/all.js:32:54)
      at async SCFRuntime.handlerInvokerWrapper (/var/user/node_modules/@midwayjs/runtime-engine/dist/runtime.js:169:17)
      at async SCFRuntime.functionStart (/var/user/node_modules/@midwayjs/runtime-engine/dist/runtime.js:42:9)
      at async BaseRuntimeEngine.ready (/var/user/node_modules/@midwayjs/runtime-engine/dist/engine.js:57:9)
      at async BaseBootstrap.start (/var/user/node_modules/@midwayjs/runtime-engine/dist/bootstrap.js:22:9)
      at async start (/var/user/node_modules/@midwayjs/serverless-scf-starter/dist/index.js:31:5)
      at async initializeMethod (/var/user/all.js:36:13)
      at async AsyncFunction.\u003canonymous\u003e (/var/user/all.js:164:7)",
```

# 重现错误步骤
1. `npm init midway -- --type=faas-aggr my_midway_app`
2. `cd my_midway_app`
3. 修改`f.yml`
``` yml
service:
  name: midway-aggr

provider:
  name: tencent
  timeout: 60 # 单位秒

aggregation:
  all:
    functionsPattern: '*'
custom:
  customDomain:
    domainName: auto

```
4. 修改 `package.json`
> 这里直接配置了 `@midwayjs/fcli-plugin-scf`的版本，为了在部署的时候不用额外安装
> 其次就是将内部所有的包提升到了 `3.3.4` 这个阶段
``` json
{
  "name": "midway_faas_project",
  "private": true,
  "version": "1.0.0",
  "description": "Midway Serverless for the Serverless environment",
  "main": "index.js",
  "license": "MIT",
  "keywords": [
    "serverless",
    "midway"
  ],
  "scripts": {
    "dev": "cross-env NODE_ENV=local midway-bin dev --ts",
    "test": "cross-env midway-bin test --ts",
    "deploy": "cross-env UDEV_NODE_ENV=production midway-bin deploy",
    "lint": "mwts check",
    "lint:fix": "mwts fix"
  },
  "dependencies": {
    "@midwayjs/core": "^3.3.5",
    "@midwayjs/decorator": "^3.3.4",
    "@midwayjs/faas": "^3.3.5"
  },
  "devDependencies": {
    "@midwayjs/cli": "^1.3.3",
    "@midwayjs/cli-plugin-faas": "^1.3.3",
    "@midwayjs/fcli-plugin-fc": "^1.3.3",
    "@midwayjs/fcli-plugin-scf": "^1.3.3",
    "@midwayjs/mock": "^3.3.5",
    "@midwayjs/serverless-app": "^3.3.5",
    "@midwayjs/serverless-fc-starter": "^3.3.5",
    "@midwayjs/serverless-fc-trigger": "^3.3.5",
    "@midwayjs/serverless-scf-starter": "^3.3.5",
    "@midwayjs/serverless-scf-trigger": "^3.3.5",
    "@types/jest": "^26.0.10",
    "@types/node": "14",
    "cross-env": "^6.0.0",
    "jest": "^26.4.0",
    "mwts": "^1.0.5",
    "ts-jest": "^26.2.0",
    "typescript": "^4.0.0"
  }
}
```
## 腾讯云打印的错误日志
``` 
START RequestId: c96050613325f083aad2627ad54bcf2f

[0m2022-05-08 10:11:37,743 INFO 8 [midway:bootstrap] current app started[0m

ERROR RequestId: c96050613325f083aad2627ad54bcf2f Result: MidwayDefinitionNotFoundError: MidwayFaaSFramework is not valid in current context     at MidwayContainer.getAsync (/var/user/node_modules/@midwayjs/core/dist/context/container.js:439:19)     at SCFRuntime.beforeFunctionStart (/var/user/all.js:32:54)     at async SCFRuntime.handlerInvokerWrapper (/var/user/node_modules/@midwayjs/runtime-engine/dist/runtime.js:169:17)     at async SCFRuntime.functionStart (/var/user/node_modules/@midwayjs/runtime-engine/dist/runtime.js:42:9)     at async BaseRuntimeEngine.ready (/var/user/node_modules/@midwayjs/runtime-engine/dist/engine.js:57:9)     at async BaseBootstrap.start (/var/user/node_modules/@midwayjs/runtime-engine/dist/bootstrap.js:22:9)     at async start (/var/user/node_modules/@midwayjs/serverless-scf-starter/dist/index.js:31:5)     at async initializeMethod (/var/user/all.js:36:13)     at async AsyncFunction.<anonymous> (/var/user/all.js:164:7)

END RequestId: c96050613325f083aad2627ad54bcf2f

Report RequestId: c96050613325f083aad2627ad54bcf2f Duration: 10ms Memory: 128MB MemUsage: 17.88MB

[31m2022-05-08 10:11:37,744 ERROR 8 Error [unhandledRejectionError]: EROFS: read-only file system, mkdir '/home/qcloud/'[39m

[31m    at Object.mkdirSync (fs.js:840:3)[39m

[31m    at /var/user/node_modules/@midwayjs/logger/dist/transport/fileStreamRotator.js:121:20[39m

[31m    at Array.reduce (<anonymous>)[39m

[31m    at mkDirForFile (/var/user/node_modules/@midwayjs/logger/dist/transport/fileStreamRotator.js:117:27)[39m

[31m    at FileStreamRotator.getStream (/var/user/node_modules/@midwayjs/logger/dist/transport/fileStreamRotator.js:456:9)[39m

[31m    at new DailyRotateFileTransport (/var/user/node_modules/@midwayjs/logger/dist/transport/rotate.js:76:38)[39m

[31m    at MidwayBaseLogger.enableFile (/var/user/node_modules/@midwayjs/logger/dist/logger/logger.js:154:34)[39m

[31m    at new MidwayBaseLogger (/var/user/node_modules/@midwayjs/logger/dist/logger/logger.js:82:18)[39m

[31m    at Map.createLogger (/var/user/node_modules/@midwayjs/logger/dist/container.js:29:28)[39m

[31m    at MidwayLoggerService.createClient (/var/user/node_modules/@midwayjs/core/dist/service/loggerService.js:29:26) {[39m

[31m  errno: -30,[39m

[31m  syscall: 'mkdir',[39m

[31m  code: 'EROFS',[39m

[31m  path: '/home/qcloud/',[39m

[31m  name: 'unhandledRejectionError'[39m

[31m}[39m

[31m2022-05-08 10:11:37,744 ERROR 8 Error [unhandledRejectionError]: EROFS: read-only file system, mkdir '/home/qcloud/'[39m

[31m    at Object.mkdirSync (fs.js:840:3)[39m

[31m    at /var/user/node_modules/@midwayjs/logger/dist/transport/fileStreamRotator.js:121:20[39m

[31m    at Array.reduce (<anonymous>)[39m

[31m    at mkDirForFile (/var/user/node_modules/@midwayjs/logger/dist/transport/fileStreamRotator.js:117:27)[39m

[31m    at FileStreamRotator.getStream (/var/user/node_modules/@midwayjs/logger/dist/transport/fileStreamRotator.js:456:9)[39m

[31m    at new DailyRotateFileTransport (/var/user/node_modules/@midwayjs/logger/dist/transport/rotate.js:76:38)[39m

[31m    at MidwayBaseLogger.enableFile (/var/user/node_modules/@midwayjs/logger/dist/logger/logger.js:154:34)[39m

[31m    at new MidwayBaseLogger (/var/user/node_modules/@midwayjs/logger/dist/logger/logger.js:82:18)[39m

[31m    at Map.createLogger (/var/user/node_modules/@midwayjs/logger/dist/container.js:29:28)[39m

[31m    at MidwayLoggerService.createClient (/var/user/node_modules/@midwayjs/core/dist/service/loggerService.js:29:26) {[39m

[31m  errno: -30,[39m

[31m  syscall: 'mkdir',[39m

[31m  code: 'EROFS',[39m

[31m  path: '/home/qcloud/',[39m

[31m  name: 'unhandledRejectionError'[39m

[31m}[39m

```

**Comment by czy88840616** [comment]
似乎是日志无法写入的报错，但是faas应该把日志覆盖过，可以临时改个日志根目录（搞到临时目录）看看，或者干脆把日志写文件的配置关闭。

**Comment by imohuan** [comment]
```javascript
export const customKey = 'hello';

export const midwayLogger = {
  default: {
    enableConsole: false,
    enableFile: false,
    enableError: false,
    enableJSON: false,
  },
  clients: {
    coreLogger: {
      enableConsole: false,
      enableFile: false,
      enableError: false,
      enableJSON: false,
    },
    appLogger: {
      enableConsole: false,
      enableFile: false,
      enableError: false,
      enableJSON: false,
    },
  },
};

```

没有效果是我配置错误？？

**Comment by czy88840616** [comment]
函数的 midwayLogger 去掉吧，基本上是固定的 ?

**Comment by imohuan** [comment]
额，我不知道怎么做，能不能直接一点，改哪里怎么改，请说清楚？

**Comment by czy88840616** [comment]
你是手动升级到3的吧，我们暂时没有提供 serverless v3的升级，因为还处在试点的阶段，可能还有变化。

核心是因为 configuration.ts 没改吧。

```ts
import { Configuration } from '@midwayjs/decorator';
import { ILifeCycle } from '@midwayjs/core';
import { join } from 'path';
import * as faas from '@midwayjs/faas';

@Configuration({
  import: [faas],
  importConfigs: [join(__dirname, './config/')],
  conflictCheck: true,
})
export class ContainerLifeCycle implements ILifeCycle {
  async onReady() {}
}

```

**Comment by imohuan** [comment]
谢谢了，可以允许了

**Comment by imohuan** [comment]
谢谢了，可以运行了
