### ISSUE TITLE
v3版 任务调度组件 手动任务 按照文档上的写法 触发不了

### ISSUE THREAD

**Issue by yay2008** [midwayjs/midway#1975]
v3版 任务调度组件 手动任务 按照文档上的写法 触发不了

测试代码仓库 
https://github.com/yay2008/midway_v3_task_test.git
调用入口 /controller/home.controller test()

**Comment by stone-jin** [comment]
@yay2008 
你的demo有几个问题：
1、@Inject service，这个service找不到。
2、this.queueService.execute,第二个参数是undefined了。
3、另外错误的日志，可以在common-error.log里面有：
```
2022-05-25 10:56:35,328 ERROR 19978 [Queue][6][HelloTask] MidwayDefinitionNotFoundError: service in class HelloTask is not valid in current context
    at MidwayContainer.getAsync (/midway_v3_task_test/node_modules/_@midwayjs_core@3.3.5@@midwayjs/core/dist/context/container.js:439:19)
    at MidwayRequestContainer.getAsync (/midway_v3_task_test/node_modules/_@midwayjs_core@3.3.5@@midwayjs/core/dist/context/requestContainer.js:67:32)
    at RefResolver.resolveAsync (/midway_v3_task_test/node_modules/_@midwayjs_core@3.3.5@@midwayjs/core/dist/context/managedResolverFactory.js:58:37)
    at ManagedResolverFactory.resolveManagedAsync (/midway_v3_task_test/node_modules/_@midwayjs_core@3.3.5@@midwayjs/core/dist/context/managedResolverFactory.js:92:25)
    at ManagedResolverFactory.createAsync (/midway_v3_task_test/node_modules/_@midwayjs_core@3.3.5@@midwayjs/core/dist/context/managedResolverFactory.js:232:44)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
