### ISSUE TITLE
view-nunjucks的自定义起止符号配置有人配过吗

### ISSUE THREAD

**Issue by stys35** [midwayjs/midway#1989]
这样配置好像没生效

## config.default.ts
```js

export default {

  view: {
    // 模板引擎
    defaultViewEngine: 'nunjucks',
    mapping: {
      '.tpl': 'nunjucks',
    },
    nunjucks: {
      autoescape: true,
      throwOnUndefined: true,
      trimBlocks: true,
      lstripBlocks: true,
      cache: true,
      tags: {
        // blockStart: '{%',
        // blockEnd: '%}',
        variableStart: '{{{',
        variableEnd: '}}}',
        // commentStart: '{#',
        // commentEnd: '#}'
      },
    },
  },
```

## test.tpl
```js
HI, {{{user}}}, 123
```

## 报错
```js
Error
Looks like something broke!

Stack
        
Template render error: (E:\work\xxx\project\_\xxx\view\test.tpl) [Line 1, Column 7]
  parseAggregate: expected colon after dict key
    at Object._prettifyError (E:\work\xxx\project\_\xxx\node_modules\nunjucks\src\lib.js:36:11)
    at Template.render (E:\work\xxx\project\_\xxx\node_modules\nunjucks\src\environment.js:538:21)
    at E:\work\xxx\project\_\xxx\node_modules\nunjucks\src\environment.js:366:27
    at createTemplate (E:\work\xxx\project\_\xxx\node_modules\nunjucks\src\environment.js:315:9)
    at handle (E:\work\xxx\project\_\xxx\node_modules\nunjucks\src\environment.js:327:11)
```

**Comment by czy88840616** [comment]
配置不对，nunjucks 和view平级的。

**Comment by stys35** [comment]
> 配置不对，nunjucks 和view平级的。

ok！！！开始移植平台
