### ISSUE TITLE
调试模式下 useContext<Context>() 获取值为undefined

### ISSUE THREAD

**Issue by RobertChaw** [midwayjs/midway#2000]
* **Node Version**: 18.1.0
* **Midway Version(Decorator/Core)**: 3.3.4/3.3.5
* **Component Name/Version**: midwayjs/hooks 3.0.1
* **Platform**: WebStorm
* **Mini Showcase Repository**:

在函数式开发、使用WebStorm调试的场景下，useContext<Context>()方法返回值为空。
但程序在正常运行时， useContext<Context>()能正常返回。

![image](https://user-images.githubusercontent.com/29568488/169756107-6e690b80-9e78-4ed1-a692-421522a04bcf.png)
![image](https://user-images.githubusercontent.com/29568488/169756354-ddf8d797-0a0f-44c9-913f-a184eea16a12.png)

> undefined
> 2022-05-23 14:04:51,044 ERROR 20992 [-/::ffff:127.0.0.1/-/5377ms GET /api/getList] TypeError: Cannot read properties of 
> undefined (reading 'ip')
>     at D:\Workspace\myBlog-Backend\src\api\article.ts:14:25
>     at D:\Workspace\myBlog-Backend\node_modules\@midwayjs\hooks-core\dist\midwayjs-hooks-core.cjs.dev.js:433:29
>     at dispatch (D:\Workspace\myBlog-Backend\node_modules\koa-compose\index.js:42:32)
>     at D:\Workspace\myBlog-Backend\node_modules\koa-compose\index.js:34:12
>     at D:\Workspace\myBlog-Backend\node_modules\koa-compose\index.js:34:12
>     at runner (D:\Workspace\myBlog-Backend\node_modules\@midwayjs\hooks-core\dist\midwayjs-hooks-core.cjs.dev.js:437:45)    at FunctionContainer.handler (D:\Workspace\myBlog-Backend\node_modules\@midwayjs\hooks\dist\hydrate-6
> 894419f.cjs.dev.js:393:20)
>     at D:\Workspace\myBlog-Backend\node_modules\@midwayjs\core\dist\common\webGenerator.js:27:63
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at D:\Workspace\myBlog-Backend\node_modules\@midwayjs\hooks\dist\midwayjs-hooks.cjs.dev.js:217:68
>     at useUniversalRuntime (D:\Workspace\myBlog-Backend\node_modules\@midwayjs\hooks\dist\midwayjs-hooks.cjs.dev.js:217:12)

**Comment by Lxxyx** [comment]
看一下调试时的 Node.js 版本，+试试看 VSCode Debugger 会不会正常。看堆栈目前是没有问题的
