### ISSUE TITLE
v2 升级v3 遇到的问题

### ISSUE THREAD

**Issue by riskgod** [midwayjs/midway#2008]
```2022-05-27 17:05:44,482 INFO 70067 [master] agent_worker#1:70158 start with clusterPort:61685
2022-05-27 17:05:53,943 ERROR 70158 nodejs.TypeError: (0 , decorator_1.isClass) is not a function
    at ContainerConfiguration.getConfigurationExport (/Users/sh07016ml/bybit/artery-custody-sevice/node_modules/midway/node_modules/@midwayjs/core/dist/context/configuration.js:287:37)
    at ContainerConfiguration.loadConfiguration (/Users/sh07016ml/bybit/artery-custody-sevice/node_modules/midway/node_modules/@midwayjs/core/dist/context/configuration.js:180:47)
    at ContainerConfiguration.load (/Users/sh07016ml/bybit/artery-custody-sevice/node_modules/midway/node_modules/@midwayjs/core/dist/context/configuration.js:157:14)
    at MidwayContainer.load (/Users/sh07016ml/bybit/artery-custody-sevice/node_modules/midway/node_modules/@midwayjs/core/dist/context/midwayContainer.js:85:23)
    at MidwayWebFramework.containerDirectoryLoad (/Users/sh07016ml/bybit/artery-custody-sevice/node_modules/midway/node_modules/@midwayjs/core/dist/baseFramework.js:137:33)
    at MidwayWebFramework.initialize (/Users/sh07016ml/bybit/artery-custody-sevice/node_modules/midway/node_modules/@midwayjs/web/dist/framework/web.js:73:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WebBootstrapStarter.init (/Users/sh07016ml/bybit/artery-custody-sevice/node_modules/midway/node_modules/@midwayjs/web/dist/starter.js:13:9)
    at async /Users/sh07016ml/bybit/artery-custody-sevice/node_modules/midway/node_modules/@midwayjs/web/dist/base.js:232:17
```
看起来像是config 那块没导入 贴上configration 代码 ，我查了下 和示例一样。有点困惑 求助
```
import * as validateComp from '@midwayjs/validate';
import * as webFramework from '@midwayjs/web';
import {
  Configuration,
  App,
  Config,
  Logger,
  Inject,
} from '@midwayjs/decorator';
import * as orm from '@midwayjs/orm';
import * as bodyParser from 'koa-bodyparser';
import { ILifeCycle, IMidwayContainer } from '@midwayjs/core';
import { Application } from '@midwayjs/koa';
import * as prometheus from '@midwayjs/prometheus';
import { createConnections } from 'typeorm';
import { ILogger } from '@midwayjs/logger';
import { join } from 'path';
import { ERRORTYPE } from './interface';
import * as redis from '@midwayjs/redis';
import * as cache from '@midwayjs/cache';
import { CacheManager } from '@midwayjs/cache';
import { RemoteConfigService } from './service/nacos';


@Configuration({
  conflictCheck: true,
  imports: [webFramework, orm, prometheus, redis, cache, validateComp],
  importConfigs: [
    join(__dirname, './config')  
  ],
})
export class ContainerLifeCycle implements ILifeCycle {
  @Logger()
  logger: ILogger;
  @App()
  app: Application;
  @Config('database')
  private database;
  @Config('endpoint')
  private endpoint;
  @Inject()
  cache: CacheManager; // 依赖注入CacheManager
  /** 容器加载配置时候导入nacos配置 */
  async onConfigLoad(container: IMidwayContainer) {
    await container.getAsync(RemoteConfigService);
  }
  async onReady() {
    if (!this.database.orm) {
      throw new Error('orm配置缺失');
    }
    if (
      !this.endpoint ||
      !this.endpoint.lark ||
      !this.endpoint.lark.robot ||
      !this.endpoint.lark.secret ||
      !this.endpoint.lark.userId ||
      !this.endpoint['sec-rc-dog']
    ) {
      throw new Error('报警机器人配置缺失');
    }
    const newOrmConfig = [];
    this.database.orm.map(
      (item) =>
        (item.entities = item.entities.map((it) => join(__dirname, '../', it)))
    );
    this.database.orm.forEach(async (db) => {
      newOrmConfig.push({ ...db, name: db.name });
      await createConnections(newOrmConfig);
    });
    this.app.use(await bodyParser());
    this.app.use(await this.app.generateMiddleware('errorHandlerMiddleware'));
    this.app.use(await this.app.generateMiddleware('performanceMiddleware'));
  }
  async onStop() {
    this.logger.error(ERRORTYPE.FRAMEERROR, '框架退出');
  }
}

```

**Comment by czy88840616** [comment]
这是 decorator 包或者某个组件依赖的 decorator 没升级吧

**Comment by riskgod** [comment]
> 这是 decorator 包或者某个组件依赖的 decorator 没升级吧
我来再检查一遍 谢谢
