### ISSUE TITLE
发布时报错 TypeError: Cannot read properties of undefined (reading 'salt')

### ISSUE THREAD

**Issue by yijie8** [midwayjs/midway#2009]
centos7系统

yarn run deploay

发布到百度

报错：

```
Error! You can try adding the -V parameter for more information output.




TypeError: Cannot read properties of undefined (reading 'salt')
    at Object.decrypt (/www/allweb_ssr/node_modules/crypto-js/cipher-core.js:876:102)
    at Object.decrypt (/www/allweb_ssr/node_modules/crypto-js/cipher-core.js:205:59)
    at AliyunFCPlugin.deployUseServerlessDev (/www/allweb_ssr/node_modules/@midwayjs/fcli-plugin-fc/src/index.ts:206:29)
    at CommandCore.execLifecycle (/www/allweb_ssr/node_modules/@midwayjs/command-core/src/core.ts:216:11)
    at CommandCore.invoke (/www/allweb_ssr/node_modules/@midwayjs/command-core/src/core.ts:182:5)
    at CLI.start (/www/allweb_ssr/node_modules/@midwayjs/command-core/src/cli.ts:192:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by czy88840616** [comment]
deploy 不支持百度吧...
