### ISSUE TITLE
使用@Files,@Fields 装饰器 ，并引入 @midwayjs/swagger  服务，项目启动失败

### ISSUE THREAD

**Issue by bobohuochai** [midwayjs/midway#2013]
* **Node Version**:
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

1.发现 使用 **@Files,@Fields 装饰器**，项目启动时会导致 **swagger** 插件报错，报错信息如下：

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at SwaggerExplorer.expandSchemaRef (/Users/xujun/Documents/github/test-swagger/node_modules/@midwayjs/swagger/dist/swaggerExplorer.js:369:25)
    at SwaggerExplorer.generateRouteMethod (/Users/xujun/Documents/github/test-swagger/node_modules/@midwayjs/swagger/dist/swaggerExplorer.js:264:26)
    at SwaggerExplorer.generatePath (/Users/xujun/Documents/github/test-swagger/node_modules/@midwayjs/swagger/dist/swaggerExplorer.js:149:22)
    at SwaggerExplorer.scanApp (/Users/xujun/Documents/github/test-swagger/node_modules/@midwayjs/swagger/dist/swaggerExplorer.js:72:18)
    at SwaggerConfiguration.onReady (/Users/xujun/Documents/github/test-swagger/node_modules/@midwayjs/swagger/dist/configuration.js:32:22)
    at async MidwayLifeCycleService.runContainerLifeCycle (/Users/xujun/Documents/github/test-swagger/node_modules/@midwayjs/core/dist/service/lifeCycleService.js:88:36)
    at async MidwayLifeCycleService.init (/Users/xujun/Documents/github/test-swagger/node_modules/@midwayjs/core/dist/service/lifeCycleService.js:56:9)
    at async ObjectCreator.doInitAsync (/Users/xujun/Documents/github/test-swagger/node_modules/@midwayjs/core/dist/definitions/objectCreator.js:111:17)
    at async ManagedResolverFactory.createAsync (/Users/xujun/Documents/github/test-swagger/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:252:9)

2.复现bug仓库 https://github.com/bobohuochai/test-swagger/tree/master/src

**Comment by czy88840616** [comment]
你得加 @ApiBody 吧。

**Comment by bobohuochai** [comment]
看其他controller 也没加@ApiBody 可以正常启动，是因为@Files 装饰器特殊嘛

**Comment by czy88840616** [comment]
分析不出来吧。

**Comment by bobohuochai** [comment]
好的，理解了。

**Comment by bobohuochai** [comment]
谢谢回复
