### ISSUE TITLE
初始化V3组件模板失败

### ISSUE THREAD

**Issue by ddzyan** [midwayjs/midway#2016]
使用最新的 cli ，创建 v3 组件模板 报错
```sh
npm init midway                                                                                                                   ✔  10820  16:28:55
✔ Hello, traveller.
  Which template do you like? · component-v3 - A midway component boilerplate for v3
✔ What name would you like to use for the new project? · midway-project
✔ The name 'midway-project' already exists, is it overwritten? (Y/n) · true
⠋ Downloading Boilerplate...
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at NpmPatternGenerator.getPackage (/Users/didi/.npm/_npx/21406589f72956d0/node_modules/create-midway/dist/index.js:13758:36)
    at NpmPatternGenerator.getTemplateConfig (/Users/didi/.npm/_npx/21406589f72956d0/node_modules/create-midway/dist/index.js:13827:20)
    at NpmPatternGenerator.run (/Users/didi/.npm/_npx/21406589f72956d0/node_modules/create-midway/dist/index.js:13604:42)
    at async AddPlugin.generator (/Users/didi/.npm/_npx/21406589f72956d0/node_modules/create-midway/dist/index.js:352:13)
    at async CommandCore.execLiftcycle (/Users/didi/.npm/_npx/21406589f72956d0/node_modules/create-midway/dist/index.js:798:21)
    at async CommandCore.invoke (/Users/didi/.npm/_npx/21406589f72956d0/node_modules/create-midway/dist/index.js:771:9)
    at async cli (/Users/didi/.npm/_npx/21406589f72956d0/node_modules/create-midway/dist/index.js:23:3)
 didi@ruziniu  ~/Documents/work-space/temp  vim /Users/didi/.npm/_npx/21406589f72956d0/node_modules/create-midway/dist/index.js
```

**Comment by czy88840616** [comment]
像是网络/环境问题。。

**Comment by czy88840616** [comment]
目前没有人反馈，是只有这个模板，还是所有模板都有问题?

**Comment by ddzyan** [comment]
其他的没问题

**Comment by czy88840616** [comment]
我目前查到这个错是 npm 客户端从远端查询最新的版本，但是 npm 服务返回的不是一个 JSON（网络超时）会报这个错误，所以可以多试几次。

**Comment by czy88840616** [comment]
https://github.com/midwayjs/light-generator/blob/master/src/generator/NpmPatternGenerator.ts#L53 这个地方。
