### ISSUE TITLE
redis在cluster模式下怎么获取nodes来支持scan

### ISSUE THREAD

**Issue by Thetiso** [midwayjs/midway#2045]
hello, 我们项目使用的是azure的redis， 并且是cluster模式.
当我直接使用this.redisService.scan(xxxxx)的时候只能遍历到一个节点的数据，我应该怎么才能获取到所有节点的数据呢

```
      while(idx != '0') {
        let result = await this.redisService.scan(!idx ? 0 : idx, 'match', `${preffix}*`, 'count', 20)
        idx = result[0]
        all_keys = all_keys.concat(result[1])
      }
````

**Comment by czy88840616** [comment]
配置对么：

```
client: {
      cluster: true,
      nodes: [
         // ...
      ]
    }
```

**Comment by luin** [comment]
可以参考 https://github.com/luin/ioredis#running-commands-to-multiple-nodes

```
const nodes = this.redisService.nodes('master')
await Promise.all(nodes.map(node => node.scan(....)))
```

不过需要每个节点自己维护 cursor。

**Comment by Thetiso** [comment]
> 配置对么：
> 
> ```ts
> client: {
>   cluster: true,
>   nodes: [
>      // ...
>   ]
> }
> ```

配置对的 

```
export const redis = {
    client: {
        cluster: true,
        nodes: [
            {
                port: 6380, // Redis port
                host: 'xxxx, // Redis host
                db: 0,
            },
        ],
        maxRedirections: 1,
        redisOptions: {
            password: 'xxxxx',
            tls: {
                servername: 'xxxxx',
            },
        }
    },
};
```

**Comment by Thetiso** [comment]
> 配置对么：
> 
> ```ts
> client: {
>   cluster: true,
>   nodes: [
>      // ...
>   ]
> }
> ```

配置对的 

```
export const redis = {
    client: {
        cluster: true,
        nodes: [
            {
                port: 6380, // Redis port
                host: 'xxxx, // Redis host
                db: 0,
            },
        ],
        maxRedirections: 1,
        redisOptions: {
            password: 'xxxxx',
            tls: {
                servername: 'xxxxx',
            },
        }
    },
};
```

**Comment by czy88840616** [comment]
按上面的nodes方法呢

**Comment by Thetiso** [comment]
> const nodes = this.redisService.nodes('master')
直接提示：
Property 'nodes' does not exist on type 'RedisService'   

我的版本是"@midwayjs/redis": "^2.14.0",

**Comment by Thetiso** [comment]
> https://github.com/luin/ioredis#running-commands-to-multiple-nodes

直接提示：
Property 'nodes' does not exist on type 'RedisService'

**Comment by czy88840616** [comment]
你可以这样拿吧 this.redisService['instance']

**Comment by Thetiso** [comment]
> this.redisService['instance']

确实拿到了实例，不过又有新的问题： 当我scan的时候
```
2022-06-18 16:41:00,288 ERROR 3508 [midway:socketIO] ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/Users/matthew/Desktop/WP/xiaoice/Mid_Disco/schedule-server/node_modules/_ioredis@4.28.5@ioredis/built/cluster/index.js:401:31)
    at /Users/matthew/Desktop/WP/xiaoice/Mid_Disco/schedule-server/node_modules/_ioredis@4.28.5@ioredis/built/cluster/index.js:418:21
    at Timeout.<anonymous> (/Users/matthew/Desktop/WP/xiaoice/Mid_Disco/schedule-server/node_modules/_ioredis@4.28.5@ioredis/built/cluster/index.js:677:24)
    at Timeout.run (/Users/matthew/Desktop/WP/xiaoice/Mid_Disco/schedule-server/node_modules/_ioredis@4.28.5@ioredis/built/utils/index.js:157:22)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:498:7) {
  lastNodeError: Error: timeout
      at Object.timeout (/Users/matthew/Desktop/WP/xiaoice/Mid_Disco/schedule-server/node_modules/_ioredis@4.28.5@ioredis/built/utils/index.js:160:38)
      at Cluster.getInfoFromNode (/Users/matthew/Desktop/WP/xiaoice/Mid_Disco/schedule-server/node_modules/_ioredis@4.28.5@ioredis/built/cluster/index.js:674:55)
      at tryNode (/Users/matthew/Desktop/WP/xiaoice/Mid_Disco/schedule-server/node_modules/_ioredis@4.28.5@ioredis/built/cluster/index.js:407:19)
      at Cluster.refreshSlotsCache (/Users/matthew/Desktop/WP/xiaoice/Mid_Disco/schedule-server/node_modules/_ioredis@4.28.5@ioredis/built/cluster/index.js:426:9)
      at /Users/matthew/Desktop/WP/xiaoice/Mid_Disco/schedule-server/node_modules/_ioredis@4.28.5@ioredis/built/cluster/index.js:198:22
```

我debug的时候发现，获取到的nodes， for-of的时候 node.status = 'wait' 


我的代码是这样的
```
    let preffix = RedisUtil.getUsrSetKeyForDate({date_key})
    let idx = ''
    let all_keys = []
    const redis = this.redisService['instance']
    const nodes = redis.isCluster ? redis.nodes('master') : [this.redisService]
    console.log(nodes.length)   // 这里返回是 1
    for (const node of nodes) {
      idx = ''
      while(idx != '0') {
        let result = await node.scan(!idx ? 0 : idx, 'match', `${preffix}*`, 'count', 20)
        idx = result[0]
        all_keys = all_keys.concat(result[1])
      }
    }
    return all_keys 
```


我的config.default.ts中配置了一个redis.client  => 是个开发环境的单例redis
我在config.local.ts中配置了redis.cluster = true和redis.nodes ，  local链接的是cluster的redis

**Comment by czy88840616** [comment]
这个我就不太懂了。得 @luin ioredis 作者了。。

**Comment by czy88840616** [comment]
怎么感觉像是配置合并的问题，你可以打印看看合并后的配置是什么。

**Comment by Thetiso** [comment]
> 怎么感觉像是配置合并的问题，你可以打印看看合并后的配置是什么。
> 
> 1、default 会和 local 合并的 2、数组合并是覆盖，而不是 mixin

我索性直接清掉了default的redis配置 ，  然后 我试着给redis做了个标记，到底返回的是开发还是正式的redis， 神奇的事情发生了。

```
    let preffix = RedisUtil.getUsrSetKeyForDate({date_key})
    let idx = ''
    let all_keys = []
    const redis = this.redisService['instance']
    console.log(await this.redisService.hget('XXXXX:CONFIG', 'env'))   //prod
    const nodes = redis.isCluster ? redis.nodes('master') : [this.redisService]
    console.log(nodes.length)   // 6
    for (const node of nodes) {
      idx = ''
      while(idx != '0') {
        //node.status = connecting
        let result = await node.scan(!idx ? 0 : idx, 'match', `${preffix}*`, 'count', 20)
        idx = result[0]
        all_keys = all_keys.concat(result[1])
      }
    }

```

**Comment by Thetiso** [comment]
我又试着删除那行获取env的代码，  直接就失败了

**Comment by czy88840616** [comment]
你可以在一开始看环境和配置啊
app.getEnv（）以及app.getConfig（“redis”）

**Comment by Thetiso** [comment]
> 你可以在一开始看环境和配置啊 app.getEnv（）以及app.getConfig（“redis”）
哈哈 一开始没怀疑是配置的问题   , 我是在scripts里面指定了node_env=local 
<img width="616" alt="image" src="https://user-images.githubusercontent.com/8968567/174433837-c7bd2c77-6e2d-4351-99c6-6f6b3bf4e36e.png">


现在的问题是nodes中status的会执行scan，但是也有处于end状态的，  scan的时候进程就直接停在那不动了。 sad

**Comment by czy88840616** [comment]
试试ctrl+c彻底停了，确定没node进程了再起，如果配置正确只是状态不对的话，那这个就是和redis底层或者服务有关了。

**Comment by Thetiso** [comment]
> 试试ctrl+c彻底停了，确定没node进程了再起，如果配置正确只是状态不对的话，那这个就是和redis底层或者服务有关了。

好的好的

**Comment by Thetiso** [comment]
Mark一下： 
1. 核对config配置， redisService['instance'].option => 确认所有参数都是prod
2. 使用redisService['instance'].nodes('master')来**遍历前需要调用**this.redisService.get来随便完成一个操作
3. 这时候的nodes数量就会正确，scan也会获得想到的结果

再次感谢 @czy88840616 的帮助~
