### ISSUE TITLE
用httpService上传图片报错

### ISSUE THREAD

**Issue by Thetiso** [midwayjs/midway#2071]
```js
        let file_response = await this.httpService.get(image_url, { responseType: 'arraybuffer' })
        let file_name = image_url.split('/').pop()
        let filedate = file_response.data
        let arraybuffer = filedate.buffer
        let param = new FormData()
        param.append("media", new File([arraybuffer], file_name))
        param.append("filename", file_name)
        param.append("filelength", Buffer.byteLength(file_response.data))
        let access_token = await this.receptionistService._getAccessTokenFromWx()
        let url = `https://qyapi.weixin.qq.com/cgi-bin/media/upload?access_token=${access_token}&type=image`
        let media_response = await this.httpService.post(url, param, {
            headers: { 'Content-Type': 'multipart/form-data' },
            transformRequest: [function (data, headers) {
                delete headers.post['Content-Type']
                return data
            }],
        })
        console.log(media_response)
```

我的image_url是一个oss地址，后台需要将这个文件下载下来再上传到微信服务器获取media_id。
我测试用node-fetch可以顺利获取到梳理。
但是直接用内置的axios.post就会一直报这个错误

```
[ Midway ] Error: Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream
    at createError (D:\WP\code\cs\mid\Mid_4_Corp_WX\node_modules\_axios@0.26.1@axios\lib\core\createError.js:16:15)
    at dispatchHttpRequest (D:\WP\code\cs\mid\Mid_4_Corp_WX\node_modules\_axios@0.26.1@axios\lib\adapters\http.js:98:23)
    at new Promise (<anonymous>)
    at httpAdapter (D:\WP\code\cs\mid\Mid_4_Corp_WX\node_modules\_axios@0.26.1@axios\lib\adapters\http.js:48:10)
    at dispatchRequest (D:\WP\code\cs\mid\Mid_4_Corp_WX\node_modules\_axios@0.26.1@axios\lib\core\dispatchRequest.js:58:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ReceptionistMessageService.sendImageMsgToUsr (D:\WP\code\cs\mid\Mid_4_Corp_WX\src\service\receptionist.msg.ts:83:30)
    at async ReceptionistController.getMsg (D:\WP\code\cs\mid\Mid_4_Corp_WX\src\controller\receptionist.ts:219:23)
    at async ReceptionistController.Clz.<computed> (D:\WP\code\cs\mid\Mid_4_Corp_WX\node_modules\_@midwayjs_core@3.3.5@@midwayjs\core\dist\service\aspectService.js:89:34)
    at async Object.<anonymous> (D:\WP\code\cs\mid\Mid_4_Corp_WX\node_modules\_@midwayjs_core@3.3.5@@midwayjs\core\dist\common\webGenerator.js:27:28) { 
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function (anonymous)] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'multipart/form-data',
      'User-Agent': 'axios/0.26.1'
    },
    method: 'post',
    url: 'https://qyapi.weixin.qq.com/cgi-bin/media/upload?access_token=XXXXXXXXX&type=image',     
    data: FormData
  },
  request: undefined,
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by czy88840616** [comment]
这个就是个 axios，可以 google axios 如何下载文件。

**Comment by Thetiso** [comment]
> 这个就是个 axios，可以 google axios 如何下载文件。

我这边是上传文件！
感谢~  正在看axios的问题~

**Comment by Thetiso** [comment]
后来用了一个超级古老的办法解决.

- 最新版的node-fetch强制ESM, 和v2不搭，放弃
- axios始终没找到错的哪，报错如上， 放弃
- http/https模块的话，借用form-data没办法直接append(xxx, Buffer/Arraybuffer)
- node-formdata虽然在test下和node-fetch能完美运行，但在正式环境中会有ts检查错误， 弃用
- 最终：  2年前的request顺利运行

**地下的代码是从postman里面借鉴的**  -> Code snippet

```

let file_response = await this.httpService.get(image_url, { responseType: 'arraybuffer' })
let file_name = image_url.split('/').pop()
let access_token = await this.receptionistService._getAccessTokenFromWx()
var options = {
    'method': 'POST',
    'url': `https://qyapi.weixin.qq.com/cgi-bin/media/upload?access_token=${access_token}&type=image`,
    'headers': {
    },
    formData: {
      'media': {
        'value': file_response.data,
        'options': {
          'filename': file_name,
          'contentType': null
        }
      }
    }
  };
  request(options, function (error, response) {
    if (error) throw new Error(error);
    console.log(response.body);
    let res = JSON.parse(response.body)
    resolve(res?.media_id)
  });
})
```
