### ISSUE TITLE
单元测试超时意外奔溃

### ISSUE THREAD

**Issue by ddzyan** [midwayjs/midway#2104]
在进行单元测试的时候，流程在 createApp 无返回，导致超时错误，控制台完整输出内容如下
```
> crypto-mint@1.0.0 test
> midway-bin test --ts -f test/comm/email.test.ts

Testing test/comm/email.test.ts
2022-07-10 00:31:19,653 WARN 57466 plugin i18n has been defined that is {"enable":false,"package":"egg-i18n","name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/Users/didi/Documents/work-space/diancun/crypto-mint/node_modules/@midwayjs/web/config/plugin.js"}, but you define again in /Users/didi/Documents/work-space/diancun/crypto-mint/src/config/plugin.default.ts
2022-07-10 00:31:19,688 INFO 57466 [egg:logger] init all loggers with options: {"clients":{"appLogger":{"fileLogName":"midway-web.log","aliasName":"logger"},"agentLogger":{"fileLogName":"midway-agent.log"},"coreLogger":{"fileLogName":"midway-core.log"},"taskLog":{"fileLogName":"midway-task.log","disableConsole":true}},"default":{"dir":"/Users/didi/Documents/work-space/diancun/crypto-mint/logs/crypto-mint","level":"info","consoleLevel":"info","auditFileDir":".audit"}}
2022-07-10 00:31:19,690 INFO 57466 [egg:core] dump config after load, 9ms
2022-07-10 00:31:19,772 INFO 57466 [egg:core] dump config after ready, 6ms
2022-07-10 00:31:19,776 WARN 57466 plugin i18n has been defined that is {"enable":false,"package":"egg-i18n","name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/Users/didi/Documents/work-space/diancun/crypto-mint/node_modules/@midwayjs/web/config/plugin.js"}, but you define again in /Users/didi/Documents/work-space/diancun/crypto-mint/src/config/plugin.default.ts
2022-07-10 00:31:19,790 INFO 57466 [egg:logger] init all loggers with options: {"clients":{"appLogger":{"fileLogName":"midway-web.log","aliasName":"logger"},"agentLogger":{"fileLogName":"midway-agent.log"},"coreLogger":{"fileLogName":"midway-core.log"},"taskLog":{"fileLogName":"midway-task.log","disableConsole":true}},"default":{"dir":"/Users/didi/Documents/work-space/diancun/crypto-mint/logs/crypto-mint","level":"info","consoleLevel":"info","auditFileDir":".audit"}}
2022-07-10 00:31:19,791 INFO 57466 [egg:core] dump config after load, 6ms
(node:57466) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
(Use `node --trace-deprecation ...` to show where the warning was created)
2022-07-10 00:31:20,079 INFO 57466 [egg-security] use methodnoallow middleware
2022-07-10 00:31:20,080 INFO 57466 [egg-security] use noopen middleware
2022-07-10 00:31:20,081 INFO 57466 [egg-security] use nosniff middleware
2022-07-10 00:31:20,082 INFO 57466 [egg-security] use xssProtection middleware
2022-07-10 00:31:20,083 INFO 57466 [egg-security] use xframe middleware
2022-07-10 00:31:20,084 INFO 57466 [egg-security] use dta middleware
2022-07-10 00:31:20,084 INFO 57466 [egg-security] compose 6 middlewares into one security middleware
2022-07-10 00:31:20,102 WARN 57466 jaegerComponent appMiddleware is not valid Array
2022-07-10 00:31:20,103 INFO 57466 [midway:redis] server connecting redis://:***@127.0.0.1:16379/{ [Symbol(origin_args)]: [Array] }
2022-07-10 00:31:20,236 INFO 57466 [midway:redis] client connect success
2022-07-10 00:31:20,241 INFO 57466 [egg:core] dump config after ready, 5ms
  console.log
    Executed (default): SELECT 1+1 AS result Elapsed time: 1ms

      at Sequelize.log (node_modules/sequelize/src/sequelize.js:1197:15)

  console.log
    ✅ Your APP launched { pkgName: 'xxx', pkgVersion: '1.0.0' }

      at ContainerLifeCycle.onReady (src/configuration.ts:74:13)

 FAIL  test/comm/email.test.ts (12.648 s)
  test/comm/email.test.ts
    ✕ test email sendNotice wallet_insufficient_funds (11783 ms)

  ● test/comm/email.test.ts › test email sendNotice wallet_insufficient_funds

    : Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.Error:

       8 | 
       9 | describe(filename, () => {
    > 10 |   it('test email sendNotice wallet_insufficient_funds', async () => {
         |   ^
      11 |     const app = await createApp<Framework>();
      12 |     const emailUtils = await app
      13 |       .getApplicationContext()

      at new Spec (node_modules/@midwayjs/cli-plugin-test/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (test/comm/email.test.ts:10:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        12.695 s
```

单元测试文件
```ts
import { createApp, close } from '@midwayjs/mock';
import { Framework } from '@midwayjs/web';
import { relative } from 'path';
import { EMAIL_TYPE } from '../../src/app/constant/email';
import { EmailUtils } from '../../src/app/comm/email';

const filename = relative(process.cwd(), __filename).replace(/\\/gu, '/');

describe(filename, () => {
  it('test sendNotice wallet_insufficient_funds', async () => {
   // 断点停在这一步，没有返回
    const app = await createApp<Framework>();
    const emailUtils = await app
      .getApplicationContext()
      .getAsync<EmailUtils>(EmailUtils);

    const result = await emailUtils.sendNotice(
      'ddzyan@163.com',
      EMAIL_TYPE.WALLET_INSUFFICIENT_FUNDS
    );

    expect(result).toBe(true);
    await close(app);
  });
});
```

**Comment by czy88840616** [comment]
参考测试章节，egg 10s不够的，起码30s

**Comment by ddzyan** [comment]
嗯，这个我修改测试过，结果还是一样的，从控制台的输出结果看，好像项目启动后就没再运行单元测试用例了
```
> crypto-mint@1.0.0 test
> midway-bin test --ts -f test/comm/email.test.ts

Testing test/comm/email.test.ts
2022-07-10 19:09:12,584 WARN 67967 plugin i18n has been defined that is {"enable":false,"package":"egg-i18n","name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/Users/didi/Documents/work-space/diancun/crypto-mint/node_modules/@midwayjs/web/config/plugin.js"}, but you define again in /Users/didi/Documents/work-space/diancun/crypto-mint/src/config/plugin.default.ts
2022-07-10 19:09:12,619 INFO 67967 [egg:logger] init all loggers with options: {"clients":{"appLogger":{"fileLogName":"midway-web.log","aliasName":"logger"},"agentLogger":{"fileLogName":"midway-agent.log"},"coreLogger":{"fileLogName":"midway-core.log"},"taskLog":{"fileLogName":"midway-task.log","disableConsole":true}},"default":{"dir":"/Users/didi/Documents/work-space/diancun/crypto-mint/logs/crypto-mint","level":"info","consoleLevel":"info","auditFileDir":".audit"}}
2022-07-10 19:09:12,621 INFO 67967 [egg:core] dump config after load, 10ms
2022-07-10 19:09:12,714 INFO 67967 [egg:core] dump config after ready, 7ms
2022-07-10 19:09:12,719 WARN 67967 plugin i18n has been defined that is {"enable":false,"package":"egg-i18n","name":"i18n","dependencies":[],"optionalDependencies":[],"env":[],"from":"/Users/didi/Documents/work-space/diancun/crypto-mint/node_modules/@midwayjs/web/config/plugin.js"}, but you define again in /Users/didi/Documents/work-space/diancun/crypto-mint/src/config/plugin.default.ts
2022-07-10 19:09:12,733 INFO 67967 [egg:logger] init all loggers with options: {"clients":{"appLogger":{"fileLogName":"midway-web.log","aliasName":"logger"},"agentLogger":{"fileLogName":"midway-agent.log"},"coreLogger":{"fileLogName":"midway-core.log"},"taskLog":{"fileLogName":"midway-task.log","disableConsole":true}},"default":{"dir":"/Users/didi/Documents/work-space/diancun/crypto-mint/logs/crypto-mint","level":"info","consoleLevel":"info","auditFileDir":".audit"}}
2022-07-10 19:09:12,733 INFO 67967 [egg:core] dump config after load, 5ms
(node:67967) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
(Use `node --trace-deprecation ...` to show where the warning was created)
2022-07-10 19:09:13,001 INFO 67967 [egg-security] use methodnoallow middleware
2022-07-10 19:09:13,002 INFO 67967 [egg-security] use noopen middleware
2022-07-10 19:09:13,003 INFO 67967 [egg-security] use nosniff middleware
2022-07-10 19:09:13,004 INFO 67967 [egg-security] use xssProtection middleware
2022-07-10 19:09:13,005 INFO 67967 [egg-security] use xframe middleware
2022-07-10 19:09:13,005 INFO 67967 [egg-security] use dta middleware
2022-07-10 19:09:13,006 INFO 67967 [egg-security] compose 6 middlewares into one security middleware
2022-07-10 19:09:13,023 WARN 67967 jaegerComponent appMiddleware is not valid Array
2022-07-10 19:09:13,024 INFO 67967 [midway:redis] server connecting redis://:***@127.0.0.1:16379/{ [Symbol(origin_args)]: [Array] }
2022-07-10 19:09:13,161 INFO 67967 [midway:redis] client connect success
2022-07-10 19:09:13,166 INFO 67967 [egg:core] dump config after ready, 5ms
  console.log
    Executed (default): SELECT 1+1 AS result Elapsed time: 2ms

      at Sequelize.log (node_modules/sequelize/src/sequelize.js:1197:15)

  console.log
    ✅ Your APP launched { pkgName: 'crypto-mint', pkgVersion: '1.0.0' }

      at ContainerLifeCycle.onReady (src/configuration.ts:73:13)

 FAIL  test/comm/email.test.ts (62.855 s)
  test/comm/email.test.ts
    ✕ test sendNotice wallet_insufficient_funds (61953 ms)

  ● test/comm/email.test.ts › test sendNotice wallet_insufficient_funds

    : Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Error:

       8 | 
       9 | describe(filename, () => {
    > 10 |   it('test sendNotice wallet_insufficient_funds', async () => {
         |   ^
      11 |     const app = await createApp<Framework>();
      12 |     const emailUtils = await app
      13 |       .getApplicationContext()

      at new Spec (node_modules/@midwayjs/cli-plugin-test/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (test/comm/email.test.ts:10:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        62.904 s, estimated 69 s
Ran all test suites related to files matching /test\/comm\/email.test.ts|test/i.




Error! You can try adding the -V parameter for more information output.




Error: /Users/didi/Documents/work-space/diancun/crypto-mint/node_modules/@midwayjs/cli-plugin-test/node_modules/jest/bin/jest.js --findRelatedTests,test/comm/email.test.ts,--_=test,--config=/Users/didi/Documents/work-space/diancun/crypto-mint/node_modules/@midwayjs/cli-plugin-test/config/jest.ts.js exit with code 1
    at ChildProcess.<anonymous> (/Users/didi/Documents/work-space/diancun/crypto-mint/node_modules/@midwayjs/command-core/src/utils/fork.ts:32:26)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 1
}
```

**Comment by czy88840616** [comment]
你是不是单测里（或者 default 文件里）给了个 port 启动端口了。。。

**Comment by ddzyan** [comment]
> 你是不是单测里给了个 port 启动端口了。。。

没有，上面有我的单测文件，还是非常简单的

**Comment by waitingsong** [comment]
`const app = await createApp<Framework>();` 
改为指定一个测试目录呢？
`const app = await createApp(join(__dirname, 'fixtures', 'base-app'), opts) as Application`

在  `test/fixtures/base-app` 放个测试项目

**Comment by ddzyan** [comment]
已经定位出问题，原因是 rabbitMQ 参数配置错误，模块初始化一直处于等待状态，已提交pr https://github.com/midwayjs/midway/pull/2130
