### ISSUE TITLE
使用examples里面的模板启动报错

### ISSUE THREAD

**Issue by sky124380729** [midwayjs/midway#2118]
使用react-faas和vue-faas模板都会报以下同样的错误

- 在windows环境下报 NODE_ENV 为undefined

- 修复上述问题后，会报以下错误

[ Midway ] TypeError: Cannot read properties of undefined (reading 'requestContext')
    at createMiddleware (E:\fullstack\perf-monitoring\node_modules\@midwayjs\serve\dist\midwayjs-serve.cjs.dev.js:27:29)
    at E:\fullstack\perf-monitoring\node_modules\@midwayjs\serve\dist\midwayjs-serve.cjs.dev.js:43:102
    at E:\fullstack\perf-monitoring\node_modules\@midwayjs\hooks\dist\midwayjs-hooks.cjs.dev.js:225:14
    at dispatch (E:\fullstack\perf-monitoring\node_modules\@midwayjs\core\dist\service\middlewareService.js:88:48)
    at composeFn (E:\fullstack\perf-monitoring\node_modules\@midwayjs\core\dist\service\middlewareService.js:76:20)
    at E:\fullstack\perf-monitoring\node_modules\@midwayjs\faas\dist\framework.js:122:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async E:\fullstack\perf-monitoring\node_modules\@midwayjs\core\dist\baseFramework.js:239:36
    at async E:\fullstack\perf-monitoring\node_modules\@midwayjs\faas\dist\framework.js:125:20
    at async FCRuntime.invokeHandlerWrapper (E:\fullstack\perf-monitoring\node_modules\@midwayjs\runtime-engine\dist\lightRuntime.js:19:28)

**Comment by czy88840616** [comment]
这是哪个模版？

**Comment by zangguojun** [comment]
大概啥时候更新？
目前发现 react-faas的模板 除了上诉问题，还不支持vite3
