### ISSUE TITLE
有关midway3-web使用自定义日志下，不配置`fileLogName`输出日志文件名字段就报错问题：[ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by JYbill** [midwayjs/midway#2265]
* **Node Version**: v14.19.1
* **Midway Version(Decorator/Core)**: 
```json
    "@midwayjs/bootstrap": "^3.0.0",
    "@midwayjs/core": "^3.0.0",
    "@midwayjs/web": "^3.0.0",
    "@midwayjs/decorator": "^3.0.0",
    "egg": "^2.0.0"
```
* **Platform**: macos
* **复现步骤**:
* 1. `npm init midawy` -> `midway3 web`
* 2. `config.default.ts`下
```ts
export default (appInfo: MidwayAppInfo) => {
  return {
    // use for cookie sign key, should change to your own and keep security
    keys: appInfo.name + '_1661397917388_493',
    egg: {
      port: 7001,
    },
    midwayLogger: {
      clients: {
        middlewareLogger: {
          // fileLogName: 'request.log', // 注释掉指定日志名就会报错
          format: info => {
            const ctx = info.ctx;
            return `${info.timestamp} ${info.LEVEL} ${info.pid} [${
              Date.now() - ctx.startTime
            }ms ${ctx.method}] ${info.message}`;
          },
        },
      },
    },
  } as MidwayConfig;
};
```
3. 报错内容
```typescript
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at isAbsolute (path.js:1133:5)
    at checkEggLoggerExistsAndBackup (/Users/xiaoqinvar/Downloads/test/node_modules/@midwayjs/web/dist/logger.js:46:40)
    at Map.createLogger (/Users/xiaoqinvar/Downloads/test/node_modules/@midwayjs/web/dist/logger.js:129:9)
    at new MidwayLoggers (/Users/xiaoqinvar/Downloads/test/node_modules/@midwayjs/web/dist/logger.js:111:22)
    at createLoggers (/Users/xiaoqinvar/Downloads/test/node_modules/@midwayjs/web/dist/logger.js:207:21)
    at EggAgent.get loggers [as loggers] (/Users/xiaoqinvar/Downloads/test/node_modules/@midwayjs/web/dist/base.js:311:60)
    at EggAgent.getLogger (/Users/xiaoqinvar/Downloads/test/node_modules/egg/lib/egg.js:322:17)
    at EggAgent.get coreLogger [as coreLogger] (/Users/xiaoqinvar/Downloads/test/node_modules/egg/lib/egg.js:340:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

- 🤔️question：
我不知道是bug，还是使用自定义日志就需要加上`fileLogName`字段，官方文档里面也没说过需要强制加上

**Comment by czy88840616** [comment]
不是bug噢，写文件日志需要提供日志的名字哦

**Comment by JYbill** [comment]
ok. thanks, 只是表达疑惑，当时注释掉了这个以为自己业务问题，找了段时间.
