### ISSUE TITLE
函数一体化下依赖注入出错MidwayDefinitionNotFoundError

### ISSUE THREAD

**Issue by zhangfisher** [midwayjs/midway#2451]
* **Node Version**: 18
    "@midwayjs/cache": "^3.6.0",
    "@midwayjs/hooks": "^3.0.0",
    "@midwayjs/hooks-kit": "^3.0.0",
    "@midwayjs/koa": "^3.1.0",
    "@midwayjs/rpc": "^3.0.0",
* **Component Name/Version**:
* **Platform**:windows

1.创建管方例子  npx degit https://github.com/midwayjs/hooks/examples/react ./hooks-app

2. add files`src/service/users.ts`,内容如下：
```
import { Provide, Scope } from '@midwayjs/decorator'; 

@Provide()
export class UserService {
  getUser(id: number) {
    return `getUser${String(id)}`
  }
}
```
3. 使用该服务在`apis/date.ts`
```
import { Api, Get,useInject } from '@midwayjs/hooks';
import { UserService } from '../service/users';

export const getDate = Api(Get(), async () => {
    let users: UserService = await useInject(UserService)
    return users.getUser(100) "=" + new Date().toString();
});

```

想通过useInject获取到UserService实例失败，出错如下：

```
2022-10-28 17:25:56,050 ERROR 74428 [-/::ffff:127.0.0.1/-/22ms GET /api/getDate] MidwayDefinitionNotFoundError: d1f89d44e2b6f8f9a4645c992b
9c07a4 is not valid in current context
    at MidwayContainer.getAsync (D:\Temp\Code\nodejs2\midway\hooks-app2\node_modules\.pnpm\@midwayjs+core@3.6.0\node_modules\@midwayjs\cor
e\dist\context\container.js:451:19)
    at MidwayRequestContainer.getAsync (D:\Temp\Code\nodejs2\midway\hooks-app2\node_modules\.pnpm\@midwayjs+core@3.6.0\node_modules\@midwa
yjs\core\dist\context\requestContainer.js:67:32)
    at useInject (D:\Temp\Code\nodejs2\midway\hooks-app2\node_modules\.pnpm\@midwayjs+hooks@3.0.1\node_modules\@midwayjs\hooks\dist\midway
js-hooks.cjs.dev.js:49:25)
    at D:\Temp\Code\nodejs2\midway\hooks-app2\src\api\date.ts:5:45
    at D:\Temp\Code\nodejs2\midway\hooks-app2\node_modules\.pnpm\@midwayjs+hooks-core@3.0.1\node_modules\@midwayjs\hooks-core\dist\midwayj
s-hooks-core.cjs.dev.js:433:29
    at dispatch (D:\Temp\Code\nodejs2\midway\hooks-app2\node_modules\.pnpm\koa-compose@4.1.0\node_modules\koa-compose\index.js:42:32)
    at D:\Temp\Code\nodejs2\midway\hooks-app2\node_modules\.pnpm\koa-compose@4.1.0\node_modules\koa-compose\index.js:34:12
    at runner (D:\Temp\Code\nodejs2\midway\hooks-app2\node_modules\.pnpm\@midwayjs+hooks-core@3.0.1\node_modules\@midwayjs\hooks-core\dist
\midwayjs-hooks-core.cjs.dev.js:437:45)
    at FunctionContainer.handler (D:\Temp\Code\nodejs2\midway\hooks-app2\node_modules\.pnpm\@midwayjs+hooks@3.0.1\node_modules\@midwayjs\h
ooks\dist\hydrate-6894419f.cjs.dev.js:393:20)
    at D:\Temp\Code\nodejs2\midway\hooks-app2\node_modules\.pnpm\@midwayjs+core@3.6.0\node_modules\@midwayjs\core\dist\common\webGenerator
.js:42:61 {
  code: 'MIDWAY_10003',
  cause: undefined,
  [Symbol(#NotFoundError)]: Symbol(#NotFoundError)
```

**Comment by czy88840616** [comment]
apis 才是node的地方，服务端代码都要写在这个里面。

**Comment by zhangfisher** [comment]
文档没有说明服务端代码只能写在apis里面
