### ISSUE TITLE
node 18 build失败

### ISSUE THREAD

**Issue by zzfn** [midwayjs/midway#2461]
```
+ node -v
v18.12.0
+ pnpm -v
7.14.1
+ pnpm install
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +958
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 958, reused 0, downloaded 1, added 0
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/2b/ec1efb4dc59fa436c38a1b45b3dbd54a368460bcbbb3d9791b65275b5dc3c71a4c54be458f4c74761dccb8897efaab46df5a407723da5c48f3db02d555d5b9' -> '/drone/src/node_modules/.pnpm/ms@2.1.2/node_modules/_tmp_17_faeadfa9ff9a08d992c16bbff848061b/license.md'
Falling back to copying packages from store
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: /drone/src/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/ec/e1033aa7bd3fe3c0decb3b2fc69179f700a88894f318d8afb09cff55e867faf17d23f9c435544cb36541e1ced82240e76b1467b42b8d5b5fceefd6b9bd85c4' -> '/drone/src/node_modules/.pnpm/sm3@1.0.3/node_modules/_tmp_17_155925389907bed40f695d75faf219da/package.json'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/5b/371f03fe1099151307bb01c448e0e3e93b3ad3b39ed1bdeb660733e81e216ef93ac2a1ff2fef331168825aaf022e3ca3eb5a5bf9606802a5654a70abea3009' -> '/drone/src/node_modules/.pnpm/ini@1.3.8/node_modules/_tmp_17_5a9d91e50ba8ff58aca05ca767d06888/package.json'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/ec/4159fb5cad0727a65ca4244f4ddd72067bb33edc5fdd2c08a962fa85b1fcc6de60c6a67b9ae75911b3b2793d4e75e2892bed25460ab8d8b08cfb4c12857908' -> '/drone/src/node_modules/.pnpm/@alicloud+gateway-spi@0.0.8/node_modules/@alicloud/_tmp_17_c877296a93bc0def7f9ad1d3830f201e/dist/client.js'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/1d/0688424f69c0e7322aeb720e4e28d9af3b5a7a2dc18b8b198156e377a61a6e05bc824528fca0f8e61ac39b137a028029ff82e5229ad400a3cc22e2bdb687ad-exec' -> '/drone/src/node_modules/.pnpm/@types+xml2js@0.4.11/node_modules/@types/_tmp_17_f1917fdbc3a56d66ecf594e6bba4ca8f/LICENSE'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/e6/c10a776d824dce24fce665809ffeeea3c1b29313ccca04dd2cd66ab6b8e20d8e104c5664e98308751e211d499995b345d35a783741281f9eabf00d144afbe7' -> '/drone/src/node_modules/.pnpm/kitx@2.1.0/node_modules/_tmp_17_0db23d33e0660d104bb8ca156958f048/LICENSE'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/0a/9133dd1c4e4f1ffa3bb5b14f1744c64b486591f4b2f65d19e31ceb179399e98575d6d782ca8f6b78e5b2426147711fa9e8d6a80688c7fc2ff3c21461b1d8cd' -> '/drone/src/node_modules/.pnpm/@alicloud+tea-util@1.4.4/node_modules/@alicloud/_tmp_17_00b48df47af8318e5e6daffa6ebf35fc/dist/client.js.map'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/83/0acea94893c8418a33ea4aa46d09780c1df79e624ddac76d6847c0afce527c224db2b95463187c9f6813dd8b4ff32f7d292891c98bfb3ee0a433dea9427219' -> '/drone/src/node_modules/.pnpm/httpx@2.2.7/node_modules/_tmp_17_f64e90e1037259e8ea00d53de5a4b5b2/lib/index.js'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/07/6be496555df323b636cfb87c7c78dcf94267564d7a1f377707e82208fce11e776e8925531765ba2872a2499a9d2011c8dd02d894b56371ae95ab40ba2e07b4' -> '/drone/src/node_modules/.pnpm/@alicloud+openapi-util@0.2.9/node_modules/@alicloud/_tmp_17_5d5e915a1f09ec1625cb4a61fdf78b84/dist/client.js'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/34/89ec3783403daa899ec5bd89d8d23a7386ab2cea6243ccccb23d2cd7a69c735f2852d66a6c3571d22a7bf724823173c8c115c4e49b9120331638145e3dc058' -> '/drone/src/node_modules/.pnpm/debug@4.3.4/node_modules/_tmp_17_1b529f11b86a9f7811dfc1439e1aee84/LICENSE'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/43/38395b0e29e3fe8ef46fb5e9dc5a1c39de64835474e57a85dd4bbf6e5ce548ff170e820acf3ce53c521b9e29bd6285ff7681566989ef2d91dfdb79c481e15a' -> '/drone/src/node_modules/.pnpm/@alicloud+tea-xml@0.0.2/node_modules/@alicloud/_tmp_17_7063d184276e6aa23985f0c6796d0c8b/dist/client.js'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/81/16af988d7dab00c346c5a5a62caebbd85121a64f105dc57e12b88f3413cb016799668c1db21fd5ebc42f80c4f5b6d3546b05b7f24904cb15e5a4eca8d61d8c' -> '/drone/src/node_modules/.pnpm/@alicloud+tea-typescript@1.8.0/node_modules/@alicloud/_tmp_17_5db87008face6225624cba3d9576eabd/dist/tea.js'
Falling back to copying packages from store
 WARN  EXDEV: cross-device link not permitted, link '/drone/src/.pnpm-store/v3/files/64/0097be709cf5a80529a780f45b0f96cdab185aa57d907e54793cfb033aa2094fa31915230a2be72deae42c26883f7f092aca93500ec14258f3c14b248fb18e' -> '/drone/src/node_modules/.pnpm/@alicloud+credentials@2.2.3/node_modules/@alicloud/_tmp_17_5b47e77a0234ad8ff4af8a10380578b5/LICENSE'
Falling back to copying packages from store
Progress: resolved 958, reused 0, downloaded 51, added 47
Progress: resolved 958, reused 0, downloaded 88, added 84
Progress: resolved 958, reused 0, downloaded 153, added 150
Progress: resolved 958, reused 0, downloaded 258, added 251
Progress: resolved 958, reused 0, downloaded 338, added 334
Progress: resolved 958, reused 0, downloaded 410, added 407
Progress: resolved 958, reused 0, downloaded 464, added 461
Progress: resolved 958, reused 0, downloaded 525, added 524
Progress: resolved 958, reused 0, downloaded 592, added 592
Progress: resolved 958, reused 0, downloaded 640, added 639
Progress: resolved 958, reused 0, downloaded 701, added 696
Progress: resolved 958, reused 0, downloaded 745, added 744
Progress: resolved 958, reused 0, downloaded 775, added 774
Progress: resolved 958, reused 0, downloaded 835, added 834
Progress: resolved 958, reused 0, downloaded 902, added 899
Progress: resolved 958, reused 0, downloaded 952, added 952
Progress: resolved 958, reused 0, downloaded 954, added 954
Progress: resolved 958, reused 0, downloaded 956, added 955
Progress: resolved 958, reused 0, downloaded 957, added 956
.../bcrypt@5.1.0/node_modules/bcrypt install$ node-pre-gyp install --fallback-to-build
.../node_modules/@midwayjs/cli postinstall$ node ./postinstall
Progress: resolved 958, reused 0, downloaded 958, added 958, done
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp info it worked if it ends with ok
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp info using node-pre-gyp@1.0.10
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp info using node@18.12.0 | linux | x64
.../node_modules/@midwayjs/cli postinstall: [midway] auto install complete
.../node_modules/@midwayjs/cli postinstall: Done
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp info check checked for "/drone/src/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.1.0/bcrypt_lib-v5.1.0-napi-v3-linux-x64-musl.tar.gz
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! install request to https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.1.0/bcrypt_lib-v5.1.0-napi-v3-linux-x64-musl.tar.gz failed, reason: socket hang up 
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.1.0 and node@18.12.0 (node-v108 ABI, musl) (falling back to source compile with node-gyp) 
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp WARN Hit error request to https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.1.0/bcrypt_lib-v5.1.0-napi-v3-linux-x64-musl.tar.gz failed, reason: socket hang up 
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp info it worked if it ends with ok
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp info using node-gyp@9.2.0
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp info using node@18.12.0 | linux | x64
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp info ok 
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp info it worked if it ends with ok
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp info using node-gyp@9.2.0
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp info using node@18.12.0 | linux | x64
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python 
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python Python is not set from command line or npm configuration
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python Python is not set from environment variable PYTHON
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python checking if "python3" can be used
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python - "python3" is not in PATH or produced an error
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python checking if "python" can be used
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python - "python" is not in PATH or produced an error
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python 
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python **********************************************************
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python You need to install the latest version of Python.
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python you can try one of the following options:
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python   (accepted by both node-gyp and npm)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python - Set the environment variable PYTHON
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python - Set the npm configuration variable python:
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python For more information consult the documentation at:
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python **********************************************************
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! find Python 
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! configure error 
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack Error: Could not find any Python installation to use
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:330:47)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:159:21)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:202:16)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:294:16)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack     at exithandler (node:child_process:420:5)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:432:5)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! System Linux 3.10.0-1160.71.1.el7.x86_64
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/drone/src/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/drone/src/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! cwd /drone/src/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! node -v v18.12.0
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! node-gyp -v v9.2.0
.../bcrypt@5.1.0/node_modules/bcrypt install: gyp ERR! not ok 
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! build error 
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/drone/src/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/drone/src/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/drone/src/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.10/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! System Linux 3.10.0-1160.71.1.el7.x86_64
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! command "/usr/local/bin/node" "/drone/src/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.10/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! cwd /drone/src/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! node -v v18.12.0
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! node-pre-gyp -v v1.0.10
.../bcrypt@5.1.0/node_modules/bcrypt install: node-pre-gyp ERR! not ok 
.../bcrypt@5.1.0/node_modules/bcrypt install: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/drone/src/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/drone/src/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
.../bcrypt@5.1.0/node_modules/bcrypt install: Failed
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by waitingsong** [comment]
你装的 py 版本是 2 不是 3 吧
