### ISSUE TITLE
中间件中使用ignore忽略路由无效

### ISSUE THREAD

**Issue by allanming** [midwayjs/midway#2492]
代码
```javascript
ignore(ctx: Context): boolean {
  console.log(ctx.path, '~~~~~~~~~~~~~')
  // return [
  //   '/api/pc/get_user'
  // ].includes(ctx.path);
  return ctx.path === '/api/pc/get_user';
}
```

输出
```shell
2022-11-10 12:26:36,818 INFO 39716 [midway:redis] client connect success
[ Midway ] Auto reload. [change] middleware/auth.middleware.ts
/api/pc/get_user ~~~~~~~~~~~~~
2022-11-10 12:26:48,321 ERROR 39716 [-/::1/-/11ms GET /api/pc/get_user] ResultError: 无效的Token
    at /Users/allan/Work/KidsTodo/KidsTodo-server-new/src/middleware/auth.middleware.ts:17:15
    at fn (/Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_core@3.7.0@@midwayjs/core/dist/service/middlewareService.js:57:36)
    at dispatch (/Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_core@3.7.0@@midwayjs/core/dist/service/middlewareService.js:93:48)
    at /Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_info@3.7.3@@midwayjs/info/dist/middleware/info.middleware.js:35:30
    at dispatch (/Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_core@3.7.0@@midwayjs/core/dist/service/middlewareService.js:93:48)
    at /Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_i18n@3.7.3@@midwayjs/i18n/dist/middleware.js:150:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bodyParser (/Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_koa-bodyparser@4.3.0@koa-bodyparser/index.js:95:5)
    at async session (/Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_session@3.7.3@@midwayjs/session/dist/middleware/session.js:137:17)
    at async /Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_core@3.7.0@@midwayjs/core/dist/baseFramework.js:267:40 {
  code: 10004,
  data: undefined
```

**正常不应该抛出ResultError: 无效的Token**

请问问题出在哪呢？

**Comment by waitingsong** [comment]
试试把 `return ctx.path === '/api/pc/get_user';` 换成 `return true` 看看啥结果

**Comment by allanming** [comment]
```javascript
ignore(ctx: Context): boolean {
  console.log(ctx.path, '~~~~~~~~~~~~~')
  // return [
  //   '/api/pc/get_user'
  // ].includes(ctx.path);
  // return ctx.path === '/api/pc/get_user';
  return true;
}
```

```shell
[ Midway ] Auto reload. [change] middleware/auth.middleware.ts
/api/pc/get_user ~~~~~~~~~~~~~
2022-11-10 13:59:56,269 ERROR 40008 [-/::1/-/15ms GET /api/pc/get_user] ResultError: 无效的Token
    at APIController.getUser (/Users/allan/Work/KidsTodo/KidsTodo-server-new/src/controller/api.controller.ts:23:11)
    at APIController.Clz.<computed> (/Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_core@3.7.0@@midwayjs/core/dist/service/aspectService.js:90:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_core@3.7.0@@midwayjs/core/dist/common/webGenerator.js:42:26
    at async /Users/allan/Work/KidsTodo/KidsTodo-server-new/src/middleware/result.middleware.ts:13:15
    at async /Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_info@3.7.3@@midwayjs/info/dist/middleware/info.middleware.js:35:24
    at async /Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_i18n@3.7.3@@midwayjs/i18n/dist/middleware.js:150:17
    at async bodyParser (/Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_koa-bodyparser@4.3.0@koa-bodyparser/index.js:95:5)
    at async session (/Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_session@3.7.3@@midwayjs/session/dist/middleware/session.js:137:17)
    at async /Users/allan/Work/KidsTodo/KidsTodo-server-new/node_modules/_@midwayjs_core@3.7.0@@midwayjs/core/dist/baseFramework.js:267:40 {
  code: 10004,
  data: null
}
```
没起作用

**Comment by allanming** [comment]
我是自己搞错了，谢谢！
