### ISSUE TITLE
在一体化项目中测试service

### ISSUE THREAD

**Issue by plusl894860970** [midwayjs/midway#2814]
如何在一体化项目中测试service?
以下是我的测试步骤

1. 我在根目录新建了 test/
2. 安装 midway-bin
3. 在packae.json srcipts 中加入 "test": "midway-bin test --ts"
4. 运行 npm test
5. 报错：SyntaxError: Cannot use import statement outside a module

```typescript
import { createApp, close } from '@midwayjs/mock';
import * as assert from 'assert';
import { Framework } from '@midwayjs/koa';
import { InChatroomAutoService } from '../../src/api/service/inChatroomAuto';

describe('test/service/inChatroomAutoService.test.ts', () => {

  it('Reply Matched', async () => {
    // create app
    const app = await createApp<Framework>();

    // 根据依赖注入 class 获取实例（推荐）
    const inChatroomAutoService = await app.getApplicationContext().getAsync<InChatroomAutoService>(InChatroomAutoService);
    const { success } = await inChatroomAutoService.replyMatched('MOCK', '10000')
    assert.ok(success)
    // close app
    await close(app);
  });

});
```

**Comment by czy88840616** [comment]
因为前端大概率开了 esModuleInterop，所以 import * as assert from 'assert'; 这类要写成 import assert from 'assert';

**Comment by plusl894860970** [comment]
问题出现在Service的引用。不在assert库
以下是堆栈信息：
```shell
$ midway-bin test --ts -f test/service/inChatroomAuto.test.ts
/Users/plus/Desktop/workspace/android-auto-server/test/service/inChatroomAuto.test.ts:25
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Module.module._compile (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_egg-bin@4.20.0@egg-bin/lib/espower-typescript.js:37:30)
    at Module.m._compile (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:439:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at require.extensions.<computed> (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:442:12)
    at Object.require.extensions.<computed> [as .ts] (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_egg-bin@4.20.0@egg-bin/lib/espower-typescript.js:39:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at /Users/plus/Desktop/workspace/android-auto-server/node_modules/_mocha@6.2.3@mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_mocha@6.2.3@mocha/lib/mocha.js:331:14)
    at Mocha.run (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_mocha@6.2.3@mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_mocha@6.2.3@mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_mocha@6.2.3@mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_mocha@6.2.3@mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_yargs@13.3.2@yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_yargs@13.3.2@yargs/yargs.js:1096:28)
    at Object.parse (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_yargs@13.3.2@yargs/yargs.js:575:25)
    at Object.exports.main (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_mocha@6.2.3@mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_mocha@6.2.3@mocha/bin/_mocha:10:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
Error: /Users/plus/Desktop/workspace/android-auto-server/node_modules/_mocha@6.2.3@mocha/bin/_mocha --espower,--f=test/service/inChatroomAuto.test.ts,--tscompiler=/Users/plus/Desktop/workspace/android-auto-server/node_modules/_ts-node@7.0.1@ts-node/register/index.js,--egg-ts-helper=/Users/plus/Desktop/workspace/android-auto-server/node_modules/_egg-ts-helper@1.34.7@egg-ts-helper/register.js,--timeout=60000,--exit,--require=/Users/plus/Desktop/workspace/android-auto-server/node_modules/_egg-bin@4.20.0@egg-bin/lib/mocha-clean.js,--require=/Users/plus/Desktop/workspace/android-auto-server/node_modules/_co-mocha@1.2.2@co-mocha/lib/co-mocha.js,--require=/Users/plus/Desktop/workspace/android-auto-server/node_modules/_ts-node@7.0.1@ts-node/register/index.js,--require=/Users/plus/Desktop/workspace/android-auto-server/node_modules/_egg-bin@4.20.0@egg-bin/lib/espower-typescript.js,test/service/inChatroomAuto.test.ts exit with code 1
    at ChildProcess.<anonymous> (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_common-bin@2.9.2@common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  code: 1
}
error Command failed with exit code 1.
```

**Comment by czy88840616** [comment]
这是走到 egg-bin 了吧，这个跟 midway关系不大啊。

**Comment by plusl894860970** [comment]
> 这是走到 egg-bin 了吧，这个跟 midway关系不大啊。
> 
> 你用错包了 -> 用 @midwayjs/cli，而不是 midway-bin 这个包。

感谢。因为hooks没有安装@midwayjs/cli 错误地认为是midway-bin

我安装了@midwayjs/cli后 面临了新的问题，这是版本不匹配的问题吗
```shell
$ midway-bin test --ts -f test/service/inChatroomAuto.test.ts
Testing test/service/inChatroomAuto.test.ts
Test environment found at "/Users/plus/Desktop/workspace/android-auto-server/node_modules/_jest-environment-node@24.9.0@jest-environment-node/build/index.js" does not export a "getVmContext" method, which is mandatory from Jest 27. This method is a replacement for "runScript".

 RUNS  test/service/inChatroomAuto.test.ts




Error! You can try adding the -V parameter for more information output.




Error: /Users/plus/Desktop/workspace/android-auto-server/node_modules/_jest@29.5.0@jest/bin/jest --findRelatedTests,test/service/inChatroomAuto.test.ts,--config=/Users/plus/Desktop/workspace/android-auto-server/node_modules/_@midwayjs_cli-plugin-test@2.0.14@@midwayjs/cli-plugin-test/config/jest.ts.js exit with code 1
    at ChildProcess.<anonymous> (/Users/plus/Desktop/workspace/android-auto-server/node_modules/_@midwayjs_command-core@2.0.14@@midwayjs/command-core/src/utils/fork.ts:32:26)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  code: 1
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by czy88840616** [comment]
这是要设置 jest 环境，https://github.com/midwayjs/midway-boilerplate/blob/master/v3/midway-framework-koa/boilerplate/jest.config.js

**Comment by plusl894860970** [comment]
我根据CHAT GPT给出的分析。
 ```npm install jest-environment-node@^27.0.0 --save-dev```
 虽然成功运行了测试文件。但是还面临很多jest的问题，解决了commonjs的问题，又有前端的问题。。

```shell
Details:

    /Users/plus/Desktop/workspace/android-auto-server/src/views/Home.vue:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){<template>
                                                                                      ^

    SyntaxError: Unexpected token '<'

      1 | import { createRouter, createWebHashHistory } from 'vue-router';
    > 2 | import Home from './views/Home.vue';
        | ^
      3 | import Login from './views/Login.vue';
      4 |
      5 | const routes: any = [

      at Runtime.createScriptFromCode (node_modules/_jest-runtime@29.5.0@jest-runtime/build/index.js:1495:14)
      at Object.<anonymous> (src/router.ts:2:1)
      at Object.<anonymous> (src/main.ts:4:1)
      at DirectoryFileDetector.run (node_modules/@midwayjs/core/dist/common/fileDetector.js:63:33)
      at MidwayContainer.loadDefinitions (node_modules/@midwayjs/core/dist/context/container.js:262:74)
      at MidwayContainer.ready (node_modules/@midwayjs/core/dist/context/container.js:413:14)
      at prepareGlobalApplicationContext (node_modules/@midwayjs/core/dist/setup.js:136:24)
      at initializeGlobalApplicationContext (node_modules/@midwayjs/core/dist/setup.js:16:32)
      at create (node_modules/@midwayjs/mock/dist/creator.js:117:61)
      at createApp (node_modules/@midwayjs/mock/dist/creator.js:151:29)
      at Object.<anonymous> (test/service/inChatroomAuto.test.ts:10:32)
```

很感谢你的回复，放弃了
