### ISSUE TITLE
打包单文件应用错误

### ISSUE THREAD

**Issue by xhlacc** [midwayjs/midway#2855]
打包单文件应用，无法正确执行：

node version :v16.13.0
npm version:8.1.0

警告:
DecoratorManager not singleton and please check @midwayjs/core version by "npm ls @midwayjs/core"
The module may be located in:

错误
2023-04-03 10:28:06,730 ERROR 22452 MidwayInconsistentVersionError: We find a latest dependency package installed, please remove the lock file and use "npm update" to upgrade all dependencies first.
    at RefResolver.resolveAsync (D:\_WorkspaceNodejs\test-midwy\midway-project\build\index.js:4547:23)
    at ManagedResolverFactory.resolveManagedAsync (D:\_WorkspaceNodejs\test-midwy\midway-project\build\index.js:4587:25)
    at ManagedResolverFactory.createAsync (D:\_WorkspaceNodejs\test-midwy\midway-project\build\index.js:4727:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MIDWAY_10013',
  cause: undefined
}

"dependencies": {
    "@midwayjs/bootstrap": "^3.11.1",
    "@midwayjs/cache": "^3.11.1",
    "@midwayjs/core": "^3.11.1",
    "@midwayjs/cross-domain": "^3.11.1",
    "@midwayjs/decorator": "^3.11.1",
    "@midwayjs/info": "^3.11.1",
    "@midwayjs/jwt": "^3.11.1",
    "@midwayjs/koa": "^3.11.1",
    "@midwayjs/logger": "^3.0.0-alpha.43",
    "@midwayjs/typeorm": "^3.11.1",
    "@midwayjs/validate": "^3.11.1",
    "cache-manager-fs-hash": "^1.0.0",
    "ethers": "^6.1.0",
    "lodash": "^4.17.21",
    "mysql2": "^3.2.0",
    "request-ip": "^3.3.0",
    "typeorm": "^0.3.12"
  },

这个怎么处理呢？挺急的

**Comment by czy88840616** [comment]
删依赖，删 lock ，重装

**Comment by xhlacc** [comment]
我自己没有修改bootstrap.js，打扰了，非常感谢
