### ISSUE TITLE
@midwayjs/security没有校验referer

### ISSUE THREAD

**Issue by weijunext** [midwayjs/midway#2916]
* **Node Version**: v16.15.0
* **Midway Version(Decorator/Core)**: ^3.0.0
* **Component Name/Version**: ^3.11.5
* **Platform**: mac
* **Mini Showcase Repository**: https://github.com/weijunext/midway_error_min_project

根据Midway官网配置了config.default.ts
```
  security: {
    csrf: {
      enable: true,
      type: 'referer',
      refererWhiteList: ['baidu.com'],
    },
  },
```
和configuration.ts
```
import * as security from '@midwayjs/security';

…………
@Configuration({
  imports: [
    koa,
    validate,
    security
    {
      component: info,
      enabledEnvironment: ['local'],
    },
  ],
  importConfigs: [join(__dirname, './config')],
})

```
实际项目中，前端有携带referer，但不在白名单内，请求没有因为referer不正确被拦截。

最小复现代码通过postman发送请求，不加referer，请求路径是`http://127.0.0.1:4999/api/get_user?uid=1234`，请求没有因为referer不正确被拦截。

**Comment by czy88840616** [comment]
case的地址进不去啊-。-

**Comment by TsMask** [comment]
- Node Version: v16.15.0
- Midway Version(Decorator/Core): ^3.0.0
- Component Name/Version: ^3.11.6
- Platform: win10

```ts
import { Middleware, IMiddleware } from '@midwayjs/core';
import { NextFunction, Context } from '@midwayjs/koa';

@Middleware()
export class ReportMiddleware implements IMiddleware<Context, NextFunction> {

  resolve() {
    return async (ctx: Context, next: NextFunction) => {
      ctx.security.html(`<script>alert('xss')</script>`);
      await next();
    };
  }

  ignore(ctx: Context): boolean {
    // 下面的路由将忽略此中间件
    return ctx.path === '/'
      || ctx.path === '/api/auth'
      || ctx.path === '/api/login';
  }

  static getName(): string {
    return 'report';
  }
}
```

**过滤提示：**
TypeError > (0 , xss_1.default) is not a function

```json
{"code":500,"msg":"(0 , xss_1.default) is not a function"}
```

**Comment by czy88840616** [comment]
需要完整堆栈。

**Comment by TsMask** [comment]
堆栈信息是直接输出log看的信息吗？

**Comment by TsMask** [comment]
堆栈信息是直接输出log看的信息吗？

**Comment by czy88840616** [comment]
控制台输出的信息，哪个文件的第几行抛出来的错误。

**Comment by TsMask** [comment]
```txt
TypeError: (0 , xss_1.default) is not a function
    at Object.html (D:\Projects\NodeProjects\mask_api_midwayjs\node_modules\@midwayjs\security\dist\middleware\helper.js:18:51)
    at D:\Projects\NodeProjects\mask_api_midwayjs\src\framework\middleware\XssMiddleware.ts:18:33
    at fn (D:\Projects\NodeProjects\mask_api_midwayjs\node_modules\@midwayjs\core\dist\service\middlewareService.js:60:36)
    at dispatch (D:\Projects\NodeProjects\mask_api_midwayjs\node_modules\@midwayjs\core\dist\service\middlewareService.js:99:48)
    at D:\Projects\NodeProjects\mask_api_midwayjs\src\framework\middleware\ReportMiddleware.ts:18:28
    at dispatch (D:\Projects\NodeProjects\mask_api_midwayjs\node_modules\@midwayjs\core\dist\service\middlewareService.js:99:48)
    at XSSProtectionMiddleware.compatibleMiddleware (D:\Projects\NodeProjects\mask_api_midwayjs\node_modules\@midwayjs\security\dist\middleware\xssProtection.js:14:30)
    at D:\Projects\NodeProjects\mask_api_midwayjs\node_modules\@midwayjs\security\dist\middleware\base.js:23:29
    at dispatch (D:\Projects\NodeProjects\mask_api_midwayjs\node_modules\@midwayjs\core\dist\service\middlewareService.js:99:48)
    at XFrameMiddleware.compatibleMiddleware (D:\Projects\NodeProjects\mask_api_midwayjs\node_modules\@midwayjs\security\dist\middleware\xframe.js:15:30)

```
![image](https://github.com/midwayjs/midway/assets/37463159/846e2113-8fcb-49ab-97ac-79a9922dd385)

**Comment by czy88840616** [comment]
像是 xss 包的问题。。。

**Comment by TsMask** [comment]
这个xss包的(0 , xss_1.default) is not a function问题，你那边能处理下吗？

毕竟@midwayjs/security模块里的问题，影响使用的

**Comment by czy88840616** [comment]
我细看一下。

**Comment by TsMask** [comment]
@czy88840616 大佬，关于这个referer的允许请求方法能不能配置参数refererIgnoreMethods

有些时候是接口只对某个站点域名开放，get，optons请求都不允许

版主 @weijunext ，他请求接口应该是get的请求，所以通过refere没r拦截下来

![image](https://github.com/midwayjs/midway/assets/37463159/08ee5486-c298-476f-b738-bafbdb048df0)

**Comment by czy88840616** [comment]
先处理问题，再处理需求。

**Comment by czy88840616** [comment]
@TsMask 需求单独提一个。
