### ISSUE TITLE
无法运行jest测试，一运行测试就报错误

### ISSUE THREAD

**Issue by aquajansi2018** [midwayjs/midway#2924]
* **Node Version**:16.19.1
* **Midway Version(Decorator/Core)**:^3.0.0
* **Component Name/Version**:
* **Platform**:macos
* **Mini Showcase Repository**:

做了一个小的网关转发项目，运行不了jest测试，运行测试，就报如下错误：
Error: Can not get main framework, please check your configuration.ts.

    at create (/Volumes/File/aquainc/zz/backend/src/zz-gw/node_modules/@midwayjs/mock/dist/creator.js:137:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createApp (/Volumes/File/aquainc/zz/backend/src/zz-gw/node_modules/@midwayjs/mock/dist/creator.js:151:23)
    at Object.<anonymous> (/Volumes/File/aquainc/zz/backend/src/zz-gw/test/controller/index.test.ts:6:21)

我已经把项目代码上传，辛苦大家帮我看看是什么问题？
[zz-gw.zip](https://github.com/midwayjs/midway/files/11357877/zz-gw.zip)

**Comment by czy88840616** [comment]
看了下是 http-proxy 中的 axios 执行到 esm 报错导致的，细节我要看看为啥。

**Comment by czy88840616** [comment]
原因：项目jest未升级到 29，导致执行到新版本 axios 出错。

参考脚手架更新：https://github.com/midwayjs/midway-boilerplate/blob/master/v3/midway-framework-koa/boilerplate/_package.json#L22

主要是更新 jest/ts-jest/@types/jest和typesccript
