### ISSUE TITLE
midway2升级3之后build报错 Interface 'Context<ResponseBodyT>' incorrectly extends interface 'Context'. ()

### ISSUE THREAD

**Issue by pigLoveRabbit520** [midwayjs/midway#2927]
错误信息
```
Error:
[TS Error] Interface 'Context<ResponseBodyT>' incorrectly extends interface 'Context'. ()
    at Object.error (/usr/src/app/node_modules/@midwayjs/cli/src/index.ts:62:13)
    at BuildPlugin.compile (/usr/src/app/node_modules/@midwayjs/cli-plugin-build/src/index.ts:168:23)
    at CommandCore.execLifecycle (/usr/src/app/node_modules/@midwayjs/command-core/src/core.ts:227:11)
    at CommandCore.invoke (/usr/src/app/node_modules/@midwayjs/command-core/src/core.ts:187:5)
    at CLI.start (/usr/src/app/node_modules/@midwayjs/command-core/src/cli.ts:191:5)
```
这是我midway依赖
```
├── @midwayjs/bootstrap@3.11.6    
├── @midwayjs/cli@2.0.15
├── @midwayjs/core@3.11.6
├── @midwayjs/decorator@3.11.6    
├── @midwayjs/egg-ts-helper@1.2.1 
├── @midwayjs/logger@2.17.0       
├── @midwayjs/mock@3.11.6
├── @midwayjs/redis@3.11.6        
├── @midwayjs/validate@3.11.6     
├── @midwayjs/web@3.11.6
```

* **Node Version**: v18.12.1
* **Midway Version(Decorator/Core)**: 3.11.6
* **Component Name/Version**: 
* **Platform**: ubuntu18
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
context 的定义不对吧，ctx.body 好像是个泛型，可以any一下。

**Comment by pigLoveRabbit520** [comment]
现在midway3如何向context里定义扩展方法呢？好像是这个问题导致的

**Comment by czy88840616** [comment]
参考https://midwayjs.org/docs/context_definition，注意几点

1、context 类型使用 `import { Context } from '@midwayjs/web';`，而不是 from 'egg'
2、在 interface 定义 ctx 上的属性类型，比如 body

```ts
import '@midwayjs/core';

declare module '@midwayjs/core' {
  interface Context {
    body: {
      a: number;
    }
  }
}
```

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/extensions/egg#%E6%89%A9%E5%B1%95-applicationcontextrequestresponse

**Comment by pigLoveRabbit520** [comment]
那个是egg的方式，不太想用egg的方式了，emm，不过现在有新的报错了：
```
Error:
[TS Error] Interface 'Context<ResponseBodyT>' cannot simultaneously extend types 'Context' and 'Context'. ()
    at Object.error (/usr/src/app/node_modules/@midwayjs/cli/src/index.ts:62:13)
    at BuildPlugin.compile (/usr/src/app/node_modules/@midwayjs/cli-plugin-build/src/index.ts:168:23)
    at CommandCore.execLifecycle (/usr/src/app/node_modules/@midwayjs/command-core/src/core.ts:227:11)
    at CommandCore.invoke (/usr/src/app/node_modules/@midwayjs/command-core/src/core.ts:187:5)
    at CLI.start (/usr/src/app/node_modules/@midwayjs/command-core/src/cli.ts:191:5)
```
好奇怪

**Comment by czy88840616** [comment]
midway并不建议往 ctx 上扩展，所以并未提供这类能力，如果硬要挂的话，在egg下要么用egg原有方式，要么app.context.xxx 。

**Comment by czy88840616** [comment]
> 

我build 并未出现问题，看看是不是使用了 "@midwayjs/cli": "^2.0.0",

**Comment by pigLoveRabbit520** [comment]
版本是这个 @midwayjs/cli@2.0.15
```
Error:
[TS Error] Interface 'Context<ResponseBodyT>' cannot simultaneously extend types 'Context' and 'Context'. ()
    at Object.error (/usr/src/app/node_modules/@midwayjs/cli/src/index.ts:62:13)
    at BuildPlugin.compile (/usr/src/app/node_modules/@midwayjs/cli-plugin-build/src/index.ts:168:23)
    at CommandCore.execLifecycle (/usr/src/app/node_modules/@midwayjs/command-core/src/core.ts:227:11)
    at CommandCore.invoke (/usr/src/app/node_modules/@midwayjs/command-core/src/core.ts:187:5)
    at CLI.start (/usr/src/app/node_modules/@midwayjs/command-core/src/cli.ts:191:5)
```

**Comment by czy88840616** [comment]
光这样看不出了，需要复现示例了。

**Comment by czy88840616** [comment]
对了，tsconfig.json 记得加个 skipLibCheck: true

**Comment by pigLoveRabbit520** [comment]
现在yarn build报错：
```
Error: 
[TS Error] Interface 'MidwayConfig' incorrectly extends interface 'PowerPartial<EggAppConfig>'. ()
```
但我现在代码里都没搜到`PowerPartial<EggAppConfig>`，好奇怪

**Comment by pigLoveRabbit520** [comment]
加上`skipLibCheck: true`可以了

**Comment by czy88840616** [comment]
MidwayConfig 是 midway 提供的配置定义，在 @midwayjs/web 中会和 EggAppConfig 进行合并，而 EggAppConfig 又依赖了 egg 自己生成的的 typings 目录。

最好还是新建一个 v3 的 egg 项目，核对一下 tsconfig/ets/typings，以及各个文件的定义写法。
