### ISSUE TITLE
serverless  npm run deploy 示例项目到阿里云报错，腾讯云正常

### ISSUE THREAD

**Issue by hisunny520** [midwayjs/midway#2941]
serverless 示例项目 npm run deploy 阿里云报错

TypeError: Cannot read property 'salt' of undefined
    at Object.decrypt (E:\Projects\vue-admin\my_midway_app\node_modules\crypto-js\cipher-core.js:876:102)
    at Object.decrypt (E:\Projects\vue-admin\my_midway_app\node_modules\crypto-js\cipher-core.js:205:59)
    at AliyunFCPlugin.deployUseServerlessDev (E:\Projects\vue-admin\my_midway_app\node_modules\@midwayjs\fcli-plugin-fc\src\index.ts:211:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CommandCore.execLifecycle (E:\Projects\vue-admin\my_midway_app\node_modules\@midwayjs\command-core\src\core.ts:216:11)
    at CommandCore.invoke (E:\Projects\vue-admin\my_midway_app\node_modules\@midwayjs\command-core\src\core.ts:182:5)
    at CLI.start (E:\Projects\vue-admin\my_midway_app\node_modules\@midwayjs\command-core\src\cli.ts:191:5)

//  package.json 

 "dependencies": {
    "@midwayjs/core": "^3.0.0",
    "@midwayjs/decorator": "^3.0.0",
    "@midwayjs/faas": "^3.0.0"
    },
  "devDependencies": {
    "@midwayjs/cli": "^1.3.16",
    "@midwayjs/cli-plugin-faas": "^1.2.90",
    "@midwayjs/fcli-plugin-fc": "^1.2.90",
    "@midwayjs/mock": "^3.0.0",
    "@midwayjs/serverless-app": "^3.0.2",
    "@midwayjs/serverless-fc-starter": "^3.0.2",
    "@midwayjs/serverless-fc-trigger": "^3.0.2",
    "@midwayjs/serverless-scf-starter": "^3.4.0",
    "@midwayjs/serverless-scf-trigger": "^3.4.3",
    "@types/jest": "^29.2.0",
    "@types/node": "14",
    "cross-env": "^6.0.0",
    "jest": "^29.2.2",
    "mwts": "^1.0.5",
    "ts-jest": "^29.0.3",
    "typescript": "~4.8.0"
  }

**Comment by czy88840616** [comment]
像是没读到 ak，可以先 reset 重新配置下。

**Comment by hisunny520** [comment]
> 像是没读到 ak，可以先 reset 重新配置下。

到不了配置就报错了
