### ISSUE TITLE
单文件构建正常，启动失败

### ISSUE THREAD

**Issue by CYJ-zZ** [midwayjs/midway#2969]
执行命令：npm run bundle_start

报错信息如下：
> my-midway-project@1.0.0 bundle_start
> NODE_ENV=production node ./build/index.js

DecoratorManager not singleton and please check @midwayjs/core version by "npm ls @midwayjs/core"
The module may be located in:
1. 
2023-05-17 16:04:37,106 ERROR 12758 MidwayInconsistentVersionError: We find a latest dependency package installed, please remove the lock file and use "npm update" to upgrade all dependencies first.
    at RefResolver.resolveAsync (/Users/rika/exandsDevProjects/send-message/EIG-Multicast/build/index.js:4555:23)
    at ManagedResolverFactory.resolveManagedAsync (/Users/rika/exandsDevProjects/send-message/EIG-Multicast/build/index.js:4595:25)
    at ManagedResolverFactory.createAsync (/Users/rika/exandsDevProjects/send-message/EIG-Multicast/build/index.js:4735:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'MIDWAY_10013',
  cause: undefined
}
2023-05-17 16:04:37,108 INFO 12758 [midway:bootstrap] exit with code:1

core信息：
npm ls @midwayjs/core
my-midway-project@1.0.0 
├── @midwayjs/core@3.11.6
├─┬ @midwayjs/decorator@3.11.6
│ └── @midwayjs/core@3.11.6 deduped
└─┬ @midwayjs/koa@3.11.6
  └── @midwayjs/core@3.11.6 deduped

已经删除.lock文件，npm update过了依旧报错

**Comment by pstruggle** [comment]
有解决问题吗

**Comment by czy88840616** [comment]
实际肯定有多个 @midwayjs/core 包，需要查找一下。
