### ISSUE TITLE
faas-V3 默认模版项目部署出错

### ISSUE THREAD

**Issue by gopkg-dev** [midwayjs/midway#3056]
<img width="794" alt="image" src="https://github.com/midwayjs/midway/assets/58848833/06eb870c-fad6-41ee-8698-8fdae1a50a3f">

```
{
    "errorMessage": "(0 , core_1.Config) is not a function",
    "errorType": "TypeError",
    "stackTrace": [
        "TypeError: (0 , core_1.Config) is not a function",
        "    at (/code/node_modules/.pnpm/@midwayjs+tablestore@3.11.6/node_modules/@midwayjs/tablestore/dist/manager.js:27:23)",
        "    at Module._compile (internal/modules/cjs/loader.js:1086:14)",
        "    at Module._extensions..js (internal/modules/cjs/loader.js:1115:10)",
        "    at Module.load (internal/modules/cjs/loader.js:951:32)",
        "    at Module._load (internal/modules/cjs/loader.js:791:12)",
        "    at Module.require (internal/modules/cjs/loader.js:975:19)",
        "    at require (internal/modules/cjs/helpers.js:93:18)",
        "    at (/code/node_modules/.pnpm/@midwayjs+tablestore@3.11.6/node_modules/@midwayjs/tablestore/dist/configuration.js:11:19)",
        "    at Module._compile (internal/modules/cjs/loader.js:1086:14)",
        "    at Module._extensions..js (internal/modules/cjs/loader.js:1115:10)"
    ]
}
```

**Comment by czy88840616** [comment]
如文档所示，一般是使用了低版本的 core（一般是锁的问题），https://midwayjs.org/blog/core-decorator-merge
