### ISSUE TITLE
midwayjs v3框架 用bull任务队列  出现 ReplyError: EXECABORT Transaction discarded because of previous errors问题

### ISSUE THREAD

**Issue by mynamexjl** [midwayjs/midway#3063]
队列场景有： 一个拉取页面队列     一个是下载页面的资源队列。一个上传到oss队列   redis类型是
![8BAD723D-2F1B-4D87-B690-0092FF7D3154](https://github.com/midwayjs/midway/assets/25628679/e94ef23d-e4e7-469c-abdc-f20f72c25f3c)
会出现底下错误： 2023-07-06 18:27:59,276 ERROR 34340 [2 PullRepoProcessor}] ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
    at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
  command: { name: 'exec', args: [] },
  previousErrors: [
    ReplyError: ERR 'EVAL' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/autosdk-server/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    }
  ]
}

**Comment by mynamexjl** [comment]
bull 配置也配置。      prefix: '{bull:task}',

**Comment by czy88840616** [comment]
要用集群？https://midway.alibaba-inc.com/docs/extensions/bull#redis-%E9%9B%86%E7%BE%A4

**Comment by mynamexjl** [comment]
不是  只是redis的类型是集群的
我这边也只有一个host 和指定端口和密码

按照文档集群的写法 我的 new Redis.Cluster([
  {
    port: 7000,
    host: '127.0.0.1',
    password:'xxx'   // 这边会提示没有password 属性
  },
], clusterOptions);

像我这种情况 是不是就是  拿集群类型的redis 当单例redis使用了
像这种  我该如何解决哈～

**Comment by czy88840616** [comment]
像我这种情况 是不是就是 拿集群类型的redis 当单例redis使用了 > 是的

这个问题我理解跟你的 redis 有点关系，但是我不在环境里无法复现，我们也没有出现这个错误的报告，所以我也无法排查。

**Comment by mynamexjl** [comment]
![image](https://github.com/midwayjs/midway/assets/25628679/0e5570c4-66a5-4226-99b8-096cea753797)
那如果我按文档集群的方式来使用。  我的redis密码是要在哪写入呢

**Comment by mynamexjl** [comment]
能发下您的邮箱嘛。 这边提供下demo。 好方便帮忙排查下问题。 或者可否加个好友

**Comment by mynamexjl** [comment]
[redis-err-demo.zip](https://github.com/midwayjs/midway/files/11979130/redis-err-demo.zip)
------------------------deom 安装启动后 请求 api http://127.0.0.1:7001/ws/autosdk/yq/test 可复现问题   代码在 /controller/document 和 /service/document。bull 队列在 /queue 文件下       报错：                   2023-07-07 15:33:29,444 ERROR 46116 [14 PullRepoProcessor}] ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
    at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
  command: { name: 'exec', args: [] },
  previousErrors: [
    ReplyError: ERR 'EVAL' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    },
    ReplyError: ERR 'EVALSHA' inside MULTI is not allowed
        at parseError (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
        at parseType (/Users/xiejianlin/Desktop/redis-err-demo/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
      command: [Object]
    }
  ]
} -------------------------------像这种情况可有办法解决

**Comment by czy88840616** [comment]
错误我能复现，大概查到了问题，原因为：

- 1、报错为调用了队列的 addBulk 方法，其中执行了 redis 的 mulit.exec，传递了 lua 脚本到服务端，但是服务端执行报错
- 2、阿里云 redis 是魔改版，不支持或者弱支持脚本执行（原因为社区正常的 redis 没有这行报错，已经请redis客户端人员定位过了）
- 3、我使用本地 docker 启动的 redis，能正常运行，没有报错

所以结论基本上明确是阿里云 redis 服务端的问题。

解决方案可能是：

- 1、咨询阿里云的 redis 人员，看是否能升级 https://help.aliyun.com/document_detail/56450.html?spm=a2c4g.468969.0.0.2518654cb5TSMg#concept-itn-f44-tdb
- 2、看是否绕过，不用 addBulk 方法

**Comment by mynamexjl** [comment]
👌。 谢谢。
