### ISSUE TITLE
如何打包单文件把环境变量也进行打包

### ISSUE THREAD

**Issue by rjl-cli** [midwayjs/midway#3096]
目前是 
  "scripts": {
    "dev": "cross-env NODE_ENV=local midway-bin dev --ts",
    "build": "bundle && midway-bin build -c && ncc build bootstrap.js -o build",
    "start": "cross-env NODE_ENV=production node ./build/index.js",
    "beta": "cross-env NODE_ENV=beta node ./build/index.js"
  },
  
  
 希望可以
 cross-env NODE_ENV=production && bundle && midway-bin build -c && ncc build bootstrap.js -o build
 直接  node ./build/index.js
  但是
  PS C:\Users\renjiali\Desktop\测试\midway\build> node index.js
2023-07-21 13:51:51,961 ERROR 16044 MidwayConfigMissingError: Can't found config key "config.keys" in your config, please set it first
    at MidwayKoaFramework.applicationInitialize (C:\Users\renjiali\Desktop\测试\midway\build\index.js:26966:19)
    at MidwayKoaFramework.initialize (C:\Users\renjiali\Desktop\测试\midway\build\index.js:14464:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MidwayFrameworkService.init (C:\Users\renjiali\Desktop\测试\midway\build\index.js:20939:21)
    at async ObjectCreator.doInitAsync (C:\Users\renjiali\Desktop\测试\midway\build\index.js:19264:17)
    at async ManagedResolverFactory.createAsync (C:\Users\renjiali\Desktop\测试\midway\build\index.js:16892:9)
    at async initializeGlobalApplicationContext (C:\Users\renjiali\Desktop\测试\midway\build\index.js:22623:5)
    at async BootstrapStarter.init (C:\Users\renjiali\Desktop\测试\midway\build\index.js:5176:35)
    at async BootstrapStarter.run (C:\Users\renjiali\Desktop\测试\midway\build\index.js:5183:35) {
  code: 'MIDWAY_10006',
  cause: undefined
}

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/deployment#%E4%BB%A3%E7%A0%81%E8%B0%83%E6%95%B4

**Comment by rjl-cli** [comment]
> https://midwayjs.org/docs/deployment#%E4%BB%A3%E7%A0%81%E8%B0%83%E6%95%B4

请看问题，谢谢！文档我比你会看，请你认真查阅文档和阅读我提出的问题

**Comment by czy88840616** [comment]
你的报错不就是配置没读到么，配置没读到不就是因为配置没改成对象模式？

**Comment by rjl-cli** [comment]
> https://midwayjs.org/docs/deployment#%E4%BB%A3%E7%A0%81%E8%B0%83%E6%95%B4

文档打包是需要依赖环境变量的，需要传入环境变量，我的要求是 build:start 就是生产的  ，build:beta就是测试的

**Comment by rjl-cli** [comment]
![image](https://github.com/midwayjs/midway/assets/111716113/42e62fe5-77b5-42e2-a6cb-fa29453c3136)
我再说一下 文档没有 且修改了！！！   没问题可以启动
但是依赖于cross-env ，我的意思是不要这个  打包的时候代入

**Comment by rjl-cli** [comment]
> 我再说一下 文档没有 且修改了！！！ 没问题可以启动
> 但是依赖于cross-env ，我的意思是不要这个 打包的时候代入

我再说一下 文档没有写打包带入指定的环境变量     且修改了！！！ 没问题可以启动 但是依赖于cross-env ，我的意思是不要这个 打包的时候代入

**Comment by czy88840616** [comment]
框架没有这种功能，你可以自行引入 dovenv 处理。
