### ISSUE TITLE
v2 升级v3 遇到的问题： ERROR 18176 nodejs.TypeError: (0 , decorator_1.isClass) is not a function ？

### ISSUE THREAD

**Issue by pigLoveRabbit520** [midwayjs/midway#3158]
```
2023-08-11 11:37:47,973 ERROR 18176 nodejs.TypeError: (0 , decorator_1.isClass) is not a function
    at ContainerConfiguration.getConfigurationExport (D:\happy-admin\node_modules\@midwayjs\koa\node_modules\@midwayjs\core\dist\context\configuration.js:287:37)
    at ContainerConfiguration.loadConfiguration (D:\happy-admin\node_modules\@midwayjs\koa\node_modules\@midwayjs\core\dist\context\configuration.js:180:47)
    at ContainerConfiguration.load (D:\happy-admin\node_modules\@midwayjs\koa\node_modules\@midwayjs\core\dist\context\configuration.js:157:14)
    at MidwayContainer.load (D:\happy-admin\node_modules\@midwayjs\koa\node_modules\@midwayjs\core\dist\context\midwayContainer.js:85:23)
    at MidwayWebFramework.containerDirectoryLoad (D:\happy-admin\node_modules\@midwayjs\koa\node_modules\@midwayjs\core\dist\baseFramework.js:137:33)
    at MidwayWebFramework.initialize (D:\happy-admin\node_modules\midway\node_modules\@midwayjs\web\dist\framework\web.js:73:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebBootstrapStarter.init (D:\happy-admin\node_modules\midway\node_modules\@midwayjs\web\dist\starter.js:13:9)
    at async D:\happy-admin\node_modules\midway\node_modules\@midwayjs\web\dist\base.js:232:17
```
这是我的依赖
```
"dependencies": {
    "@alicloud/pop-core": "^1.7.10",
    "@grpc/grpc-js": "^1.2.0",
    "@grpc/proto-loader": "^0.5.0",
    "@midwayjs/bootstrap": "^3.0.0",
    "@midwayjs/core": "^3.0.0",
    "@midwayjs/decorator": "^3.0.0",
    "@midwayjs/validate": "^3.0.0",
    "@midwayjs/web": "^3.0.0",
    "@midwayjs/cron": "3.11.15",
    "@midwayjs/bull": "3.11.15",
    "amqplib": "^0.10.0",
    "bcryptjs": "^2.4.3",
    "co-wechat-api-new": "^3.12.0",
    "dayjs": "^1.9.6",
    "decimal.js": "^10.2.1",
    "egg": "^2.31.0",
    "egg-redis": "^2.4.0",
    "egg-scripts": "^2.15.1",
    "egg-view-ejs": "^2.0.1",
    "got": "^11.8.1",
    "injection": "^1.8.6",
    "ldapjs": "^2.3.1",
    "ldapts": "^3.1.0",
    "lodash": "^4.17.20",
    "midway": "^2.6.10",
    "mysql2": "^2.2.5",
    "node-fetch": "^2",
    "path-to-regexp": "^6.2.0",
    "pinyin-no-jieba": "^2.8.3",
    "qiniu": "^7.3.2",
    "redlock": "^4.2.0",
    "reflect-metadata": "^0.1.13",
    "request": "^2.88.2",
    "request-promise": "^4.2.6",
    "sequelize": "^5.22.0",
    "sequelize-typescript": "^1.1.0",
    "stripe": "^12.4.0",
    "svg-captcha": "^1.4.0",
    "tsconfig-paths": "^3.9.0",
    "uniqid": "^5.3.0"
  },
```
框架的版本应该都是一致的
```
├── @midwayjs/bootstrap@3.11.15
├── @midwayjs/bull@3.11.15
├── @midwayjs/cli@2.1.1
├── @midwayjs/core@3.11.15
├── @midwayjs/cron@3.11.15
├── @midwayjs/decorator@3.11.15
├── @midwayjs/egg-ts-helper@1.2.1
├── @midwayjs/mock@3.11.15
├── @midwayjs/validate@3.11.15
├── @midwayjs/web@3.11.15
```
这是啥原因呢？
* **Node Version**: v18.17.1
* **Midway Version(Decorator/Core)**: 3.11.15
* **Component Name/Version**:
* **Platform**: windows
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
npx midway-version -u

**Comment by pigLoveRabbit520** [comment]
npx midway-version 报错了
```
D:\happy-admin\node_modules\midway-version\index.js:138
      if (versions[pkgName].some((v) => satisfies(version, v))) {
                            ^

TypeError: versions[pkgName].some is not a function
```

**Comment by pigLoveRabbit520** [comment]
@czy88840616  npx midway-version的问题我改了下代码就好了，
```
>> Start to check your midway component version...

✓ @midwayjs/faas-typings(not installed)
✓ @midwayjs/fc-starter(not installed)
✓ @midwayjs/serverless-http-parser(not installed)
✓ @midwayjs/async-hooks-context-manager(3.11.15) 
✓ @midwayjs/axios(not installed)
✓ @midwayjs/bootstrap(3.11.15)
✓ @midwayjs/bull(3.11.15)
✓ @midwayjs/bull-board(not installed)
✓ @midwayjs/cache(not installed)
✓ @midwayjs/captcha(not installed)
✓ @midwayjs/casbin(not installed)
✓ @midwayjs/casbin-redis-adapter(not installed)  
✓ @midwayjs/casbin-typeorm-adapter(not installed)
✓ @midwayjs/code-dye(not installed)
✓ @midwayjs/consul(not installed)
✓ @midwayjs/core(3.11.15)
✓ @midwayjs/cos(not installed)
✓ @midwayjs/cron(3.11.15)
✓ @midwayjs/cross-domain(not installed)
✓ @midwayjs/decorator(3.11.15)
✓ @midwayjs/etcd(not installed)
✓ @midwayjs/express-session(not installed)
✓ @midwayjs/faas(not installed)
✓ @midwayjs/grpc(not installed)
✓ @midwayjs/http-proxy(not installed)
✓ @midwayjs/i18n(3.11.15)
✓ @midwayjs/info(not installed)
✓ @midwayjs/jwt(not installed)
✓ @midwayjs/kafka(not installed)
✓ @midwayjs/mikro(not installed)
✓ @midwayjs/mock(3.11.15)
✓ @midwayjs/mongoose(not installed)
✓ @midwayjs/oss(not installed)
✓ @midwayjs/otel(not installed)
✓ @midwayjs/passport(not installed)
✓ @midwayjs/process-agent(not installed)
✓ @midwayjs/prometheus(not installed)
✓ @midwayjs/prometheus-socket-io(not installed)
✓ @midwayjs/rabbitmq(not installed)
✓ @midwayjs/redis(not installed)
✓ @midwayjs/security(not installed)
✓ @midwayjs/sequelize(not installed)
✓ @midwayjs/session(not installed)
✓ @midwayjs/socketio(not installed)
✓ @midwayjs/static-file(not installed)
✓ @midwayjs/swagger(not installed)
✓ @midwayjs/tablestore(not installed)
✓ @midwayjs/tags(not installed)
✓ @midwayjs/typegoose(not installed)
✓ @midwayjs/typeorm(not installed)
✓ @midwayjs/upload(not installed)
✓ @midwayjs/validate(3.11.15)
✓ @midwayjs/version(3.11.18)
✓ @midwayjs/view(not installed)
✓ @midwayjs/view-ejs(not installed)
✓ @midwayjs/view-nunjucks(not installed)
✓ @midwayjs/web(3.11.15)
✓ @midwayjs/express(not installed)
✖ @midwayjs/koa(current: 2.14.6, allow: "3.11.15")
✓ @midwayjs/ws(not installed)
**************************************************
>> Check complete, found 1 problem.
>> Please check the result above.
**************************************************
```

`@midwayjs/koa`应该不是问题吧，我之前也有个项目升级了v3，`npx midway-version`检查也是这个问题，但是能启动起来的。

**Comment by czy88840616** [comment]
当然是了。。

**Comment by pigLoveRabbit520** [comment]
我看了下，是`"midway": "^2.6.10"` ，应该是这个依赖的问题。

**Comment by czy88840616** [comment]
不需要这个依赖。

**Comment by czy88840616** [comment]
"injection": "^1.8.6", 这个也不需要
