### ISSUE TITLE
npm run dev 运行时出现错误

### ISSUE THREAD

**Issue by Aqincheng** [midwayjs/midway#321]
PS C:\Users\Administrator\Desktop\5555\htetypescript> npm run dev

> htetypescript@1.0.0 dev C:\Users\Administrator\Desktop\5555\htetypescript
> cross-env NODE_ENV=local midway-bin dev --ts --sticky

[egg-bin] server port 7001 is in use, now using port 7002

2019-08-14 16:34:56,686 INFO 416 [master] =================== midway start =====================
2019-08-14 16:34:56,689 INFO 416 [master] node version v10.15.0
2019-08-14 16:34:56,690 INFO 416 [master] midway version 1.11.1
2019-08-14 16:34:56,690 INFO 416 [master] start with options: {"framework":"C:\\Users\\Administrator\\Desktop\\5555\\htetypescript\\node_modules\\midway","baseDir":"C:\\Users\\Administrator\\Desktop\\5555\\htetypescript","port":7002,"workers":1,"plugins":null,"https":false,"typescript":true,"sticky":true}
2019-08-14 16:34:56,691 INFO 416 [master] start with env: isProduction: false, EGG_SERVER_ENV: undefined, NODE_ENV: local
2019-08-14 16:34:56,694 INFO 416 [master] egg version 2.23.0, egg-core version 4.17.3
2019-08-14 16:34:56,711 INFO 416 [master] agent_worker#1:3840 start with clusterPort:63119
2019-08-14 16:34:59,188 INFO 416 [master] agent_worker#1:3840 started (2491ms)
2019-08-14 16:34:59,189 INFO 416 [master] start appWorker with args ["{\"framework\":\"C:\\\\Users\\\\Administrator\\\\Desktop\\\\5555\\\\htetypescript\\\\node_modules\\\\midway\",\"baseDir\":\"C:\\\\Users\\\\Administrator\\\\Desktop\\\\5555\\\\htetypescript\",\"port\":7002,\"workers\":1,\"plugins\":null,\"https\":false,\"typescript\":true,\"sticky\":true,\"clusterPort\":63119,\"stickyWorkerPort\":63120}"]
2019-08-14 16:34:59,202 INFO 416 [master] app_worker#1:5416 start, state: none, current workers: ["1"]
2019-08-14 16:35:01,989 ERROR 5416 [-/127.0.0.1/-/1ms GET /] nodejs.TypeError: Cannot read property 'prototype' of undefined
    at generateAPIFunc (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:190:22)
    at getTag_Path (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:115:18)
    at buildDocument (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:50:14)
    at documentInit (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:497:7)
    at module.exports.swaggerInit.app (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\index.js:10:3)
    at app.beforeStart (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\app.js:8:5)
    at Object.callFn (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-core\lib\utils\index.js:44:42)
    at process.nextTick (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-core\lib\lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

pid: 5416
hostname: USER-20190118FU

2019-08-14 16:35:01,991 ERROR 5416 nodejs.TypeError: Cannot read property 'prototype' of undefined
    at generateAPIFunc (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:190:22)
    at getTag_Path (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:115:18)
    at buildDocument (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:50:14)
    at documentInit (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:497:7)
    at module.exports.swaggerInit.app (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\index.js:10:3)
    at app.beforeStart (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\app.js:8:5)
    at Object.callFn (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-core\lib\utils\index.js:44:42)
    at process.nextTick (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-core\lib\lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

pid: 5416
hostname: USER-20190118FU

2019-08-14 16:35:01,993 ERROR 5416 [app_worker] start error, exiting with code:1
[2019-08-14 16:35:01.997] [cfork:master:416] worker:5416 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2019-08-14 16:35:01.998] [cfork:master:416] don't fork, because worker:5416 will be kill soon
2019-08-14 16:35:01,998 INFO 416 [master] app_worker#1:5416 disconnect, suicide: false, state: disconnected, current workers: ["1"]
2019-08-14 16:35:01,998 ERROR 3840 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 3840
hostname: USER-20190118FU

[2019-08-14 16:35:02.009] [cfork:master:416] worker:5416 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2019-08-14 16:35:02,014 ERROR 416 nodejs.AppWorkerDiedError: [master] app_worker#1:5416 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-cluster\lib\master.js:510:21)
    at Master.emit (events.js:182:13)
    at Messenger.sendToMaster (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.cluster.on (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-cluster\lib\master.js:353:22)
    at EventEmitter.emit (events.js:187:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:193:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
name: "AppWorkerDiedError"
pid: 416
hostname: USER-20190118FU

2019-08-14 16:35:02,015 ERROR 416 [master] app_worker#1:5416 start fail, exiting with code:1
2019-08-14 16:35:02,016 ERROR 416 [master] exit with code:1
{ Error: C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\midway-bin\node_modules\egg-bin\lib\start-cluster {"typescript":true,"sticky":true,"workers":1,"framework":"C:\\Users\\Administrator\\Desktop\\5555\\htetypescript\\node_modules\\midway","baseDir":"C:\\Users\\Administrator\\Desktop\\5555\\htetypescript","port":7002} exit with code 1
    at ChildProcess.proc.once.code (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12) code: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! htetypescript@1.0.0 dev: `cross-env NODE_ENV=local midway-bin dev --ts --sticky`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the htetypescript@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-08-14T08_35_02_073Z-debug.log

**Comment by czy88840616** [comment]
插件挂了，提个 demo？

**Comment by Aqincheng** [comment]
> 插件挂了，提个 demo？

这个问题exports.swaggerdoc = {
  enable: true,
  package: 'egg-swagger-doc',
};
只要我把enable设置成true就会这样

**Comment by Aqincheng** [comment]
> 插件挂了，提个 demo？

目前我不知道问题出在哪里了，求大神帮忙

**Comment by czy88840616** [comment]
没个demo我也不知道问题出在哪里啊……
