### ISSUE TITLE
请问typgoose如何监听数据库连接状态

### ISSUE THREAD

**Issue by Logan80s** [midwayjs/midway#3255]
* **Node Version**:16.20.1.
* **Midway Version(Decorator/Core)**:3.12.4
* **Component Name/Version**:
* **Platform**: linux
* **Mini Showcase Repository**:

请问在使用typegoose的时候，如果获取MongoDB的数据库连接状态的连接状态回调，我是想在连接状态发送变化的时候，收到回调类似这样：
 // 监听连接状态并获取回调事件
    mongoose.connection.on('connected', () => {
      console.log('已建立数据库连接');
    });

    mongoose.connection.on('error', error => {
      console.error('数据库连接错误：', error);
    });

    mongoose.connection.on('disconnected', () => {
      console.log('数据库连接已断开');
    });

但是，以上我在ContainerLifeCycle中的onReady()方法中设置后，运行时获取mongoose会出现错误，如下：
ReferenceError: mongoose is not defined
    at eval (eval at onReady (/Users/logan/projects-st/SituVideo-Care-Server/src/configuration.ts:81:5), <anonymous>:1:1)
    at ContainerLifeCycle.onReady (/Users/logan/projects-st/SituVideo-Care-Server/src/configuration.ts:81:5)
    at MidwayLifeCycleService.runContainerLifeCycle (/Users/logan/projects-st/SituVideo-Care-Server/node_modules/@midwayjs/core/dist/service/lifeCycleService.js:94:67)
    at async MidwayLifeCycleService.init (/Users/logan/projects-st/SituVideo-Care-Server/node_modules/@midwayjs/core/dist/service/lifeCycleService.js:61:9)
    at async ObjectCreator.doInitAsync (/Users/logan/projects-st/SituVideo-Care-Server/node_modules/@midwayjs/core/dist/definitions/objectCreator.js:111:17)

**Comment by czy88840616** [comment]
typegoose底层使用了mongoose 组件，如需获取 mongoose 实例，参考 https://midwayjs.org/docs/extensions/mongodb#%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8-mongoose ，从 MongooseDataSourceManager 中获取 mongoose 实例再使用。

**Comment by Logan80s** [comment]
> typegoose底层使用了mongoose 组件，如需获取 mongoose 实例，参考 https://midwayjs.org/docs/extensions/mongodb#%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8-mongoose ，从 MongooseDataSourceManager 中获取 mongoose 实例再使用。

谢谢，按照您发的这个已经搞定
