### ISSUE TITLE
validate无法拦截socketio的校验错误

### ISSUE THREAD

**Issue by cakey90** [midwayjs/midway#3349]
### 🐛 Describe the bug（描述 bug）

socketio代码
```
@WSController('/')
export class TestSocketController {
  @OnWSMessage('createAccount')
  async createAccount(@Valid() dto: AccountAddDTO) {
    console.log(dto);
    return { status: 0, message: `发送成功!`, data: null };
  }
}
```
校验类代码
```
import { Rule, RuleType } from '@midwayjs/validate';

const strReq = RuleType.string().required();
export class GameAccountAddDTO {
  @Rule(strReq.min(5).max(15))
  name: string;

  @Rule(strReq.min(5).max(30))
  password: string;

  @Rule(strReq)
  server: string;
}
```
返回错误信息为:
```
2023-10-22 01:27:25,875 ERROR 11152 MidwayValidationError: "name" is not allowed to be empty
    at ValidateService.validateWithSchema (D:\projects\game\mh-midway\node_modules\@midwayjs\validate\dist\service.js:47:19)
    at DecoratorValidPipe.validateWithSchema (D:\projects\game\mh-midway\node_modules\@midwayjs\validate\dist\pipe.js:21:45)
    at DecoratorValidPipe.transform (D:\projects\game\mh-midway\node_modules\@midwayjs\validate\dist\pipe.js:69:21)
    at Object.before (D:\projects\game\mh-midway\node_modules\@midwayjs\core\dist\service\decoratorService.js:125:73)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GameSocketController.Clz.<computed> (D:\projects\game\mh-midway\node_modules\@midwayjs\core\dist\service\aspectService.js:87:21)
    at async D:\projects\game\mh-midway\node_modules\@midwayjs\socketio\dist\framework.js:151:44
    at async D:\projects\game\mh-midway\node_modules\@midwayjs\core\dist\baseFramework.js:277:40
    at async D:\projects\game\mh-midway\node_modules\@midwayjs\core\dist\baseFramework.js:271:24
    at async Socket.<anonymous> (D:\projects\game\mh-midway\node_modules\@midwayjs\socketio\dist\framework.js:134:48) {
  code: 'VALIDATE_10000',
  cause: [Error [ValidationError]: "name" is not allowed to be empty] {
    _original: { name: '', role: '', server: '' },
    details: [ [Object] ]
  },
  status: 422
}
```
已配置拦截
```
import { Catch } from '@midwayjs/core';
import { MidwayValidationError } from '@midwayjs/validate';
import { Context } from '@midwayjs/web';
import { Context as SocketContext } from '@midwayjs/socketio';

@Catch(MidwayValidationError)
export class ValidateErrorFilter {
  async catch(err: MidwayValidationError, ctx: Context | SocketContext) {
    // ...
    return {
      status: -999,
      message: '校验参数错误,' + err.message,
    };
  }
}
```
目前api访问, 校验是正确的, socketio不会拦截, 会直接报错

### Midway Versions（Midway 版本）

npx midway-version@latest

**Comment by cakey90** [comment]
校验类代码
```
import { Rule, RuleType } from '@midwayjs/validate';

const strReq = RuleType.string().required();
export class AccountAddDTO {
  @Rule(strReq.min(5).max(15))
  name: string;

  @Rule(strReq.min(5).max(30))
  password: string;

  @Rule(strReq)
  server: string;
}
```

**Comment by cakey90** [comment]
是我自己配置缺少了一行配置...
```
    this.socketapp.useFilter([ValidateErrorFilter]);
```
