### ISSUE TITLE
不能配置全局中间件

### ISSUE THREAD

**Issue by JoslynWu** [midwayjs/midway#364]
* **Node Version**: 12.10.0
* **Egg Version**: 2.10.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: macOS
* **Mini Showcase Repository**:

如图
<img width="998" alt="image" src="https://user-images.githubusercontent.com/12249826/69360047-ccf5b700-0cc4-11ea-8650-4e96d9aa9134.png">
我想使用全局中间件，但总是会报错。错误类似这样：
```typescript
midway-ts/node_modules/_egg-core@4.17.3@egg-core/lib/loader/mixin/middleware.js:66
        throw new TypeError(`Middleware ${name} not found`);
              ^
TypeError: Middleware trace not found
    at AppWorkerLoader.loadMiddleware (/midway-ts/node_modules/_egg-core@4.17.3@egg-core/lib/loader/mixin/middleware.js:66:15)
    at AppWorkerLoader.load (/midway-ts/node_modules/_midway-web@1.14.4@midway-web/src/loader/loader.ts:22:10)
    at new Application (/midway-ts/node_modules/_egg@2.25.0@egg/lib/application.js:66:19)
    at new MidwayApplication /midway-ts/node_modules/_midway-web@1.14.4@midway-web/dist/midway.js:11:9)
    at Object.<anonymous> (/midway-ts/node_modules/_egg-cluster@1.26.0@egg-cluster/lib/app_worker.js:21:13)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
```

- midway 的 1.0.0 和 1.14.4 我都测试，依旧失败。
- demo-extended-koa 可以跑起来，但是我不知道两者的差别在哪？
- 我新建一个 egg 项目是可以顺利使用全局中间件的。

请帮我看看问题在哪里？

**Comment by czy88840616** [comment]
全局中间件，需要放在 `app/middleware`  目录中。

**Comment by JoslynWu** [comment]
解决问题。
多谢，多谢！

另外，我有被 `midway-ts-strict` 模板干扰，（原来路由中间件才可以任意目录）

**Comment by czy88840616** [comment]
我们尽量在展现上把官方模板和社区模板做一些区分。
