### ISSUE TITLE
[Support] midwayjs似乎一直在尝试执行eval-stdin.php，请问这是否必须，如何关闭。

### ISSUE THREAD

**Issue by lptam3344** [midwayjs/midway#3909]
### Discussed in https://github.com/midwayjs/midway/discussions/3908

<div type='discussions-op-text'>

<sup>Originally posted by **lptam3344** June 17, 2024</sup>
### Describe the problem（描述问题）

2024-06-17 02:18:40.054 ERROR 1463351 NotFoundError: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php Not Found
    at notFound (/www/wwwroot/service/node_modules/@midwayjs/koa/dist/framework.js:135:23)
    at async /www/wwwroot/service/dist/modules/user/middleware/app.js:59:13
    at async /www/wwwroot/service/dist/modules/base/middleware/log.js:26:13
    at async /www/wwwroot/service/dist/modules/base/middleware/authority.js:147:13
    at async /www/wwwroot/service/node_modules/@midwayjs/i18n/dist/middleware.js:150:17
    at async bodyParser (/www/wwwroot/service/node_modules/koa-bodyparser/index.js:78:5)
    at async session (/www/wwwroot/service/node_modules/@midwayjs/session/dist/middleware/session.js:137:17)
    at async /www/wwwroot/service/node_modules/koa-static-cache/index.js:41:56
    at async /www/wwwroot/service/node_modules/@midwayjs/core/dist/baseFramework.js:273:40
    at async /www/wwwroot/service/node_modules/@midwayjs/core/dist/baseFramework.js:267:24 {
  code: '404',
  cause: undefined,
  status: 404
}

### Midway Versions（Midway 版本）

3.16.2</div>

**Comment by czy88840616** [comment]
这是刺探了这个路由吧，static 没访问到往后面走了，这就是静态走 / 的弊端。

**Comment by lptam3344** [comment]
> 这是刺探了这个路由吧，static 没访问到往后面走了，这就是静态走 / 的弊端。
谢谢回复。
不是很懂，大概是哪方面的原因，是反向代理设置的问题？
另外，貌似都是每天晚上log里才会有这个，每天1到2次，
还是我服务器被攻击了？

**Comment by czy88840616** [comment]
也不算被攻击吧，就是正常的外部探测，少量就随他了，404 而已，也不会怎么样

**Comment by lptam3344** [comment]
> 也不算被攻击吧，就是正常的外部探测，少量就随他了，404 而已，也不会怎么样

好的，谢谢，我在观察下，
一个nodejs总是尝试调用php的库，总让人感觉很不安。

**Comment by czy88840616** [comment]
这是外部来的请求，框架怎么可能会自己调php ..
