### ISSUE TITLE
monorepo 下 start 启动失败, midway is not found

### ISSUE THREAD

**Issue by yyyang1996** [midwayjs/midway#456]
项目采用的 `lerna` 和 `yarn workspace` 的 monorepo 方案, 启动方式是
```json
// package.json
"scripts": {
    "start": "node ./server.js"
}
```
```js
// server.js 
require('midway/server');
```
项目目录结构为
![zzz](https://user-images.githubusercontent.com/34713301/78457811-85a21d00-76df-11ea-8713-ec8fa885d779.png)

从目录结构可以看出, `server/node_modules` 里只有几个依赖, 剩下的依赖全部在最外层的 `node_modules` 里

报错信息:
```
$ node ./server.js
D:\project\shiki\node_modules\egg-utils\lib\framework.js:66
  throw new Error(`${frameworkName} is not found in ${Array.from(moduleDirs)}`);
  ^

Error: midway is not found in D:\project\shiki\packages\server\node_modules
    at assertAndReturn (D:\project\shiki\node_modules\egg-utils\lib\framework.js:66:9)
    at Object.getFrameworkPath (D:\project\shiki\node_modules\egg-utils\lib\framework.js:39:12)
    at module.exports (D:\project\shiki\node_modules\egg-cluster\lib\utils\options.js:28:29)
    at new Master (D:\project\shiki\node_modules\egg-cluster\lib\master.js:44:20)
    at new Master (D:\project\shiki\node_modules\midway\cluster\master.js:8:5)
    at Object.<anonymous> (D:\project\shiki\node_modules\midway\server.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
进入 `framework.js` 里看, 似乎只会从 `process.cwd()`的目录的 `node_modules` 查找依赖。
```js
const moduleDirs = new Set([
    moduleDir,
    // find framework from process.cwd, especially for test,
    // the application is in test/fixtures/app,
    // and framework is install in ${cwd}/node_modules
    path.join(process.cwd(), 'node_modules'),
    // prevent from mocking process.cwd
    path.join(initCwd, 'node_modules'),
  ]);
```

也许这不是一个Bug, 但我想知道这个问题是否有办法解决?

related issue: #341

**Comment by czy88840616** [comment]
我们之前修的应该是 `midway-bin dev --ts`  阶段的查找框架问题，你这个似乎是使用服务器环境启动的模式？？ `require('midway/server')`是给服务器上用的，理论上服务器上的目录结构不会是 monorepo 的情况吧？

**Comment by yyyang1996** [comment]
服务器上确实不是 monorepo, 因此正常运行。只不过本地 `yarn start` 的时候会报错。设置 "framework"后可以解决问题, 非常感谢。
