### ISSUE TITLE
创建新工程时报错,Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by wen495713** [midwayjs/midway#665]
macos 10.15.7
错误信息如下

man:learn_midwayjs man$ f create
Generating boilerplate...
✔ Hello, traveller.
  Which template do you like? · faas-standard - A serverless boilerplate for aliyun fc, tencent scf and so on
✔ The directory where the service should be created · my_new_serverless
npm ERR! Cannot read property 'resolve' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/man/.npm/_logs/2020-10-09T04_44_09_746Z-debug.log
Error: Command failed: npm view @midwayjs/faas-boilerplate-standard dist-tags --json 
npm ERR! Cannot read property 'resolve' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/man/.npm/_logs/2020-10-09T04_44_09_746Z-debug.log

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at NpmPatternGenerator.getPackage (/usr/local/lib/node_modules/@midwayjs/faas-cli/node_modules/_light-generator@1.6.1@light-generator/src/generator/NpmPatternGenerator.ts:30:18)
    at NpmPatternGenerator.getTemplateConfig (/usr/local/lib/node_modules/@midwayjs/faas-cli/node_modules/_light-generator@1.6.1@light-generator/src/generator/NpmPatternGenerator.ts:79:16)
    at NpmPatternGenerator.getParameterList (/usr/local/lib/node_modules/@midwayjs/faas-cli/node_modules/_light-generator@1.6.1@light-generator/src/generator/CommonGenerator.ts:61:40)
    at CreatePlugin.createFromTemplate (/usr/local/lib/node_modules/@midwayjs/faas-cli/node_modules/_@midwayjs_fcli-plugin-create@1.2.18@@midwayjs/fcli-plugin-create/src/index.ts:144:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at CreatePlugin.create (/usr/local/lib/node_modules/@midwayjs/faas-cli/node_modules/_@midwayjs_fcli-plugin-create@1.2.18@@midwayjs/fcli-plugin-create/src/index.ts:106:7)
    at CommandHookCore.execLiftcycle (/usr/local/lib/node_modules/@midwayjs/faas-cli/node_modules/_@midwayjs_fcli-command-core@1.2.12@@midwayjs/fcli-command-core/src/core.ts:175:11)
    at CommandHookCore.invoke (/usr/local/lib/node_modules/@midwayjs/faas-cli/node_modules/_@midwayjs_fcli-command-core@1.2.12@@midwayjs/fcli-command-core/src/core.ts:154:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 7b 0a 20 20 22 65 72 72 6f 72 22 3a 20 7b 0a 20 20 20 20 22 73 75 6d 6d 61 72 79 22 3a 20 22 43 61 6e 6e 6f 74 20 72 65 61 64 20 70 72 6f 70 65 72 74 ... 50 more bytes>,
    <Buffer 6e 70 6d 20 45 52 52 21 20 43 61 6e 6e 6f 74 20 72 65 61 64 20 70 72 6f 70 65 72 74 79 20 27 72 65 73 6f 6c 76 65 27 20 6f 66 20 75 6e 64 65 66 69 6e ... 127 more bytes>
  ],
  pid: 9619,
  stdout: <Buffer 7b 0a 20 20 22 65 72 72 6f 72 22 3a 20 7b 0a 20 20 20 20 22 73 75 6d 6d 61 72 79 22 3a 20 22 43 61 6e 6e 6f 74 20 72 65 61 64 20 70 72 6f 70 65 72 74 ... 50 more bytes>,
  stderr: <Buffer 6e 70 6d 20 45 52 52 21 20 43 61 6e 6e 6f 74 20 72 65 61 64 20 70 72 6f 70 65 72 74 79 20 27 72 65 73 6f 6c 76 65 27 20 6f 66 20 75 6e 64 65 66 69 6e ... 127 more bytes>
}
man:learn_midwayjs man$ node --version
v12.16.3

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/95544605-304c1d00-0a2e-11eb-9329-3e437164b283.png)

我刚重新安装了工具链并创建了一个似乎没有问题，堆栈里执行的是个 npm 命令，可能是 npm 内部抛的错。

**Comment by czy88840616** [comment]
实在不行，脚手架代码在这里，可以直接下载 https://github.com/midwayjs/midway-boilerplate/tree/master/faas-boilerplate-standard/boilerplate。

**Comment by wen495713** [comment]
确实我的环境有问题,抱歉抱歉
