### ISSUE TITLE
在faas-standard项目中如何使用jest测试

### ISSUE THREAD

**Issue by yoodu** [midwayjs/midway#711]
使用f test能够成功测试，但用jest（按 [docs: 增加 Jest 使用文档](https://github.com/midwayjs/midway/pull/358/commits/5153c521ce9c4a3d55ce0ea158517406cc2529e7) 配置）会报错：
```
 ● /test/index.test.ts › should use default event

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

       7 | 
       8 | describe('/test/index.test.ts', () => {
    >  9 |   it('should use default event', async () => {
         |   ^
      10 |     const result = await invoke({
      11 |       functionName: 'test',
      12 |       data: [

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (test/index.test.ts:9:3)
```

**Comment by czy88840616** [comment]
貌似函数的jest配置没开出来，用这个看看 https://www.yuque.com/midwayjs/midway_v2/testing#ewxph

**Comment by czy88840616** [comment]
2.x 已经可以用 jest了
