### ISSUE TITLE
midway添加了egg plugin之后执行f deploy报错

### ISSUE THREAD

**Issue by nmvr2600** [midwayjs/midway#766]
添加了egg-redis插件之后，执行f deploy报错，本地yarn dev正常

Error: Command failed: yarn build
Error: TS Error: Cannot find name 'Singleton'.(node_modules/egg-redis/index.d.ts)
    at BuildPlugin.emit (/Users/macyou/workspace-incubator/spark-mw-fc/node_modules/@midwayjs/cli-plugin-build/src/index.ts:109:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CommandCore.execLiftcycle (/Users/macyou/workspace-incubator/spark-mw-fc/node_modules/@midwayjs/command-core/src/core.ts:190:11)
    at CommandCore.invoke (/Users/macyou/workspace-incubator/spark-mw-fc/node_modules/@midwayjs/command-core/src/core.ts:167:5)
    at CLI.start (/Users/macyou/workspace-incubator/spark-mw-fc/node_modules/@midwayjs/command-core/src/cli.ts:155:5)
error Command failed with exit code 1.

**Comment by czy88840616** [comment]
看起来是 egg-redis 的定义问题。

**Comment by czy88840616** [comment]
三方的定义报错，可以使用将tsconfig中的 skipLibCheck 值设置为 true ，让ts构建时跳过 *.d.ts  文件的类型检查。

最好也能去该库提 issue，推进解决。
