### ISSUE TITLE
安装即错误

### ISSUE THREAD

**Issue by xf789050** [midwayjs/midway#781]
先说下我的安装步骤，请大神帮我看看哪里错了，谢谢啦！！！
1. 安装了nodejs；
2. 更改了npm镜像源为淘宝；
3. 运行命令 `npm install @midwayjs/faas-cli -g`；
然后就一大堆的错误......
![image](https://user-images.githubusercontent.com/6984456/103302591-fabc3c00-4a3e-11eb-8e72-a90c86cd368d.png)

**Comment by iosh** [comment]
看报错是缺少python3. 安装一下.

**Comment by czy88840616** [comment]
恩，环境问题，看起来是某个包走到了 gyp，然后要编译。。。

**Comment by jacob-lcs** [comment]
可是截图中不是找到了 Python3 吗，需要重新安装？

**Comment by czy88840616** [comment]
降级为 node14/npm6 再安装。

**Comment by czy88840616** [comment]
我们发现，在 node15/npm7 下执行 npm install/i 命令安装依赖会有 Python 编译错误，原因是测试框架 Jest 依赖 jsdom，npm7 会自动安装其 peerDependencies 中依赖的 canvas 包， 而 canvas 的安装编译需要有python3环境。

jest 的新测试版本已经移除了该依赖，还需要等其发版。

**Comment by xmsz** [comment]
npm run deploy
```
npm ERR! code 1
npm ERR! path /Users/xmsz/code/ele-20201214/server/.serverless/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.16.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.8 found at "/usr/local/opt/python@3.8/bin/python3.8"
npm ERR! gyp info spawn /usr/local/opt/python@3.8/bin/python3.8
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/xmsz/code/ele-20201214/server/.serverless/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/xmsz/Library/Caches/node-gyp/14.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/xmsz/Library/Caches/node-gyp/14.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/xmsz/Library/Caches/node-gyp/14.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/xmsz/code/ele-20201214/server/.serverless/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Package pixman-1 was not found in the pkg-config search path.
npm ERR! Perhaps you should add the directory containing `pixman-1.pc'
npm ERR! to the PKG_CONFIG_PATH environment variable
npm ERR! No package 'pixman-1' found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Darwin 19.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/xmsz/code/ele-20201214/server/.serverless/node_modules/canvas
npm ERR! gyp ERR! node -v v14.16.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xmsz/.npm/_logs/2021-06-27T08_05_38_258Z-debug.log
```
现在还是这样
