### ISSUE TITLE
is not valid in current context

### ISSUE THREAD

**Issue by falstack** [midwayjs/midway#784]
我仿照 [@midway/orm](https://github.com/midwayjs/midway-component/tree/master/packages/orm) 的代码写了一个包 [@calibur/fass](https://github.com/calibur-tv/CaliburOpenAPI/tree/master/packages/vendor)，但是在 [sign](https://github.com/calibur-tv/CaliburOpenAPI/tree/master/packages/sign) 调用的时候却报错了：

- 在 sign 文件夹下`npm run dev`
- 访问`localhost:3000/hello`
- 得到报错：
```node.js
NotFoundError: redis in class IndexController is not valid in current context
    at MidwayContainer.getAsync (/Users/yuistack/Documents/calibur/fc/node_modules/@midwayjs/core/dist/context/applicationContext.js:174:19)
    at MidwayContainer.getAsync (/Users/yuistack/Documents/calibur/fc/node_modules/@midwayjs/core/dist/context/midwayContainer.js:404:33)
    at MidwayRequestContainer.getAsync (/Users/yuistack/Documents/calibur/fc/node_modules/@midwayjs/core/dist/context/requestContainer.js:75:32)
    at RefResolver.resolveAsync (/Users/yuistack/Documents/calibur/fc/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:105:38)
    at ManagedResolverFactory.resolveManagedAsync (/Users/yuistack/Documents/calibur/fc/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:298:25)
    at ManagedResolverFactory.createAsync (/Users/yuistack/Documents/calibur/fc/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:444:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at MidwayRequestContainer.getAsync (/Users/yuistack/Documents/calibur/fc/node_modules/@midwayjs/core/dist/context/requestContainer.js:67:29)
    at FaaSStarter.invokeHandler (/Users/yuistack/Documents/calibur/fc/node_modules/@midwayjs/faas/src/starter.ts:199:23) {
  [Symbol(#NotFoundError)]: Symbol(#NotFoundError)
```

代码是仿照 midwayORM 写的，不知道为什么会报这个错，能帮忙看看吗？

**Comment by czy88840616** [comment]
参考组件开发 https://www.yuque.com/midwayjs/midway_v2/component_development
