### ISSUE TITLE
midway2 咋用底层amqplib发消息给RabbitMQ一直报错呢？

### ISSUE THREAD

**Issue by salamander-mh** [midwayjs/midway#787]
用最简单的`sendToQueue`方法，就一直报错。

**Comment by czy88840616** [comment]
报错代码？复现demo？错误截图？

**Comment by salamander-mh** [comment]
**rabbit.ts**
```
import { provide, scope, ScopeEnum, init, config, EggAppConfig } from 'midway';
const amqp = require('amqplib')


@scope(ScopeEnum.Singleton) // Singleton 单例，全局唯一（进程级别）
@provide('rabbit')
export class Rabbit {
  @config('rabbitmq')
  options!: EggAppConfig['rabbitmq'];

  client;

  async getMQConnection(options) {
    return await amqp.connect({
      protocol: 'amqp',
      hostname: options.host,
      port: options.port,
      username: options.user,
      password: options.pass,
      locale: 'en_US',
      frameMax: 0,
      heartbeat: options.heartbeat, // 心跳
      vhost: options.vhost,
    })
  }

  async sendToQueue() {
    const channel = await this.client.createConfirmChannel()
    let testData = {"id": 66666}
    channel.publish('', 'push_task', Buffer.from(JSON.stringify(testData)), { persistent: true, mandatory: true });
    await channel.waitForConfirms();
    await channel.close();
  }

  @init()
  connect() {
    this.getMQConnection(this.options).then((conn) => {
      this.client = conn;
    })
  }
}
```
**app.ts**
```
import { Application } from 'midway';

export default (app: Application) => {
  app.beforeStart(async () => {
    const rabbit = await app.applicationContext.getAsync('rabbit');
    await rabbit.sendToQueue();
  });
};
```
`yarn dev`就报错了：
```
2021-01-04 16:27:16,094 ERROR 18477 nodejs.TypeError: Cannot read property 'getTargetQueues' of undefined
    at Object.publish (/home/salamander/文档/bxh_admin/node_modules/@midwayjs/mock/dist/client/rabbitMQ.js:226:41)
    at Rabbit.sendToQueue (/home/salamander/文档/bxh_admin/src/app/foundation/rabbit/rabbit.ts:30:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /home/salamander/文档/bxh_admin/src/app.ts:7:5
```

**Comment by stone-jin** [comment]
@salamander-mh 修复了你反馈的问题，下一次版本包会进行修复
