### ISSUE TITLE
自定义日志文件没有按天切割

### ISSUE THREAD

**Issue by rickyes** [midwayjs/midway#822]
* **Node Version**: v14.14.0
* **Egg Version**: v2.1.0
* **Platform**: Linux
* **Mini Showcase Repository**: 

暂时复现不了，可以参考以下配置：

https://github.com/rickyes/midway-log-bug/blob/edc447155cca7ab2a66d952dff57c816c3e0f2ad/src/config/config.default.ts#L21-L25

日志文件只停留在 23 号：
```sh
lrwxrwxrwx 1 root root    21 Jan 23 16:13 access.log -> access.log.2021-01-23
-rw-r--r-- 1 root root 64535 Jan 23 17:31 access.log.2021-01-23
```

感觉文件的内容也不全，日志内容停留在重启后的一个多小时之后，不知道有什么想法可以排查下

**Comment by czy88840616** [comment]
是怎么重启的？到了新的一天没有打出新的一天的日志？

**Comment by rickyes** [comment]
重启走的 docker ,  重启当天有新的日志文件，第二天之后就没有了

**Comment by czy88840616** [comment]
机器的时区是？

**Comment by rickyes** [comment]
GMT+8

**Comment by czy88840616** [comment]
似乎没有发现，我去找一些机器看看

**Comment by eon-lee96** [comment]
@czy88840616 https://github.com/eon-lee96/midway-test-logger 看看这个repo

复现步骤
1. `yarn build`
2. `yarn start`
3. 打开浏览器`127.0.0.1:7001`
4. 疯狂刷新页面，等一批log写入后，再缓慢更新
5. 观察是否丢失了部分log

**Comment by czy88840616** [comment]
我复现了日志在高并发写入后，无法再写入内容的问题，还在排查 ，表现在

- 1、cluster 4worker ctx logger 出现问题
- 2、cluster 1worker ctx logger  出现问题
- 3、cluster 1worker app logger 出现问题
- 4、cluster 1worker 直接从 @midwayjs/logger 创建日志对象 ，没有出现问题

**Comment by czy88840616** [comment]
可以将 @midwayjs/web 降回到 2.5.x 使用 egg-logger，下个版本我会加个开关，让 egg日志和 midway 日志分离。

**Comment by rickyes** [comment]
`@midwayjs/web` 降回 `2.5.5` 启动不了:

```sh
[ Midway ] start error: Cannot read property 'info' of undefined
TypeError: Cannot read property 'info' of undefined
    at new Agent (/Users/ricky/projj/xxx/webs/shopline-static/xxxx-server/node_modules/egg/lib/agent.js:29:21)
    at new EggAgent (/Users/ricky/projj/xxx/webs/shopline-static/xxxx-server/node_modules/@midwayjs/web/dist/base.js:210:13)
    at new EggAgent (/Users/ricky/projj/xxx/webs/shopline-static/xxxx-server/node_modules/@midwayjs/web/dist/application.js:21:1)
    at module.exports (/Users/ricky/projj/xxx/webs/shopline-static/xxxx-server/node_modules/egg/lib/start.js:31:17)
    at MidwayDevFramework.initialize (/Users/ricky/projj/xxx/webs/shopline-static/xxxx-server/node_modules/@midwayjs/web/dist/devFramework.js:37:26)
    at /Users/ricky/projj/xxx/webs/shopline-static/xxxx-server/node_modules/@midwayjs/bootstrap/dist/bootstrap.js:44:32
    at Array.map (<anonymous>)
    at BootstrapStarter.getActions (/Users/ricky/projj/xxx/webs/shopline-static/xxxx-server/node_modules/@midwayjs/bootstrap/dist/bootstrap.js:43:36)
    at BootstrapStarter.init (/Users/ricky/projj/xxx/webs/shopline-static/xxxx-server/node_modules/@midwayjs/bootstrap/dist/bootstrap.js:30:32)
    at create (/Users/ricky/projj/xxx/webs/shopline-static/xxxx-server/node_modules/@midwayjs/mock/dist/utils.js:94:19)
```

**Comment by czy88840616** [comment]
估计是其他包得同步降。
