### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#830]
```
[Error Message] window is not defined.
ReferenceError: window is not defined
    at /Users/project/.faas_debug_tmp/build/web/index.js:34:41
    at Object.<anonymous> (/Users/project/.faas_debug_tmp/build/web/index.js:1028:10)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module._compile (/Users/project/node_modules/_pirates@4.0.1@pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.newLoader [as .js] (/Users/project/node_modules/_pirates@4.0.1@pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at MidwayContainer.loadDirectory (/Users/project/node_modules/_@midwayjs_core@2.7.0@@midwayjs/core/dist/context/midwayContainer.js:137:33)
    at MidwayContainer.load (/Users/project/node_modules/_@midwayjs_core@2.7.0@@midwayjs/core/dist/context/midwayContainer.js:92:18)
    at MidwayFaaSFramework.containerDirectoryLoad (/Users/project/node_modules/_@midwayjs_core@2.7.0@@midwayjs/core/dist/baseFramework.js:121:33)
    at MidwayFaaSFramework.initialize (/Users/project/node_modules/_@midwayjs_core@2.7.0@@midwayjs/core/dist/baseFramework.js:55:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ReferenceError: window is not defined
    at /Users/project/.faas_debug_tmp/build/web/index.js:34:41
    at Object.<anonymous> (/Users/project/.faas_debug_tmp/build/web/index.js:1028:10)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module._compile (/Users/project/node_modules/_pirates@4.0.1@pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.newLoader [as .js] (/Users/project/node_modules/_pirates@4.0.1@pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at MidwayContainer.loadDirectory (/Users/project/node_modules/_@midwayjs_core@2.7.0@@midwayjs/core/dist/context/midwayContainer.js:137:33)
    at MidwayContainer.load (/Users/project/node_modules/_@midwayjs_core@2.7.0@@midwayjs/core/dist/context/midwayContainer.js:92:18)
    at MidwayFaaSFramework.containerDirectoryLoad (/Users/project/node_modules/_@midwayjs_core@2.7.0@@midwayjs/core/dist/baseFramework.js:121:33)
    at MidwayFaaSFramework.initialize (/Users/project/node_modules/_@midwayjs_core@2.7.0@@midwayjs/core/dist/baseFramework.js:55:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

直接炸了，但是依赖太多根本找不出来是哪个影响的 也退不回去

**Comment by Lxxyx** [comment]
看看 src/apis 下面的代码哪里用了 window，或者是否 src/apis 下的代码引用了前端的代码

**Comment by xmsz** [comment]
> window

src/apis下没有用到windows和引用前端代码

然后神奇的是我本来想打算拷贝一个repo，结果一模一样的代码，现在不出现这个提示，但是出现
```
Please use in compiled mode
useContext.js:5 Uncaught (in promise) Error: Please use in compiled mode
    at Object.useContext (useContext.js:5)
    at useInject (useInject.js:6)
    at useDB.ts:4
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tslib.es6.js:74
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70)
    at useDB (useDB.ts:3)
    at index.ts:18
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tslib.es6.js:74
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70)
    at getHomeInfoApi (index.ts:11)
    at home.ts:6
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tslib.es6.js:74
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70)
    at HomeService.getInfo (home.ts:4)
    at index.tsx:96
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tslib.es6.js:74
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70)
    at index.tsx:95
    at index.tsx:129
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tslib.es6.js:74
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70)
    at initData (index.tsx:125)
    at index.tsx:125
    at __create (hooks.js:141)
    at hooks.js:136
    at invokeFunctionsWithClear (scheduler.js:28)
    at flushEffect (scheduler.js:55)
useContext @ useContext.js:5
useInject @ useInject.js:6
(anonymous) @ useDB.ts:4
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
useDB @ useDB.ts:3
(anonymous) @ index.ts:18
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
getHomeInfoApi @ index.ts:11
(anonymous) @ home.ts:6
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
getInfo @ home.ts:4
(anonymous) @ index.tsx:96
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
(anonymous) @ index.tsx:95
(anonymous) @ index.tsx:129
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
initData @ index.tsx:125
(anonymous) @ index.tsx:125
__create @ hooks.js:141
(anonymous) @ hooks.js:136
invokeFunctionsWithClear @ scheduler.js:28
flushEffect @ scheduler.js:55
Promise.then (async)
step @ tslib.es6.js:73
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
initData @ index.tsx:125
(anonymous) @ index.tsx:125
__create @ hooks.js:141
(anonymous) @ hooks.js:136
invokeFunctionsWithClear @ scheduler.js:28
flushEffect @ scheduler.js:55
setTimeout (async)
scheduler @ scheduler.js:20
scheduleEffect @ scheduler.js:48
__destory @ hooks.js:165
(anonymous) @ hooks.js:194
invokeFunctionsWithContext @ invokeFunctionsWithContext.js:8
componentDidUpdate @ reactive.js:135
(anonymous) @ composite.js:379
performInSandbox @ performInSandbox.js:17
(anonymous) @ composite.js:58
invokeFunctionsWithClear @ scheduler.js:28
flushLayout @ scheduler.js:63
runUpdate @ updater.js:59
performUpdate @ updater.js:91
invokeFunctionsWithClear @ scheduler.js:28
flush @ scheduler.js:43
setTimeout (async)
scheduler @ scheduler.js:20
schedule @ scheduler.js:35
scheduleUpdate @ updater.js:107
requestUpdate @ updater.js:132
setState @ updater.js:151
setState @ component.js:22
__update @ reactive.js:144
setState @ hooks.js:96
(anonymous) @ createTabBar.js:75
__create @ hooks.js:141
(anonymous) @ hooks.js:136
invokeFunctionsWithClear @ scheduler.js:28
flushEffect @ scheduler.js:55
setState @ hooks.js:77
(anonymous) @ index.tsx:148
__create @ hooks.js:141
(anonymous) @ hooks.js:136
invokeFunctionsWithClear @ scheduler.js:28
flushEffect @ scheduler.js:55
setState @ hooks.js:77
(anonymous) @ index.tsx:26
__create @ hooks.js:141
(anonymous) @ hooks.js:136
invokeFunctionsWithClear @ scheduler.js:28
flushEffect @ scheduler.js:55
setTimeout (async)
scheduler @ scheduler.js:20
scheduleEffect @ scheduler.js:48
__create @ hooks.js:135
invokeFunctionsWithContext @ invokeFunctionsWithContext.js:8
componentDidMount @ reactive.js:127
(anonymous) @ composite.js:185
measureLifeCycle @ composite.js:51
(anonymous) @ composite.js:184
performInSandbox @ performInSandbox.js:17
(anonymous) @ composite.js:58
invokeFunctionsWithClear @ scheduler.js:28
flushLayout @ scheduler.js:63
runUpdate @ updater.js:59
performUpdate @ updater.js:91
scheduleUpdate @ updater.js:109
requestUpdate @ updater.js:139
forceUpdate @ updater.js:154
forceUpdate @ component.js:26
__update @ root.js:41
mount @ instance.js:102
render @ render.js:25
(anonymous) @ renderer.js:181
Promise.then (async)
_renderApp @ renderer.js:141
(anonymous) @ renderer.js:122
step @ renderer.js:43
(anonymous) @ renderer.js:24
(anonymous) @ renderer.js:18
./node_modules/rax-app-renderer/lib/renderer.js.__awaiter @ renderer.js:14
raxAppRenderer @ renderer.js:96
runApp @ runApp.ts:50
./src/app.ts @ app.ts:2
__webpack_require__ @ bootstrap:837
fn @ bootstrap:129
1 @ app.ts:2
__webpack_require__ @ bootstrap:837
(anonymous) @ bootstrap:1024
(anonymous) @ bootstrap:1024
Show 12 more frames
```
![image](https://user-images.githubusercontent.com/5879146/106154858-04aa9980-61bb-11eb-826d-e2ef97966001.png)

**Comment by Lxxyx** [comment]
目前 hooks 得配合着编译器一起用的，编译器的配置在 f.yml 里，单独拷过去是用不了的

**Comment by xmsz** [comment]
再稍等我一下 我一个一个依赖升级试试看

**Comment by xmsz** [comment]
先记录一下

我直接拷贝项目，运行报`Please use in compiled mode`，发现和原项目不同的是依赖版本不同

一个一个尝试更新依赖，发现只要重新安装了`@midwayjs/faas-cli`，就会报`window is not defined`

@midwayjs/faas-cli本来本身1.2.35，只要升级这个包就会出错，但是后来发现并不是这个包问题，而是更新这个包的时候，同时更新了其他的包

现在就在看到底是哪个包影响

**Comment by xmsz** [comment]
@Lxxyx  这是https://github.com/xmsz/demo-20210128 我的项目

- 去掉src/apis/lambda/home/index.ts的`const ctx = useContext();`就能正常跑
- 升级到`@midwayjs/bootstrap@2.6.10`以上就能复现`window is not defined`
