### ISSUE TITLE
grpc报错问题

### ISSUE THREAD

**Issue by giter-chenpan** [midwayjs/midway#945]
* **Node Version**:  v12.13.0
* **Egg Version**: 2.0.0
* **Plugin Name**:@midwayjs/grpc
* **Plugin Version**:2.9.0
* **Platform**:mac
* **Mini Showcase Repository**: https://github.com/giter-chenpan/midway-stu.git

在配置gRPC调用方时启动报如下：
2021-03-24 22:12:06,305 INFO 12365 [midway:gRPC] Find 0 class has gRPC provider decorator
TypeError: this.configurationOptions.services is not iterable
    at MidwayGRPCFramework.loadService (/Users/chenpan/Desktop/doc/test/node-stu/midwayApp/node_modules/@midwayjs/grpc/dist/provider/framework.js:33:57)
    at MidwayGRPCFramework.afterContainerReady (/Users/chenpan/Desktop/doc/test/node-stu/midwayApp/node_modules/@midwayjs/grpc/dist/provider/framework.js:22:20)
    at MidwayGRPCFramework.initialize (/Users/chenpan/Desktop/doc/test/node-stu/midwayApp/node_modules/@midwayjs/grpc/node_modules/@midwayjs/core/dist/baseFramework.js:78:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at BootstrapStarter.init (/Users/chenpan/Desktop/doc/test/node-stu/midwayApp/node_modules/@midwayjs/bootstrap/dist/bootstrap.js:31:9)
    at create (/Users/chenpan/Desktop/doc/test/node-stu/midwayApp/node_modules/@midwayjs/mock/dist/utils.js:152:5)
    at Object.createApp (/Users/chenpan/Desktop/doc/test/node-stu/midwayApp/node_modules/@midwayjs/mock/dist/utils.js:159:23)

**Comment by czy88840616** [comment]
额，这个原因是 dev 启动的时候会找到第一个框架来加载，解决方法比较简单，只要把 @midwayjs/grpc": "^2.9.0", 放到 @midwayjs/web 下面就行。。。
