### ISSUE TITLE
bootstrap启动socket框架后，接口报错

### ISSUE THREAD

**Issue by 329988300** [midwayjs/midway#969]
// bootstrap.js

const WebFramework = require('@midwayjs/web').Framework;
const SocketFramework = require('@midwayjs/socketio').Framework;
const { Bootstrap } = require('@midwayjs/bootstrap');

// 加载主 web 框架
const webFramework = new WebFramework().configure({
  port: 7001,
});

// 加载副 socket.io 框架，自动适配主框架
const socketFramework = new SocketFramework().configure({});

Bootstrap.load(webFramework).load(socketFramework).run();

// console log
2021-04-05T08:41:09.637+08:00 ERROR 57415 [-/127.0.0.1/6784635978158964736/1ms POST /logout] TypeError: opts.matching is not a function
    at Object.checkIfIgnore (/Users/zhangao30/Documents/projects/service-mw2/node_modules/egg-security/lib/utils.js:56:16)
    at Object.assertCsrf (/Users/zhangao30/Documents/projects/service-mw2/node_modules/egg-security/app/extend/context.js:151:15)
    at csrf (/Users/zhangao30/Documents/projects/service-mw2/node_modules/egg-security/lib/middlewares/csrf.js:33:9)
    at dispatch (/Users/zhangao30/Documents/projects/service-mw2/node_modules/koa-compose/index.js:42:32)
    at /Users/zhangao30/Documents/projects/service-mw2/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/zhangao30/Documents/projects/service-mw2/node_modules/koa-compose/index.js:42:32)
    at session (/Users/zhangao30/Documents/projects/service-mw2/node_modules/koa-session/index.js:41:13)
    at dispatch (/Users/zhangao30/Documents/projects/service-mw2/node_modules/koa-compose/index.js:42:32)
    at overrideMethod (/Users/zhangao30/Documents/projects/service-mw2/node_modules/koa-override/index.js:38:12)
    at dispatch (/Users/zhangao30/Documents/projects/service-mw2/node_modules/koa-compose/index.js:42:32)

仓库地址：https://github.com/329988300/service-mw2
commit：“bug：missing matching”

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/113539284-0dcb4300-9610-11eb-8f95-862f1a5b4d2b.png)

暂未发现问题。
